### ISSUE TITLE
gnt-node add should warn when no hypervisor running / gnt-node list has bad error message when no hypervisor running

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#102]
Originally reported of Google Code with ID 46.

```
<b>What steps will reproduce the problem?</b>
1. install ganeti as described on three hosts until right before the first
gnt-* commands
2. BUT: boot one of the systems with Linux, not with a Hypervisor
3. run gnt-node add for all nodes
4. run gnt-node list

You get something like this:

Traceback (most recent call last):
  File "/usr/local/sbin/gnt-node", line 399, in ?
    sys.exit(GenericMain(commands, override={"tag_type": constants.TAG_NODE}))
  File "/usr/local/lib/python2.4/site-packages/ganeti/cli.py", line 497, in
GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-node", line 62, in ListNodes
    output = SubmitOpCode(op)
  File "/usr/local/lib/python2.4/site-packages/ganeti/cli.py", line 389, in
SubmitOpCode
    return proc.ExecOpCode(op)
  File "/usr/local/lib/python2.4/site-packages/ganeti/mcpu.py", line 136,
in ExecOpCode
    result = lu.Exec(self._feedback_fn)
  File "/usr/local/lib/python2.4/site-packages/ganeti/cmdlib.py", line
1528, in Exec
    live_data[name] = {
KeyError: 'cpu_total'


And after some time of searching, you realize, one of the systems has no
hypervisor running.


I'd expect the command return some warning or error (like when one of the
nodes is down, it's simply shown in the list with question marks).

Ideally, gnt-node add should already warn that it makes not sense ading a
node that doesn't run Xen.


```
Originally added on 2008-12-08 00:49:53 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi Henning,

This bad behaviour is fixed in SVN, will be released as part of 1.2.7. The fix won't
be complete (you just get ? instead of the values), will look into implementing a
better fix for future releases.

thanks,
iustin
```
Originally added on 2008-12-08 15:15:37 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Great to see it become better in the next version!


In the long run/to make it real nice, I'd propose two parts to fix:

1)
gnt-node add should not add a note that doesn't run a hypervisor at all and refuse that.
One could have the the possibility to force or override the warning, because the user
might know what he's doing and for some reason want to add the node  now and _after_
that reboot into the hypervisor

2)
gnt-node list printing questionsmarks is already much nicer than we have it now, but
sure, it would be better if it printed something like "cannot reach hypervisor on
this node - please check"  or something like that.
```
Originally added on 2008-12-08 16:05:37 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Unfortunately, running things at gnt-node add time is hard to do, since we have a
very "ugly" procedure to add nodes to the cluster. If we would migrate to something
more easily to script (e.g. a python-based ssh client, like paramiko), then we could
do more things.

As for 2), it won't make sense to do that at gnt-node list time (IMHO), but
definitely at gnt-cluster verify. In there we can show more data than in the output
of node list (which is designed to be tabular and easy to parse from scripts).
```
Originally added on 2008-12-08 16:28:01 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hmm, but as I see it, losing some "machine-parseabilty" from the output of a user
command ( we are, currently, speaking of the primary UI - USER interface of Ganeti)
is not something I can easily accept as a reason for not making a command more
user-friendly or it's output easier to understand for a human.

I'm voting for making it the way I propose, and for machine-parseable output, one
could add an option "-p / --parseable" that might not contain things that will
confuse machines reading the outpout. That is common practice in many command-line
software development tools, so they provide output suitable for easy integration in,
for example, emacs.

For backwards compatibility, one could add a config option in /etc/ganeti/... where
people could set a default if they want userfriedly or machine-friendly ouput by
default...
```
Originally added on 2008-12-08 16:55:35 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you, for your clear, concise and clean explanation, my head feels better
already.<a href="http://www.webteameu.com">web design London</a>

Thanks and best regards
Tauqeer Aziz

```
Originally added on 2009-08-06 11:53:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2010-03-12 19:39:33 +0000 UTC.

Added to Milestone: Unplanned

**Comment by Ganeti-Issues-Migrator** [comment]
```
For the record, we've settled on making gnt-cluster verify the preferred way to flag/diagnose issues, so we won't add this to node list.

In the meantime, node add has been improved and if needed this could be checked at node add time, but I think this is low enough priority that I'm marking it WontFix. If anyone feels like working on it feel free to reopen.

regards,
iustin
```
Originally added on 2011-08-02 12:07:00 +0000 UTC.

Changed State: WontFix
Removed from Milestone: Unplanned
