### ISSUE TITLE
sphinx build error on CentOS7

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1036]
Originally reported of Google Code with ID 980.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

<b>What distribution are you using?</b>
CentOS 7
ganeti-2.10 / ganeti-2.11 from source
ghc-7.6 & cabal
python2 as python

<b>What steps will reproduce the problem?</b>
1. ./autogen.sh
2. ./configure [...]
3. make

<b>What is the expected output? What do you see instead?</b>
[...]
PYTHONPATH=. ENABLE_MANPAGES= COPY_DOC=1 \
./autotools/run-in-tempdir autotools/sphinx-wrapper /bin/sphinx-build -q -W -b html \
    -d . \
    -D version="2.11" \
    -D release="2.11.6" \
    -D graphviz_dot="" \
    -D enable_manpages="" \
    doc /home/ganeti/src/ganeti-2.11/$dir && \
rm -f $dir/.buildinfo $dir/objects.inv

Exception occurred:
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
The full traceback has been saved in /tmp/sphinx-err-uqfZJU.log, if you want to report the issue to the developers.

<b>Please provide any additional information below.</b>
# Sphinx version: 1.1.3
# Python version: 2.7.5
# Docutils version: 0.11 repository
# Jinja2 version: 2.7.2
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/html.py", line 419, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/site-packages/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/graphviz.py", line 243, in html_visit_graphviz
    render_dot_html(self, node, node['code'], node['options'])
  File "/usr/lib/python2.7/site-packages/sphinx/ext/graphviz.py", line 197, in render_dot_html
    fname, outfn = render_dot(self, code, options, format, prefix)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/graphviz.py", line 157, in render_dot
    p = Popen(dot_args, stdout=PIPE, stdin=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```
Originally added on 2014-10-22 20:21:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This seems as if sphinx is failing to invoke 'dot' from graphviz. Do you have graphviz installed? This looks very similar to [1].

[1] https://groups.google.com/forum/#!msg/sphinx-dev/UQYIVGcD2Dc/bROqgSQn8fAJ
```
Originally added on 2014-10-27 12:41:39 +0000 UTC.

Changed State: NeedFeedback

**Comment by Ganeti-Issues-Migrator** [comment]
```
no, it isn't installed (dot is missing too)

and if i try to install it with cabal i get the following message:

ganeti@node1 ~/src/ganeti-2.11 (git)-[stable-2.11] % cabal install graphviz
Resolving dependencies...
In order, the following would be installed:
colour-2.3.3 (new package)
dlist-0.7.1 (new package)
fgl-5.5.0.1 (new package)
text-1.1.1.3 (new version)
polyparse-1.9 (reinstall) changes: text-1.2.0.0 -> 1.1.1.3
wl-pprint-text-1.1.0.2 (new package)
graphviz-2999.17.0.1 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
cpphs-1.18.6
hlint-1.9.10
haskell-src-exts-1.16.0
Use --force-reinstalls if you want to install anyway.

```
Originally added on 2014-10-27 13:12:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This isn't a Haskell dependency, it's sphinx dependency. Probably the sphinx package doesn't require graphviz to be installed, but if it isn't present, it just fails. I'd suggest trying to install the CentOS graphviz package using the standard method and then trying again.
```
Originally added on 2014-10-27 13:22:59 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
ok, thanks - solved with:
$ yum install graphviz
```
Originally added on 2014-10-27 13:41:51 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Closing as this is a sphinx dependency issue, not a Ganeti issue.
```
Originally added on 2014-10-27 13:55:11 +0000 UTC.

Changed State: Invalid
