### ISSUE TITLE
Could not migrate instance ...: hypervisor returned failure

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1081]
Originally reported of Google Code with ID 1025.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

<b>What distribution are you using?</b>
# gnt-cluster --version
gnt-cluster (ganeti v2.11.6) 2.11.6
# gnt-cluster version
Software version: 2.11.6
Internode protocol: 2110000
Configuration format: 2110000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version v2.11.6
# hspace --version
hspace (ganeti) version v2.11.6
compiled with ghc 7.4
running on linux x86_64
# cat /etc/debian_version
7.8
# apt-cache policy ganeti
ganeti:
  Installed: 2.11.6-1~bpo70+1
  Candidate: 2.11.6-1~bpo70+1
  Package pin: 2.11.6-1~bpo70+1
  Version table:
 *** 2.11.6-1~bpo70+1 990
        100 http://debian.xxxxxxxx.de/debian/ wheezy-backports/main amd64 Packages
        100 /var/lib/dpkg/status
# kvm --version
QEMU emulator version 2.1.2 (Debian 2.1+dfsg-9~bpo70+1), Copyright (c) 2003-2008 Fabrice Bellard


<b>What steps will reproduce the problem?</b>
1. gnt-instance migrate -f zzzzzzzz

<b>What is the expected output? What do you see instead?</b>
Sun Feb  1 13:30:09 2015 Migrating instance zzzzzzzz.yyyyyy.xxxxxxxxx.de
Sun Feb  1 13:30:09 2015 * checking disk consistency between source and target
Sun Feb  1 13:30:10 2015 * switching node node2.yyyyyy.xxxxxxxxx.de to secondary mode
Sun Feb  1 13:30:10 2015 * changing into standalone mode
Sun Feb  1 13:30:11 2015 * changing disks into dual-master mode
Sun Feb  1 13:30:14 2015 * wait until resync is done
Sun Feb  1 13:30:15 2015 * preparing node2.yyyyyy.xxxxxxxxx.de to accept the instance
Sun Feb  1 13:30:16 2015 * migrating instance to node2.yyyyyy.xxxxxxxxx.de
Sun Feb  1 13:30:18 2015 * starting memory transfer
Sun Feb  1 13:30:18 2015 Migration failed, aborting
Sun Feb  1 13:30:19 2015 * switching node node2.yyyyyy.xxxxxxxxx.de to secondary mode
Sun Feb  1 13:30:20 2015 * changing into standalone mode
Sun Feb  1 13:30:20 2015 * changing disks into single-master mode
Sun Feb  1 13:30:22 2015 * wait until resync is done
Failure: command execution error:
Could not migrate instance zzzzzzzz.yyyyyy.xxxxxxxxx.de: hypervisor returned failure


<b>Please provide any additional information below.</b>
of the 10 VMs running with qemu-kvm 1.1 (machine_version=pc-1.1)
  8 failed (with the hypervisor returned failure) [debian 6-8, archlinux guests]
  1 crashed (like in https://code.google.com/p/ganeti/issues/detail?id=986) [dragonfly bsd; non-paravirtual net-dev]
  1 was successfull [centos 7]

I had upgraded to KVM 2.1 (wheezy => wheezy-backports) because of #986, but as the VMs are running pruductiv I can't really reboot them at the moment to change them to 2.1, thats why I tested it with the machine_version pc-1.1 what worked fine on my test-cluster.
  Migration of kvm 2.1 VMs seams to be running without problems.


tail -f /var/log/ganeti/*.log (on node1 / master)
==> commands.log <==
2015-02-01 13:30:22,633: gnt-instance migrate pid=21011 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/share/ganeti/2.11/ganeti/cli.py", line 2597, in GenericMain
    result = func(options, args)
  File "/usr/share/ganeti/2.11/ganeti/client/gnt_instance.py", line 817, in MigrateInstance
    SubmitOrSend(op, cl=cl, opts=opts)
  File "/usr/share/ganeti/2.11/ganeti/cli.py", line 2387, in SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn, opts=opts)
  File "/usr/share/ganeti/2.11/ganeti/cli.py", line 2352, in SubmitOpCode
    reporter=reporter)
  File "/usr/share/ganeti/2.11/ganeti/cli.py", line 2331, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/share/ganeti/2.11/ganeti/cli.py", line 2153, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/share/ganeti/2.11/ganeti/errors.py", line 510, in MaybeRaise
    raise errcls(*args)
OpExecError: Could not migrate instance freifunk.xxxx.zzzzzzzzzz.de: hypervisor returned failure

==> master-daemon.log <==
2015-02-01 13:30:22,686: ganeti-masterd pid=12872/Jq13/Job209902 INFO Finished job 209902, status = error


tail -f /var/log/ganeti/*.log (on node2)
==> node-daemon.log <==
2015-02-01 13:30:15,950: ganeti-noded pid=24764 INFO RunCmd /usr/bin/kvm -device '?'
2015-02-01 13:30:15,976: ganeti-noded pid=24764 INFO RunCmd /usr/lib/ganeti/kvm-ifup tap6
2015-02-01 13:30:15,987: ganeti-noded pid=24764 INFO RunCmd /usr/bin/kvm -name zzzzzzzz.yyyyyy.xxxxxxxxx.de -m 1024 -smp 1 -pidfile /var/run/ganeti/kvm-hypervisor/pid/zzzzzzzz.yyyyyy.xxxxxxxxx.de -balloon virtio,id=balloon,bus=pci.0,addr=0x3 -daemonize -machine pc-1.1 -mo
nitor unix:/var/run/ganeti/kvm-hypervisor/ctrl/zzzzzzzz.yyyyyy.xxxxxxxxx.de.monitor,server,nowait -serial unix:/var/run/ganeti/kvm-hypervisor/ctrl/zzzzzzzz.yyyyyy.xxxxxxxxx.de.serial,server,nowait -usb -device virtio-serial-pci,id=spice,bus=pci.0,addr=0x4 -device virtseri
alport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent -spice addr=0.0.0.0,port=11001,disable-ticketing -cpu host -vga qxl -uuid e219677e-c2e2-4a6d-9b34-8293b137b55a -runas freifunk -netdev type=tap,id=hotnic-c4640d2f-pci-6,fd
=8 -device virtio-net-pci,mac=00:e6:e7:81:95:fc,id=hotnic-c4640d2f-pci-6,bus=pci.0,addr=0x6,netdev=hotnic-c4640d2f-pci-6 -incoming tcp:10.165.94.2:8102 -qmp unix:/var/run/ganeti/kvm-hypervisor/ctrl/zzzzzzzz.yyyyyy.xxxxxxxxx.de.qmp,server,nowait -qmp unix:/var/run/ganeti/k
vm-hypervisor/ctrl/zzzzzzzz.yyyyyy.xxxxxxxxx.de.kvmd,server,nowait -boot c -device virtio-blk-pci,drive=hotdisk-e4b113da-pci-5,id=hotdisk-e4b113da-pci-5,bus=pci.0,addr=0x5 -drive file=/var/run/ganeti/instance-disks/zzzzzzzz.yyyyyy.xxxxxxxxx.de:0,format=raw,if=none,cache=w
riteback,id=hotdisk-e4b113da-pci-5,bus=0,unit=5
2015-02-01 13:30:16,158: ganeti-noded pid=24764 INFO RunCmd echo 'info cpus' |  /usr/bin/socat STDIO UNIX-CONNECT:/var/run/ganeti/kvm-hypervisor/ctrl/zzzzzzzz.yyyyyy.xxxxxxxxx.de.monitor
2015-02-01 13:30:16,682: ganeti-noded pid=24764 INFO RunCmd /usr/bin/kvm --help
2015-02-01 13:30:16,709: ganeti-noded pid=24764 INFO 0123:4567:890a::515:0:59426 POST /accept_instance HTTP/1.1 200
2015-02-01 13:30:19,141: ganeti-noded pid=24805 INFO 0123:4567:890a::515:0:59430 POST /instance_finalize_migration_dst HTTP/1.1 200
2015-02-01 13:30:19,837: ganeti-noded pid=24807 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_data
2015-02-01 13:30:20,249: ganeti-noded pid=24807 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_meta
2015-02-01 13:30:20,452: ganeti-noded pid=24807 INFO RunCmd drbdsetup secondary 25
2015-02-01 13:30:20,505: ganeti-noded pid=24807 INFO 0123:4567:890a::515:0:59432 POST /blockdev_close HTTP/1.1 200
2015-02-01 13:30:20,685: ganeti-noded pid=24816 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_data
2015-02-01 13:30:20,843: ganeti-noded pid=24816 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_meta
2015-02-01 13:30:20,883: ganeti-noded pid=24816 INFO RunCmd drbdsetup disconnect ipv4:10.165.94.2:11003 ipv4:10.165.94.1:11003
2015-02-01 13:30:20,934: ganeti-noded pid=24816 INFO 0123:4567:890a::515:0:59434 POST /drbd_disconnect_net HTTP/1.1 200
2015-02-01 13:30:21,157: ganeti-noded pid=24820 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_data
2015-02-01 13:30:21,223: ganeti-noded pid=24820 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_meta
2015-02-01 13:30:21,260: ganeti-noded pid=24820 INFO RunCmd drbdsetup disk-options 25 --resync-rate 98304
2015-02-01 13:30:21,276: ganeti-noded pid=24820 INFO RunCmd drbdsetup connect resource25 ipv4:10.165.94.2:11003 ipv4:10.165.94.1:11003 --protocol C --after-sb-0pri discard-zero-changes --after-sb-1pri consensus --cram-hmac-alg md5 --shared-secret b2849485ad5a8580db93238b0
05332a1307c8b47
2015-02-01 13:30:21,279: ganeti-noded pid=24820 INFO RunCmd drbdsetup show 25
2015-02-01 13:30:21,327: ganeti-noded pid=24820 INFO RunCmd drbdsetup disk-options 25 --resync-rate 98304
2015-02-01 13:30:22,171: ganeti-noded pid=24820 INFO 0123:4567:890a::515:0:59436 POST /drbd_attach_net HTTP/1.1 200
2015-02-01 13:30:22,329: ganeti-noded pid=24835 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_data
2015-02-01 13:30:22,478: ganeti-noded pid=24835 INFO RunCmd lvs --noheadings '--separator=|' --units=k --nosuffix -olv_attr,lv_kernel_major,lv_kernel_minor,vg_extent_size,stripes,devices /dev/lvm/6675cc68-f247-44e4-b56c-f1a15af280c4.disk0_meta
2015-02-01 13:30:22,526: ganeti-noded pid=24835 INFO 0123:4567:890a::515:0:59438 POST /drbd_wait_sync HTTP/1.1 200
2015-02-01 13:30:22,703: ganeti-noded pid=24838 INFO 0123:4567:890a::515:0:59439 POST /jobqueue_update HTTP/1.1 200

```
Originally added on 2015-02-01 15:00:02 +0000 UTC.

Mentioned Issue with GoogleCode ID 986 has been migrated to GitHub with ID #1042.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-02-05 13:20:11 +0000 UTC.

Added Labels: Type-Defect
Changed State: Accepted
Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
This seems like a hypervisor issue and we're not sure if there is anything we can do in Ganeti. If there is more evidence, please reopen.
```
Originally added on 2015-04-08 13:58:26 +0000 UTC.

Added Labels: Type-Other Hypervisor-KVM
Removed Labels: Type-Defect
Changed State: WontFix
Removed from Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
I have got a Ganeti cluster (v2.6.2) with 4 VMs and only one fails with migration :

# gnt-instance migrate vm.test.lan
Instance vm.test.lan will be migrated. Note that migration might
impact the instance if anything goes wrong (e.g. due to bugs in the
hypervisor). Continue?
y/[n]/?: y
Wed Jun  1 18:54:53 2016 Migrating instance vm.test.lan
Wed Jun  1 18:54:53 2016 * checking disk consistency between source and target
Wed Jun  1 18:54:54 2016 * switching node node2.test.lan to secondary mode
Wed Jun  1 18:54:55 2016 * changing into standalone mode
Wed Jun  1 18:54:55 2016 * changing disks into dual-master mode
Wed Jun  1 18:54:56 2016 * wait until resync is done
Wed Jun  1 18:54:57 2016 * preparing node2.test.lan to accept the instance
Wed Jun  1 18:54:59 2016 * migrating instance to node2.test.lan
Wed Jun  1 18:55:00 2016 * starting memory transfer
Wed Jun  1 18:55:14 2016 Migration failed, aborting
Wed Jun  1 18:55:45 2016 * switching node node2.test.lan to secondary mode
Wed Jun  1 18:55:45 2016 * changing into standalone mode
Wed Jun  1 18:55:45 2016 * changing disks into single-master mode
Wed Jun  1 18:55:47 2016 * wait until resync is done
Failure: command execution error:
Could not migrate instance vm.test.lan: hypervisor returned failure

===> /var/log/ganeti/commands.log :

2016-06-01 18:48:01,178: gnt-instance migrate pid=80506 INFO Command line: gnt-instance migrate vm.test.lan
2016-06-01 18:48:59,054: gnt-instance migrate pid=80506 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cli.py", line 2241, in GenericMain
    result = func(options, args)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/client/gnt_instance.py", line 881, in MigrateInstance
    SubmitOrSend(op, cl=cl, opts=opts)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cli.py", line 2053, in SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn, opts=opts)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cli.py", line 2030, in SubmitOpCode
    reporter=reporter)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cli.py", line 2011, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cli.py", line 1833, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/errors.py", line 506, in MaybeRaise
    raise errcls(*args)
OpExecError: Could not migrate instance vm.test.lan: hypervisor returned failure

===> /var/log/ganeti/master-daemon.log

2016-06-01 18:48:01,179: ganeti-masterd pid=3659/MainThread INFO Accepted connection from pid=80506, uid=0, gid=0
2016-06-01 18:48:01,180: ganeti-masterd pid=3659/ClientReq13 INFO Received instance query request for ['vm.test.lan']
2016-06-01 18:48:02,550: ganeti-masterd pid=3659/ClientReq14 INFO Receiving new job
2016-06-01 18:48:02,716: ganeti-masterd pid=3659/ClientReq14 INFO New job with id 1632, summary: INSTANCE_MIGRATE(vm.test.lan)
2016-06-01 18:48:02,719: ganeti-masterd pid=3659/ClientReq15 INFO Received job poll request for 1632
2016-06-01 18:48:02,723: ganeti-masterd pid=3659/ClientReq16 INFO Received job poll request for 1632
2016-06-01 18:48:02,725: ganeti-masterd pid=3659/ClientReq1 INFO Received job poll request for 1632
2016-06-01 18:48:02,804: ganeti-masterd pid=3659/Jq10/Job1632 INFO Op 1/1: opcode INSTANCE_MIGRATE(vm.test.lan) waiting for locks
2016-06-01 18:48:02,963: ganeti-masterd pid=3659/ClientReq2 INFO Received job poll request for 1632
2016-06-01 18:48:03,696: ganeti-masterd pid=3659/ClientReq3 INFO Received job poll request for 1632
2016-06-01 18:48:03,698: ganeti-masterd pid=3659/ClientReq4 INFO Received job poll request for 1632
2016-06-01 18:48:04,895: ganeti-masterd pid=3659/ClientReq5 INFO Received job poll request for 1632
2016-06-01 18:48:05,615: ganeti-masterd pid=3659/ClientReq6 INFO Received job poll request for 1632
2016-06-01 18:48:05,618: ganeti-masterd pid=3659/ClientReq7 INFO Received job poll request for 1632
2016-06-01 18:48:07,215: ganeti-masterd pid=3659/ClientReq8 INFO Received job poll request for 1632
2016-06-01 18:48:07,218: ganeti-masterd pid=3659/ClientReq9 INFO Received job poll request for 1632
2016-06-01 18:48:09,339: ganeti-masterd pid=3659/ClientReq10 INFO Received job poll request for 1632
2016-06-01 18:48:11,091: ganeti-masterd pid=3659/ClientReq11 INFO Received job poll request for 1632
2016-06-01 18:48:25,587: ganeti-masterd pid=3659/Jq10/Job1632/I_MIGRATE ERROR Instance migration failed, trying to revert disk status: None
2016-06-01 18:48:26,047: ganeti-masterd pid=3659/ClientReq12 INFO Received job poll request for 1632
2016-06-01 18:48:55,286: ganeti-masterd pid=3659/ClientReq13 INFO Received job poll request for 1632
2016-06-01 18:48:56,799: ganeti-masterd pid=3659/ClientReq14 INFO Received job poll request for 1632
2016-06-01 18:48:57,214: ganeti-masterd pid=3659/ClientReq15 INFO Received job poll request for 1632
2016-06-01 18:48:57,217: ganeti-masterd pid=3659/ClientReq16 INFO Received job poll request for 1632
2016-06-01 18:48:58,780: ganeti-masterd pid=3659/Jq10/Job1632 ERROR Op 1/1: Caught exception in INSTANCE_MIGRATE(vm.test.lan)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1031, in _ExecOpCodeUnlocked
    timeout=timeout, priority=op.priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1342, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 457, in ExecOpCode
    priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 396, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 405, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 396, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 405, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 356, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 328, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib.py", line 292, in Exec
    tl.Exec(feedback_fn)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib.py", line 8637, in Exec
    return self._ExecMigration()
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib.py", line 8466, in _ExecMigration
    (instance.name, msg))
OpExecError: Could not migrate instance vm.test.lan: hypervisor returned failure
2016-06-01 18:48:58,862: ganeti-masterd pid=3659/Jq10/Job1632 INFO Finished job 1632, status = error
2016-06-01 18:48:59,050: ganeti-masterd pid=3659/ClientReq1 INFO Received job poll request for 1632
2016-06-01 18:48:59,052: ganeti-masterd pid=3659/ClientReq2 INFO Received job query request for 1632

Did you find a solution ?
```
Originally added on 2016-06-01 17:27:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi Charlie,

The commands.log and master-daemon.log are not the most interesting logs for this problem. Can you post the ganeti-noded.log from both the source and destination nodes? That should show the actual issue.

On the ganeti side, it seems to be a bug that we don't report the actual failure.
```
Originally added on 2016-06-04 11:05:59 +0000 UTC.
