### ISSUE TITLE
Upgrade QA from 2.14 to 2.15 fails with rate limiting error

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1136]
Originally reported of Google Code with ID 1080.

```
Once in a while the upgrade QA fails with:

---- FAILED [TestFilterRateLimit] Tests that the RATE_LIMIT filter does reject new jobs when all: Job should not be rate-limited: 'queued' not in ['running', 'waiting']
>>>> 2015-04-29 11:00:07.677763 time=0:00:13.661309 [TestFilterRateLimit] Tests that the RATE_LIMIT filter does reject new jobs when all
---- BLOCK FAILED [RunFilterTests] Run tests for job filter management: Job should not be rate-limited: 'queued' not in ['running', 'waiting']
^^^^ BLOCK 2015-04-29 11:00:07.677880 time=0:01:31.857363 [RunFilterTests] Run tests for job filter management
Traceback (most recent call last):
  File "./ganeti-qa.py", line 1133, in <module>
    main()
  File "/buildbot/qa-devel-new-2/qa-devel-upgrade-stable-2.15-stable-2.14/build/ganeti/rapi/client.py", line 273, in wrapper
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 1128, in main
    RunQa()
  File "./ganeti-qa.py", line 967, in RunQa
    RunTestBlock(RunFilterTests)
  File "./ganeti-qa.py", line 169, in RunTestBlock
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 446, in RunFilterTests
    RunTestIf("filters", qa_filters.TestFilterRateLimit)
  File "./ganeti-qa.py", line 150, in RunTestIf
    RunTest(fn, *args, **kwargs)
  File "./ganeti-qa.py", line 112, in RunTest
    retval = fn(*args, **kwargs)
  File "/buildbot/qa-devel-new-2/qa-devel-upgrade-stable-2.15-stable-2.14/build/qa/qa_filters.py", line 359, in TestFilterRateLimit
    msg="Job should not be rate-limited")
  File "/buildbot/qa-devel-new-2/qa-devel-upgrade-stable-2.15-stable-2.14/build/qa/qa_utils.py", line 102, in AssertIn
    _RaiseWithInfo(msg, "%r not in %r" % (item, sequence))
  File "/buildbot/qa-devel-new-2/qa-devel-upgrade-stable-2.15-stable-2.14/build/qa/qa_utils.py", line 94, in _RaiseWithInfo
    raise qa_error.Error(output)
qa_error.Error: Job should not be rate-limited: 'queued' not in ['running', 'waiting']
```
Originally added on 2015-04-30 07:58:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This does not seem to be related to the actual upgrading. If this is the case, please disable the test on the QA, because it masks actual upgrading problems and blocks releases.
```
Originally added on 2015-04-30 08:18:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Also, in the last several runs of this QA, this error did not occur.
So I'm closing this bug as I cannot reproduce it, but I'll keep an eye
on it.
```
Originally added on 2015-05-04 08:32:23 +0000 UTC.

Changed State: NotRepeatable
