### ISSUE TITLE
Failed to find SSH public keys

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1203]
Originally reported of Google Code with ID 1150.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".
2.17 (commit d2b1043d897cd80fa404050c25786e41141cdd35)

<b>What distribution are you using?</b>
4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

<b>What steps will reproduce the problem?</b>
1. gnt-cluster init --nic-parameters link=kvm-br0 --enabled-hypervisors=kvm  --enabled-disk-templates="ext" Ganeti-Cluster
Failure: prerequisites not met for this operation:
error type: environment_error, error details:
Failed to find SSH public keys
2. ls -al /etc/ssh
-rw-------   1 root root 263002 Sep 11 11:33 moduli
-rw-------   1 root root   1763 Nov 25 17:01 ssh_config
-rw-------   1 root root   3601 Nov 25 16:59 sshd_config
-rw-------   1 root root    668 Nov 25 17:00 ssh_host_dsa_key
-rw-------   1 root root    610 Nov 25 17:00 ssh_host_dsa_key.pub
-rw-------   1 root root    227 Nov 25 17:00 ssh_host_ecdsa_key
-rw-------   1 root root    182 Nov 25 17:00 ssh_host_ecdsa_key.pub
-rw-------   1 root root    411 Nov 25 17:00 ssh_host_ed25519_key
-rw-------   1 root root    102 Nov 25 17:00 ssh_host_ed25519_key.pub
-rw-------   1 root root   1675 Nov 25 17:00 ssh_host_rsa_key
-rw-------   1 root root    402 Nov 25 17:00 ssh_host_rsa_key.pub
-rw-------   1 root root    338 Oct 24 22:37 ssh_import_id
-rw-------   1 root root      0 Nov 25 19:41 ssh_known_hosts


```
Originally added on 2015-11-27 18:20:17 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi!

Thanks for submitting this. 

However, I tried to reproduce this and failed to do so. Ganeti looks for /etc/ssh/ssh_host_dsa_key.pub or /etc/ssh/ssh_host_rsa_key.pub which according to your 'ls' paste are there. So I am confused why it is failing.

Therefore, a few questions:
- Did this repeatedly happen?
- You did run 'gnt-cluster init ...' as root, right?
- Did you change the --with-ssh-config-dir parameter at configure time? (I see you use a rather fresh version of ganeti, so I assume you configured it from scratch).
- Can you check if there is anything interesting in the logs about this?

Thanks,
Helga
```
Originally added on 2015-12-01 09:07:41 +0000 UTC.

Added Labels: Type-Defect
Changed State: NeedFeedback
Added to Milestone: Release2.17

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hello Helga,
Thanks for answering this.
- yes
- yes, 
- whoops, yes, and that's probably a wrong idea:
	    --with-ssh-config-dir=/root/.ssh \
ls -al /root/.ssh
-rw-------  1 root root  416 Nov 25 18:29 authorized_keys
-rw-------  1 root root 1766 Nov 25 18:29 id_rsa
-rw-------  1 root root 1460 Nov 25 18:31 id_rsa.ppk
-rw-r--r--  1 root root  416 Nov 25 18:29 id_rsa.pub
-rw-r--r--  1 root root  222 Nov 25 19:42 known_hosts
I'll try to reconfigure without modifying that path and let you know about the results.
- also from the logs, we can see that Ganeti expects in /var/lib/ganeti/ a bunch of missing files, including hmac.key, ssconf_hypervisor_list, ssconf_maintain_node_health and server.pem. I have no idea what those first 3 files are for, but regarding the last one, we can't have SSH keys defined in different locations, especially not in a "lib" folder...
If I change the name of the private RSA SSH key to *.pem in /etc/ssh, the error is the same.
If I copy that key into /var/lib/ganeti/server.pem, I have another error:
error type: wrong_state, error details:
/var/lib/ganeti contains non-directory entries like server.pem. Remove left-overs of an old cluster before initialising a new one
and sudo gnt-cluster destroy --yes-do-it
Failure: prerequisites not met for this operation:
error type: wrong_input, error details:
Cluster not initialized or this machine is not part of a cluster

--------------
- commands.log
--------------
2015-12-01 10:22:00,297: gnt-cluster init pid=3394 INFO Using PycURL PycURL/7.19.5.1 libcurl/7.43.0 GnuTLS/3.3.15 zlib/1.2.8 libidn/1.28 librtmp/2.3
2015-12-01 10:22:03,297: gnt-cluster init pid=3394 INFO RunCmd /usr/lib/ganeti/daemon-util stop-all
2015-12-01 10:22:03,331: gnt-cluster init pid=3394 WARNING Specified a file storage directory, although file storage is not enabled.
2015-12-01 10:22:03,331: gnt-cluster init pid=3394 WARNING Specified a sharedfile storage directory, although sharedfile storage is not enabled.
2015-12-01 10:22:03,331: gnt-cluster init pid=3394 WARNING Specified a gluster storage directory, although gluster storage is not enabled.
2015-12-01 10:22:03,332: gnt-cluster init pid=3394 INFO RunCmd ip link show dev kvm-br0
2015-12-01 10:22:03,337: gnt-cluster init pid=3394 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/share/ganeti/2.18/ganeti/cli.py", line 1221, in GenericMain
    result = func(options, args)
  File "/usr/share/ganeti/2.18/ganeti/rpc/node.py", line 141, in wrapper
    return fn(*args, **kwargs)
  File "/usr/share/ganeti/2.18/ganeti/client/gnt_cluster.py", line 337, in InitCluster
    enabled_user_shutdown=enabled_user_shutdown,
  File "/usr/share/ganeti/2.18/ganeti/bootstrap.py", line 710, in InitCluster
    errors.ECODE_ENVIRON)
OpPrereqError: ('Failed to find SSH public keys', 'environment_error')
-----------------
- conf-daemon.log:
-----------------
2015-12-01 10:20:02,371863000000 CET: ganeti-confd pid=3270/ThreadId 3 NOTICE ganeti-confd daemon startup
2015-12-01 10:20:02,376600000000 CET: ganeti-confd pid=3270/ThreadId 3 INFO Starting up in polling mode
2015-12-01 10:20:02,376769000000 CET: ganeti-confd pid=3270/ThreadId 3 NOTICE ganeti-confd daemon shutdown
ganeti-confd: /var/lib/ganeti/hmac.key: openBinaryFile: does not exist (No such file or directory)
----------------
- kvm-daemon.log
----------------
2015-12-01 10:20:02,533272000000 CET: ganeti-kvmd pid=3290/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 10:20:02,534750000000 CET: ganeti-kvmd pid=3290/ThreadId 3 INFO /var/lib/ganeti/ssconf_hypervisor_list: openFile: does not exist (No such file or directory)
2015-12-01 10:20:02,535640000000 CET: ganeti-kvmd pid=3290/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
2015-12-01 10:25:02,178198000000 CET: ganeti-kvmd pid=3754/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 10:25:02,178885000000 CET: ganeti-kvmd pid=3754/ThreadId 3 INFO /var/lib/ganeti/ssconf_hypervisor_list: openFile: does not exist (No such file or directory)
2015-12-01 10:25:02,179069000000 CET: ganeti-kvmd pid=3754/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
-------------
- watcher.log
-------------
2015-12-01 10:20:01,962: ganeti-watcher pid=3230 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-noded
2015-12-01 10:20:02,215: ganeti-watcher pid=3230 ERROR Can't start daemon 'ganeti-noded', failure exited with exit code 1, output: SSL key file '/var/lib/ganeti/server.pem' was not found

2015-12-01 10:20:02,215: ganeti-watcher pid=3230 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-confd
2015-12-01 10:20:02,373: ganeti-watcher pid=3230 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-kvmd
2015-12-01 10:20:02,535: ganeti-watcher pid=3230 ERROR Configuration error, not activating node maintenance: Can't read ssconf file /var/lib/ganeti/ssconf_maintain_node_health: [Errno 2] No such file or directory: '/var/lib/ganeti/ssconf_maintain_node_health'
2015-12-01 10:25:01,652: ganeti-watcher pid=3694 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-noded
2015-12-01 10:25:01,889: ganeti-watcher pid=3694 ERROR Can't start daemon 'ganeti-noded', failure exited with exit code 1, output: SSL key file '/var/lib/ganeti/server.pem' was not found

2015-12-01 10:25:01,889: ganeti-watcher pid=3694 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-confd
2015-12-01 10:25:02,021: ganeti-watcher pid=3694 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-kvmd
2015-12-01 10:25:02,180: ganeti-watcher pid=3694 ERROR Configuration error, not activating node maintenance: Can't read ssconf file /var/lib/ganeti/ssconf_maintain_node_health: [Errno 2] No such file or directory: '/var/lib/ganeti/ssconf_maintain_node_health'

```
Originally added on 2015-12-01 09:55:54 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi!

please configure Ganeti then with the standard ssh dir (either by not setting it as it is the default or explicitely with --with-ssh-config-dir=/etc/ssh).

About the other files:  usually Ganeti will generate those. I assume it did not do this, because it failed before with that SSH error.

Check whether it works better with the correct ssh dir and let me know of there are still problems then.
```
Originally added on 2015-12-01 10:00:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The command "gnt-cluster init --nic-parameters link=kvm-br0 --enabled-hypervisors=kvm  --enabled-disk-templates="ext" Ganeti-Cluster" now can be executed without any error.

However, the logs show:
--------------
- commands.log
--------------
2015-12-01 11:31:41,961: gnt-cluster init pid=4957 WARNING Specified a file storage directory, although file storage is not enabled.
2015-12-01 11:31:41,962: gnt-cluster init pid=4957 WARNING Specified a sharedfile storage directory, although sharedfile storage is not enabled.
2015-12-01 11:31:41,962: gnt-cluster init pid=4957 WARNING Specified a gluster storage directory, although gluster storage is not enabled.
How do I enable a file storage directory (this node does not use LVM)?
Or maybe I should use glusterFS instead.

2015-12-01 11:31:41,982: gnt-cluster init pid=4957 INFO RunCmd ssh-keygen -t dsa -f /root/.ssh/id_dsa -q -N ''
That seems to imply that DSA is used: how do we use RSA or ECDSA instead of an obsolete DSA?
----------------
- kvm-daemon.log
----------------
2015-12-01 11:30:02,685591000000 CET: ganeti-kvmd pid=4956/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 11:30:02,686439000000 CET: ganeti-kvmd pid=4956/ThreadId 3 INFO /var/lib/ganeti/ssconf_hypervisor_list: openFile: does not exist (No such file or directory)
2015-12-01 11:30:02,686777000000 CET: ganeti-kvmd pid=4956/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
2015-12-01 11:31:44,746512000000 CET: ganeti-kvmd pid=5104/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 11:31:44,747171000000 CET: ganeti-kvmd pid=5104/ThreadId 3 INFO User shutdown not enabled, exiting
2015-12-01 11:31:44,747274000000 CET: ganeti-kvmd pid=5104/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
2015-12-01 11:35:01,972547000000 CET: ganeti-kvmd pid=5181/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 11:35:01,972956000000 CET: ganeti-kvmd pid=5181/ThreadId 3 INFO User shutdown not enabled, exiting
2015-12-01 11:35:01,973035000000 CET: ganeti-kvmd pid=5181/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
2015-12-01 11:40:02,012749000000 CET: ganeti-kvmd pid=5264/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 11:40:02,013301000000 CET: ganeti-kvmd pid=5264/ThreadId 3 INFO User shutdown not enabled, exiting
2015-12-01 11:40:02,013408000000 CET: ganeti-kvmd pid=5264/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
2015-12-01 11:45:02,039320000000 CET: ganeti-kvmd pid=5355/ThreadId 3 NOTICE ganeti-kvmd daemon startup
2015-12-01 11:45:02,039908000000 CET: ganeti-kvmd pid=5355/ThreadId 3 INFO User shutdown not enabled, exiting
2015-12-01 11:45:02,040004000000 CET: ganeti-kvmd pid=5355/ThreadId 3 NOTICE ganeti-kvmd daemon shutdown
...
-----------------
- rapi-daemon.log
-----------------
2015-12-01 11:31:44,449: ganeti-rapi pid=5069 INFO Reading users file at /var/lib/ganeti/rapi/users
2015-12-01 11:31:44,449: ganeti-rapi pid=5069 WARNING No users file at /var/lib/ganeti/rapi/users
-------------
- watcher.log
-------------
2015-12-01 11:35:01,989: ganeti-watcher pid=5150 INFO RunCmd /usr/lib/ganeti/daemon-util check-and-start ganeti-maintd
2015-12-01 11:35:02,132: ganeti-watcher pid=5150 ERROR Can't start daemon 'ganeti-maintd', failure exited with exit code 2, output: start-stop-daemon: unable to start /usr/sbin/ganeti-maintd (No such file or directory)

As a side node, I had to uninstall my home-brewed ganeti-instance-debootstrap to avoid the following error:
Error processing archive /home/ubuntu/Jean-Christophe_Manciot/ganeti/Ubuntu/15.10/ganeti_2.17-11_amd64.deb (--install):
 trying to overwrite '/srv/ganeti/os/debootstrap/export', which is also in package ganeti-instance-debootstrap 0.15-11

Does that mean that instance debootstrap code is now embedded into Ganeti?



```
Originally added on 2015-12-01 10:59:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi!

You can ignore the warnings about file/sharedfile/glusterfs. Since you only enabled 'ext', just ignore them. It will not impair the functionality of your cluster. (I will file a bug to fix that though.)

For the DSA/RSA thing we recently added functionality to use RSA, but I think that hasn't hit 2.17 yet, but will be in the next release.

I am not sure about the kvm-daemon.log output, do you mind posting that on the mailing list? (this bug is not the right place for it).

The rapi warning you can ignore if you don't intend to use rapi.

The watcher question please also ask on the mailing list. (Separate thread preferrably.)

Technically ganeti-instance-debootstrap does not come with Ganeti as far as I know, but the packager might have included it. 

FYI, I will close this bug now as the SSH thing was working as intended. Please refer to the mailing list / IRC for further questions about setting up a cluster.
```
Originally added on 2015-12-01 11:54:23 +0000 UTC.

Changed State: Invalid
