### ISSUE TITLE
gnt-instance move socat error - certificate commonName does not match hostname

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1232]
Originally reported of Google Code with ID 1179.

```
*What software version are you running?*

root@nuc1:~# gnt-cluster --version
gnt-cluster (ganeti 2.15.2-3) 2.15.2

root@nuc1:~# gnt-cluster version
Software version: 2.15.2
Internode protocol: 2150000
Configuration format: 2150000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version 2.15.2-3

root@nuc1:~# hspace --version
hspace (ganeti) version 2.15.2-3
compiled with ghc 7.10
running on linux x86_64

*What distribution are you using?*

Two nodes both ubuntu 16.04

    10.10.0.238 = nuc1.ws.nsrc.org
    10.10.0.239 = nuc2.ws.nsrc.org

*What steps will reproduce the problem?*

root@nuc1:~# gnt-instance list -o name,pnode,snodes pfsense1
Instance Primary_node     Secondary_Nodes
pfsense1 nuc2.ws.nsrc.org

root@nuc1:~# gnt-instance move -n nuc1.ws.nsrc.org -d pfsense1
2016-05-08 16:22:41,729: gnt-instance move pid=6299 cli:1218 DEBUG Command line: gnt-instance move -n nuc1.ws.nsrc.org -d pfsense1
Instance pfsense1 will be moved. This requires a shutdown of the
instance. Continue?
y/[n]/?: y
Sun May  8 16:22:47 2016  - INFO: Not checking memory on the secondary node as instance will not be started
Sun May  8 16:22:48 2016  - INFO: Shutting down instance pfsense1 on source node nuc2.ws.nsrc.org
Sun May  8 16:22:49 2016 Exporting disk/0 from nuc2.ws.nsrc.org to nuc1.ws.nsrc.org
Sun May  8 16:22:53 2016 disk/0 is now listening, starting export
Sun May  8 16:22:56 2016  - WARNING: import 'import-disk0-2016-05-08_16_22_49-MXuNPT' on nuc1.ws.nsrc.org failed: Exited with status 1
Sun May  8 16:22:56 2016 disk/0 failed to receive data: Exited with status 1 (recent output: 0+0 records in\n0+0 records out\n0 bytes copied, 4.81635 s, 0.0 kB/s)
Sun May  8 16:22:56 2016  - WARNING: Aborting export 'export-disk0-2016-05-08_16_22_54-MM8F_x' on 0b180aa9-2c45-4250-a54a-e56c41b5cc68
Sun May  8 16:22:56 2016  - WARNING: export 'export-disk0-2016-05-08_16_22_54-MM8F_x' on nuc2.ws.nsrc.org failed: Exited with status 1
Sun May  8 16:22:56 2016 disk/0 failed to send data: Exited with status 1 (recent output: socat: E certificate is valid but its commonName does not match hostname\ndd: dd: error writing 'standard output': Broken pipe\ndd: error writing 'standard output': Broken pipe\n2+0 records in\n1+0 records out\n1114112 bytes (1.1 MB, 1.1 MiB) copied, 0.0976589 s, 11.4 MB/s)
Sun May  8 16:22:57 2016  - WARNING: Some disks failed to copy, aborting
2016-05-08 16:22:57,864: gnt-instance move pid=6299 cli:1225 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 1221, in GenericMain
    result = func(options, args)
  File "/usr/share/ganeti/2.15/ganeti/client/gnt_instance.py", line 851, in MoveInstance
    SubmitOrSend(op, opts, cl=cl)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 1011, in SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn, opts=opts)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 976, in SubmitOpCode
    reporter=reporter)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 955, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 777, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/share/ganeti/2.15/ganeti/errors.py", line 531, in MaybeRaise
    raise errcls(*args)
OpExecError: Errors during disk copy: Failed to transfer instance data
Failure: command execution error:
Errors during disk copy: Failed to transfer instance data
root@nuc1:~#

"gnt-cluster renew-crypto --new-node-certificates" is successful, but does not affect the results. Restarting ganeti on both nodes makes no difference.

Replacing /usr/bin/socat with:

#!/bin/sh
echo "$0" "$@" >>/tmp/socat.out
exec socat.real "$@"

allowed me to capture the command arguments.

=== On nuc1: receiver of image and cluster master ===
/usr/bin/socat -ls -d -d -b1048576 -u OPENSSL-LISTEN:0,reuseaddr,forever,intervall=0.01,keepalive,keepidle=60,keepintvl=10,keepcnt=5,verify=1,method=TLS1,cipher=HIGH:-DES:-3DES:-EXPORT:-DH,compress=none,key=/var/lib/ganeti/server.pem,cert=/var/lib/ganeti/server.pem,cafile=/var/run/ganeti/import-export/import-disk0-2016-05-08_16_27_40-mDO5uf/ca,pf=ipv4 stdout

=== On nuc2: sender of image ===
/usr/bin/socat -ls -d -d -b1048576 -u stdin OPENSSL:10.10.0.238:46423,connect-timeout=20,retry=10,intervall=1,keepalive,keepidle=60,keepintvl=10,keepcnt=5,verify=1,method=TLS1,cipher=HIGH:-DES:-3DES:-EXPORT:-DH,compress=none,key=/var/lib/ganeti/server.pem,cert=/var/lib/ganeti/server.pem,cafile=/var/run/ganeti/import-export/export-disk0-2016-05-08_16_27_45-u0Sxcf/ca,pf=ipv4

OK: so that it seems that the sender is trying to connect by IP address (10.10.0.238 = nuc1), but socat fails because it the hostname in the certificate is "nuc1.ws.nsrc.org"

It says in the socat manpage:

              NOTE: Up to version 1.7.2.4 the server certificate was only checked for  validity
              against  the system certificate store or cafile or capath, but not for match with
              the server’s name or its IP address.  Since version 1.7.3.0 socat checks the peer
              certificate  for match with the <host> parameter or the value of the openssl-com‐
              monname option.  Socat tries to match it against the certificates subject common‐
              Name, and the certifications extension subjectAltName DNS names. Wildcards in the
              certificate are supported.

I think therefore that the connection should be made by name but not IP address, *or* the commonname option should be added.

It's possible that my cluster is in an invalid state as it has been through several upgrades, but I don't think so; it seems to work OK apart from instance move; gnt-cluster verify is fine. Here is the relevant config excerpt (reformatted via 'python -m json.tool')

=== /var/lib/ganeti/config.data ===

...
    "nodes": {
        "0b180aa9-2c45-4250-a54a-e56c41b5cc68": {
            "ctime": 1462607653.915405,
            "drained": false,
            "group": "4f283bc2-68c9-4392-9155-65a569e06a97",
            "master_candidate": true,
            "master_capable": true,
            "mtime": 1462607653.915405,
            "name": "nuc2.ws.nsrc.org",
            "ndparams": {},
            "offline": false,
            "powered": true,
            "primary_ip": "10.10.0.239",
            "secondary_ip": "10.10.0.239",
            "serial_no": 1,
            "tags": [],
            "uuid": "0b180aa9-2c45-4250-a54a-e56c41b5cc68",
            "vm_capable": true
        },
        "52cee655-b738-45ff-b920-b797840a6113": {
            "ctime": 1462717482.202958,
            "drained": false,
            "group": "4f283bc2-68c9-4392-9155-65a569e06a97",
            "master_candidate": true,
            "master_capable": true,
            "mtime": 1462717482.202958,
            "name": "nuc1.ws.nsrc.org",
            "ndparams": {},
            "offline": false,
            "powered": true,
            "primary_ip": "10.10.0.238",
            "secondary_ip": "10.10.0.238",
            "serial_no": 1,
            "tags": [],
            "uuid": "52cee655-b738-45ff-b920-b797840a6113",
            "vm_capable": true
        }
...

== ssconf_node_primary_ips ==

nuc1.ws.nsrc.org 10.10.0.238
nuc2.ws.nsrc.org 10.10.0.239

== ssconf_master_candidates_ips ==

10.10.0.239
10.10.0.238
```
Originally added on 2016-05-08 15:42:39 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Some debug code:

--- impexpd/__init__.py.orig	2016-05-08 12:15:29.000000000 +0100
+++ impexpd/__init__.py	2016-05-08 16:43:55.882379251 +0100
@@ -132,6 +132,9 @@
     self._socat_stderr_fd = socat_stderr_fd
     self._dd_stderr_fd = dd_stderr_fd
     self._dd_pid_fd = dd_pid_fd
+    with open("/tmp/opts","a+") as f:
+        f.write(repr(opts) + "\n")
+

     assert (self._opts.magic is None or
             constants.IE_MAGIC_RE.match(self._opts.magic))


Results at the sending side:

<Values at 0x7f29825d8b48: {'magic': 'aabe259ed8aecf3dac27abb79534f7c2602a6f2c', 'verbose': False, 'bind': None, 'ca': '/var/run/ganeti/import-export/export-disk0-2016-05-08_16_47_08-Bz3TAU/ca', 'compress': 'none', 'cert': '/var/lib/ganeti/server.pem', 'cmd_suffix': None, 'connect_timeout': 20, 'host': '10.10.0.238', 'exp_size': 2048, 'connect_retries': 10, 'key': '/var/lib/ganeti/server.pem', 'ipv6': None, 'debug': 0, 'cmd_prefix': 'dd if=/dev/ganeti/5a8b4e5d-6f4e-4844-bb75-5a8841112859.disk0 bs=1048576 count=2048 iflag=direct |', 'port': 33318, 'ipv4': True}>

It seems that 'host' is the IP address, and the true hostname is not included.

Here is a temporary (insecure) workaround:

--- __init__.py.orig	2016-05-08 12:15:29.899058666 +0100
+++ __init__.py	2016-05-08 16:51:32.000000000 +0100
@@ -88,7 +88,7 @@

 # Common options for socat
 SOCAT_TCP_OPTS = ["keepalive", "keepidle=60", "keepintvl=10", "keepcnt=5"]
-SOCAT_OPENSSL_OPTS = ["verify=1", "method=TLS1",
+SOCAT_OPENSSL_OPTS = ["verify=0", "method=TLS1",
                       "cipher=%s" % constants.OPENSSL_CIPHERS]

 if constants.SOCAT_USE_COMPRESS:

With this change, the instance move works. 

But I think the real solution is either:

1. pass the hostname rather than IP address in the "host" option; or
2. pass the commonname as an additional option, and use commonname=XXX socat openssl option

```
Originally added on 2016-05-08 15:55:51 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Oops, I think this is a duplicate of #1173
```
Originally added on 2016-05-08 16:15:28 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
It is, but a very helpful duplicate. Thanks for all the analysis.
```
Originally added on 2016-05-09 12:36:24 +0000 UTC.

Changed State: Duplicate
Marked as duplicate of #1226

**Comment by Ganeti-Issues-Migrator** [comment]
```
I am facing same type of problem at the time of taking backup.
What steps should I take to solve this. 

OS is ubuntu 16.04.1
ganeti 2.15.2-3
socat 1.7.3.1

Message details is below.

root@node01:~# gnt-backup export -n node01.beximtex.com inst03.beximtex.com
Sat Sep 17 21:56:40 2016 Shutting down instance inst03.beximtex.com
Sat Sep 17 21:56:40 2016 Activating disks for inst03.beximtex.com
Sat Sep 17 21:56:41 2016 Exporting disk/0 from node03.beximtex.com to node01.beximtex.com
Sat Sep 17 21:56:44 2016  - WARNING: import 'import-disk0-2016-09-17_21_56_41-lmSEVS' on node01.beximtex.com failed: Exited with status 1
Sat Sep 17 21:56:44 2016 disk/0 failed to receive data: Exited with status 1 (recent output: socat: E openssl-method="TLSv1": method unknown or not provided by library)
Sat Sep 17 21:56:44 2016  - WARNING: Some disk exports have failed; there may be leftover data for instance inst03.beximtex.com on node node01.beximtex.com
Sat Sep 17 21:56:44 2016 Deactivating disks for inst03.beximtex.com
Failure: command execution error:
Export failed, errors in export finalization, disk export: disk(s) 0

```
Originally added on 2016-09-17 16:23:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I am facing same type of problem at the time of taking backup.
What steps should I take to solve this. 

OS is ubuntu 16.04.1
ganeti 2.15.2-3
socat 1.7.3.1

Message details is below.

root@node01:~# gnt-backup export -n node01.beximtex.com inst03.beximtex.com
Sat Sep 17 21:56:40 2016 Shutting down instance inst03.beximtex.com
Sat Sep 17 21:56:40 2016 Activating disks for inst03.beximtex.com
Sat Sep 17 21:56:41 2016 Exporting disk/0 from node03.beximtex.com to node01.beximtex.com
Sat Sep 17 21:56:44 2016  - WARNING: import 'import-disk0-2016-09-17_21_56_41-lmSEVS' on node01.beximtex.com failed: Exited with status 1
Sat Sep 17 21:56:44 2016 disk/0 failed to receive data: Exited with status 1 (recent output: socat: E openssl-method="TLSv1": method unknown or not provided by library)
Sat Sep 17 21:56:44 2016  - WARNING: Some disk exports have failed; there may be leftover data for instance inst03.beximtex.com on node node01.beximtex.com
Sat Sep 17 21:56:44 2016 Deactivating disks for inst03.beximtex.com
Failure: command execution error:
Export failed, errors in export finalization, disk export: disk(s) 0

Regards
Md. Salah Uddin
```
Originally added on 2016-09-17 16:25:17 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
You could fix this in your local install by applying the patch in

http://git.ganeti.org/?p=ganeti.git;a=commitdiff;h=d5d747d5
```
Originally added on 2016-09-29 16:05:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

socat problem is solved after fixing the line.


Now I am facing problem with windows 2008 32 bit guest.
it starts but after showing "windows is loading fies....." it has no
progress.

Startup command is:
 gnt-instance start -H
cdrom_disk_type=ide,boot_order=cdrom,cdrom_image_path=/iso/en_windows_server_2008_enter_with_sp2_x86_dvd_342333.iso,cdrom2_image_path=/iso/virtio-win.iso
inst10.beximtex.com

host os is ubuntu 16.04.1
ganeti version is 2.15.2
kvm is : 1:2.5+dfsg-5ubuntu10.5
os defination is : image+cd

Do you have any suggestion.
```
Originally added on 2016-10-11 18:24:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I'm afraid I have no experience with Windows on Ganeti.

Could you follow up this discussion to the ganeti mailing list at http://groups.google.com/forum/#!forum/ganeti please? This is a bug tracker, not a support list.

Thanks!
```
Originally added on 2016-10-12 14:40:45 +0000 UTC.
