### ISSUE TITLE
gnt-backup export failure

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1236]
Originally reported of Google Code with ID 1183.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".
# gnt-cluster --version
gnt-cluster (ganeti v2.14.2-177-g003cd9a) 2.15.2

# gnt-cluster --version
gnt-cluster (ganeti v2.14.2-177-g003cd9a) 2.15.2
[root@ocean ~]# gnt-cluster version
Software version: 2.15.2
Internode protocol: 2150000
Configuration format: 2150000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version v2.14.2-177-g003cd9a

# hspace --version
hspace (ganeti) version v2.14.2-177-g003cd9a
compiled with ghc 7.6
running on linux x86_64

<b>What distribution are you using?</b>
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

<b>What steps will reproduce the problem?</b>
1. gnt-backup export -n node1 instance1
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Backup complete message. Instead:# gnt-backup export -d -n node1 instance1
2016-06-24 17:05:01,989: gnt-backup export pid=179732 cli:1218 DEBUG Command line: gnt-backup export -d -n node1 instance1
Fri Jun 24 17:05:02 2016 Shutting down instance instance1.intranet.domain.com
Fri Jun 24 17:05:07 2016 Creating a snapshot of disk/0 on node node1.intranet.domain.com
Fri Jun 24 17:05:07 2016 Starting instance instance1.intranet.domain.com
Fri Jun 24 17:05:08 2016 Exporting snapshot/0 from node1.intranet.domain.com to node1.intranet.domain.com
Fri Jun 24 17:05:11 2016 snapshot/0 is now listening, starting export
Fri Jun 24 17:05:13 2016 snapshot/0 finished receiving data
Fri Jun 24 17:05:13 2016  - WARNING: export 'export-disk0-2016-06-24_17_05_12-YArFHA' on node1.intranet.domain.com failed: Exited with status 1
Fri Jun 24 17:05:13 2016 snapshot/0 failed to send data: Exited with status 1 (recent output: )
Fri Jun 24 17:05:13 2016 Removing snapshot of disk/0 on node node1.intranet.domain.com
Fri Jun 24 17:05:14 2016  - WARNING: Some disk exports have failed; there may be leftover data for instance instance1.intranet.domain.com on node node1.intranet.domain.com
2016-06-24 17:05:14,120: gnt-backup export pid=179732 cli:1225 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 1221, in GenericMain
    result = func(options, args)
  File "/usr/share/ganeti/2.15/ganeti/client/gnt_backup.py", line 116, in ExportInstance
    SubmitOrSend(op, opts)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 1011, in SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn, opts=opts)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 976, in SubmitOpCode
    reporter=reporter)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 955, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/share/ganeti/2.15/ganeti/cli.py", line 777, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/share/ganeti/2.15/ganeti/errors.py", line 531, in MaybeRaise
    raise errcls(*args)
OpExecError: Export failed, errors in export finalization, disk export: disk(s) 0
Failure: command execution error:
Export failed, errors in export finalization, disk export: disk(s) 0


<b>Please provide any additional information below.</b>
I would be happy to test anything else to determine what the cause may be.
```
Originally added on 2016-06-24 21:08:13 +0000 UTC.

**Comment by iustin** [comment]
Can you please retest with 2.16? In the meantime closing this for old bugs cleanup, reopen if it still happens.
