### ISSUE TITLE
Cluster-Init fails with Master daemon not answering

### ISSUE THREAD

**Issue by mweinelt** [ganeti/ganeti#1289]
## Setup

Debian Stretch
Ganeti 2.16.0-rc2 installed from Unstable (sid)

```
root@grumpy:~# dpkg -l | grep ganeti
ii  ganeti                               2.16.0~rc2-1                   all          cluster virtualization manager
ii  ganeti-2.16                          2.16.0~rc2-1                   all          cluster virtualization manager - Python components
ii  ganeti-haskell-2.16                  2.16.0~rc2-1                   amd64        cluster virtualization manager - Haskell components
ii  ganeti-htools-2.16                   2.16.0~rc2-1                   amd64        cluster virtualization manager - tools for Ganeti 2.16
ii  ganeti-instance-debootstrap          0.16-3                         all          debootstrap-based instance OS definition for ganeti
```

## Problem

Already reported against the Debian Package and Ganeti 2.15.2 at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875710

The init of a fresh cluster fails, when the master daemon does not answer:

```
root@grumpy:~# gnt-cluster init -d --master-netdev=br-vlan30 --vg-name=system --enabled-hypervisors=kvm --no-etc-hosts --hypervisor-parameters kvm:initrd_path=,kernel_path=,vhost_net=true,cpu_type=host --enabled-disk-templates=plain,drbd snowwhite
2018-02-26 04:03:02,826: gnt-cluster init pid=20500 cli:1250 DEBUG Command line: gnt-cluster init -d --master-netdev=br-vlan30 --vg-name=system --enabled-hypervisors=kvm --no-etc-hosts --hypervisor-parameters kvm:initrd_path=,kernel_path=,vhost_net=true,cpu_type=host --enabled-disk-templates=plain,drbd snowwhite
2018-02-26 04:03:02,826: gnt-cluster init pid=20500 node:94 INFO Using PycURL PycURL/7.43.0 libcurl/7.52.1 GnuTLS/3.5.8 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
2018-02-26 04:03:02,828: gnt-cluster init pid=20500 netutils:326 DEBUG Attempting to reach TCP port 1811 on target 192.168.30.14 with a timeout of 5 seconds
2018-02-26 04:03:05,880: gnt-cluster init pid=20500 process:221 INFO RunCmd vgs --noheadings --units m --nosuffix -o name,size
2018-02-26 04:03:05,903: gnt-cluster init pid=20500 bootstrap:607 DEBUG Stopping daemons (if any are running)
2018-02-26 04:03:05,904: gnt-cluster init pid=20500 process:221 INFO RunCmd /usr/lib/ganeti/daemon-util stop-all
2018-02-26 04:03:06,021: gnt-cluster init pid=20500 __init__:835 WARNING Specified a file storage directory, although file storage is not enabled.
2018-02-26 04:03:06,021: gnt-cluster init pid=20500 __init__:835 WARNING Specified a sharedfile storage directory, although sharedfile storage is not enabled.
2018-02-26 04:03:06,022: gnt-cluster init pid=20500 __init__:835 WARNING Specified a gluster storage directory, although gluster storage is not enabled.
2018-02-26 04:03:06,023: gnt-cluster init pid=20500 process:221 INFO RunCmd ip link show dev br-vlan30
2018-02-26 04:03:06,036: gnt-cluster init pid=20500 io:549 DEBUG Backing up /root/.ssh/id_rsa at /root/.ssh/id_rsa.backup-2018-02-26_04_03_06.zFG01R
2018-02-26 04:03:06,037: gnt-cluster init pid=20500 io:549 DEBUG Backing up /root/.ssh/id_rsa.pub at /root/.ssh/id_rsa.pub.backup-2018-02-26_04_03_06.sotcc2
2018-02-26 04:03:06,038: gnt-cluster init pid=20500 process:221 INFO RunCmd ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ''
2018-02-26 04:03:06,254: gnt-cluster init pid=20500 __init__:2683 DEBUG Writing configuration and unlocking it
2018-02-26 04:03:06,256: gnt-cluster init pid=20500 __init__:2685 DEBUG Configuration write, unlock finished
2018-02-26 04:03:06,477: gnt-cluster init pid=20500 security:86 DEBUG Generating new cluster certificate at /var/lib/ganeti/server.pem
2018-02-26 04:03:06,729: gnt-cluster init pid=20500 bootstrap:144 DEBUG Writing new confd HMAC key to /var/lib/ganeti/hmac.key
2018-02-26 04:03:06,730: gnt-cluster init pid=20500 security:86 DEBUG Generating new RAPI certificate at /var/lib/ganeti/rapi.pem
2018-02-26 04:03:07,028: gnt-cluster init pid=20500 bootstrap:173 DEBUG Generating new self-signed SPICE certificate at /var/lib/ganeti/spice.pem
2018-02-26 04:03:07,128: gnt-cluster init pid=20500 bootstrap:179 DEBUG Writing the public certificate to /var/lib/ganeti/spice.pem
2018-02-26 04:03:07,129: gnt-cluster init pid=20500 bootstrap:188 DEBUG Generating new cluster domain secret at /var/lib/ganeti/cluster-domain-secret
2018-02-26 04:03:07,137: gnt-cluster init pid=20500 __init__:2683 DEBUG Writing configuration and unlocking it
2018-02-26 04:03:07,138: gnt-cluster init pid=20500 __init__:2685 DEBUG Configuration write, unlock finished
2018-02-26 04:03:07,145: gnt-cluster init pid=20500 __init__:2683 DEBUG Writing configuration and unlocking it
2018-02-26 04:03:07,147: gnt-cluster init pid=20500 __init__:2685 DEBUG Configuration write, unlock finished
2018-02-26 04:03:07,381: gnt-cluster init pid=20500 process:221 INFO RunCmd /usr/lib/ganeti/daemon-util start ganeti-noded
2018-02-26 04:03:11,442: gnt-cluster init pid=20500 client:144 DEBUG Starting request <ganeti.http.client.HttpClientRequest 192.168.30.1:1811 POST /version at 0x7f89284d2c90>
2018-02-26 04:03:11,527: gnt-cluster init pid=20500 client:238 DEBUG Request from 192.168.30.1:36464 <ganeti.http.client.HttpClientRequest 192.168.30.1:1811 POST /version at 0x7f89284d2c90> finished, errmsg=None
2018-02-26 04:03:11,528: gnt-cluster init pid=20500 bootstrap:824 DEBUG Starting daemons
2018-02-26 04:03:11,528: gnt-cluster init pid=20500 process:221 INFO RunCmd /usr/lib/ganeti/daemon-util start-all
2018-02-26 04:03:48,361: gnt-cluster init pid=20500 cli:1257 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/share/ganeti/2.16/ganeti/cli.py", line 1253, in GenericMain
    result = func(options, args)
  File "/usr/share/ganeti/2.16/ganeti/rpc/node.py", line 144, in wrapper
    return fn(*args, **kwargs)
  File "/usr/share/ganeti/2.16/ganeti/client/gnt_cluster.py", line 349, in InitCluster
    ssh_key_bits=ssh_key_bits,
  File "/usr/share/ganeti/2.16/ganeti/bootstrap.py", line 831, in InitCluster
    _WaitForMasterDaemon()
  File "/usr/share/ganeti/2.16/ganeti/bootstrap.py", line 273, in _WaitForMasterDaemon
    " %s seconds" % _DAEMON_READY_TIMEOUT)
OpExecError: Master daemon didn't answer queries within 10.0 seconds
Failure: command execution error:
Master daemon didn't answer queries within 10.0 seconds
```

### Running Ganeti Processes
```
root@grumpy:~# ps aux | grep ganeti
root     20549  0.0  0.2 168964 70760 ?        SL   04:03   0:00 /usr/bin/python /usr/sbin/ganeti-noded
gnt-con+ 20576  0.0  0.0 1073783092 13600 ?    S    04:03   0:00 /usr/sbin/ganeti-confd
gnt-rapi 20601  0.0  0.1  98032 52692 ?        S    04:03   0:00 /usr/bin/python /usr/sbin/ganeti-rapi -b 127.0.0.1 --require-authentication
root     20639  0.0  0.0 1073786060 15304 ?    S    04:03   0:00 /usr/sbin/ganeti-mond
root     20672  0.0  0.0   4292   748 ?        Ss   04:05   0:00 /bin/sh -c [ -x /usr/sbin/ganeti-watcher ] && /usr/sbin/ganeti-watcher
root     20673  9.1  0.1 147280 38080 ?        S    04:05   0:00 /usr/bin/python /usr/sbin/ganeti-watcher
```
### Sockets

These sockets come up during the `gnt-cluster init` call:

```
u_str  UNCONN     0      0         * 23541                 * 0                   users:(("gnt-cluster",pid=13328,fd=4))
udp    UNCONN     0      0         *:1814                  *:*                   users:(("ganeti-confd",pid=13440,fd=6))
tcp    LISTEN     0      128       *:1811                  *:*                   users:(("ganeti-noded",pid=13409,fd=9))
tcp    LISTEN     0      128       *:1815                  *:*                   users:(("ganeti-mond",pid=13523,fd=6))
tcp    LISTEN     0      128    127.0.0.1:5080                  *:*                   users:(("ganeti-rapi",pid=13481,fd=9))
```

### Firewall
```
root@grumpy:~# iptables-save
# Generated by iptables-save v1.6.0 on Mon Feb 26 04:06:48 2018
*filter
:INPUT ACCEPT [79:19876]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [75:19532]
COMMIT
# Completed on Mon Feb 26 04:06:48 2018
```

### Network
```
6: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether b8:ca:3a:65:37:68 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::baca:3aff:fe65:3768/64 scope link 
       valid_lft forever preferred_lft forever
7: br-vlan30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether b8:ca:3a:65:37:68 brd ff:ff:ff:ff:ff:ff
    inet 192.168.30.1/24 brd 192.168.30.255 scope global br-vlan30
       valid_lft forever preferred_lft forever
    inet6 fe80::88ba:fcff:fee5:155b/64 scope link 
       valid_lft forever preferred_lft forever
8: bond0.30@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br-vlan30 state UP group default qlen 1000
    link/ether b8:ca:3a:65:37:68 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::baca:3aff:fe65:3768/64 scope link 
       valid_lft forever preferred_lft forever

```

### Hosts
```
root@grumpy:~# cat /etc/hosts
127.0.0.1	localhost

192.168.30.1	grumpy grumpy.darmstadt.freifunk.net
192.168.30.2	sleepy sleepy.darmstadt.freifunk.net
192.168.30.3    sneezy sneezy.darmstadt.freifunk.net
192.168.30.4    happy happy.darmstadt.freifunk.net

192.168.30.14	snowwhite snowwhite.darmstadt.freifunk.net
```

**Comment by mweinelt** [comment]
Init worked after switching fqdn and alias in `/etc/hosts`. Thank you very much for your help @apoikos!

```
root@grumpy:/var/lib/ganeti# cat /etc/hosts
127.0.0.1	localhost

192.168.30.1	grumpy.darmstadt.freifunk.net grumpy
192.168.30.2	sleepy.darmstadt.freifunk.net sleepy
192.168.30.3    sneezy.darmstadt.freifunk.net sneezy
192.168.30.4    happy.darmstadt.freifunk.net happy

192.168.30.14	snowwhite.darmstadt.freifunk.net snowwhite 
```

**Comment by mosharaflink** [comment]
Hi
I am also facing the same issue with version 2.15 and my hostname is configured as fqdn.
