### ISSUE TITLE
gnt-node remove error: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#135]
Originally reported of Google Code with ID 79.

```
Hi,

I'm running  ganeti2 2.0.3-1 on Debian GNU/Linux 2.6.30-1-amd64,

And I have the following error when trying to remove a node from the cluster:
z2-2:~# gnt-node remove z2-6.host.gnt
Failure: command execution error:
list.remove(x): x not in list

However the node seems indeed removed from the cluster list:
z2-2:~# gnt-node list
Node          DTotal  DFree MTotal MNode MFree Pinst Sinst
z2-1.host.gnt   1.3T 649.3G   3.9G  2.2G  1.2G     8    10
z2-2.host.gnt   1.3T   1.1T   3.8G  2.1G  1.1G    10     9
z2-3.host.gnt   1.3T   1.1T   3.9G  2.5G  1.6G     8     8
z2-4.host.gnt   1.3T 569.8G   7.6G  3.4G  4.7G    11    13
z2-5.host.gnt   1.3T   1.2T   3.9G  2.5G  680M    10     6
z2-7.host.gnt 911.0G 375.5G  15.7G  410M 15.5G     1     2

Let me know if you need more information.
```
Originally added on 2009-11-16 15:52:26 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

Can you provide please:

- snippets from the master daemon log (/var/log/ganeti/masterd.log) when this error
occured
- what was the state of the node before? was it offlined recently, or demoted from
master candidate, etc.?

thanks,
iustin
```
Originally added on 2009-11-26 12:00:16 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,
sorry for the delay. 
We got this issue in 2 clusters :
  * ganeti 2.0.3 : 

commands.log :

2009-11-16 16:54:04,427: gnt-node remove pid=16572 INFO run with arguments 'z2-6.host.gnt'
2009-11-16 16:54:04,954: gnt-node remove pid=16572 ERROR Error durring command processing
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.5/ganeti/cli.py", line 746, in GenericMain
    result = func(options, args)
  File "/usr/sbin/gnt-node", line 380, in RemoveNode
    SubmitOpCode(op)
  File "/usr/lib/pymodules/python2.5/ganeti/cli.py", line 592, in SubmitOpCode
    op_results = PollJob(job_id, cl=cl, feedback_fn=feedback_fn)
  File "/usr/lib/pymodules/python2.5/ganeti/cli.py", line 574, in PollJob
    raise errors.OpExecError(str(msg))
OpExecError: list.remove(x): x not in list

master.log : 

2009-11-16 16:54:04,545:  pid=24087/Thread-43 INFO Op 1/1: Starting opcode NODE_REMOVE(z2-
6.host.gnt)
2009-11-16 16:54:04,545:  pid=24087/Thread-49 INFO Received job poll request for 49784
2009-11-16 16:54:04,602:  pid=24087/Thread-49 INFO Received job poll request for 49784
2009-11-16 16:54:04,603:  pid=24087/Thread-49 INFO Received job poll request for 49784
2009-11-16 16:54:04,660:  pid=24087/Thread-43 INFO Stopping the node daemon and removing 
configs from node z2-6.host.gnt
2009-11-16 16:54:04,660:  pid=24087/Thread-43 INFO Removing node z2-6.host.gnt from 
configuration
2009-11-16 16:54:04,841:  pid=24087/Thread-43 INFO Op 1/1: Error in opcode NODE_REMOVE(z2-
6.host.gnt): list.remove(x): x not in list
2009-11-16 16:54:04,897:  pid=24087/Thread-43 ERROR Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.5/ganeti/jqueue.py", line 404, in RunTask
    result = proc.ExecOpCode(input_opcode, _Log, self._NotifyStart)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 213, in ExecOpCode
    result = self._LockAndExecLU(lu, locking.LEVEL_INSTANCE)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 176, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 176, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 141, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 124, in _ExecLU
    hm.RunConfigUpdate()
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 365, in RunConfigUpdate
    results = self._RunWrapper(nodes, hpath, phase)
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 308, in _RunWrapper
    env = self._BuildEnv()[0]
  File "/usr/lib/pymodules/python2.5/ganeti/mcpu.py", line 293, in _BuildEnv
    lu_env, lu_nodes_pre, lu_nodes_post = self.lu.BuildHooksEnv()
  File "/usr/lib/pymodules/python2.5/ganeti/cmdlib.py", line 1901, in BuildHooksEnv
    all_nodes.remove(self.op.node_name)
ValueError: list.remove(x): x not in list

 * ganeti 2.0.4 

In commands.log : 

2010-01-01 08:56:13,787: gnt-node remove pid=658 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 750, in GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-node", line 380, in RemoveNode
    SubmitOpCode(op)
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 598, in SubmitOpCode
    op_results = PollJob(job_id, cl=cl, feedback_fn=feedback_fn)
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 580, in PollJob
    raise errors.OpExecError(str(msg))
OpExecError: list.remove(x): x not in list

in master.log : 

2010-01-01 08:56:13,141:  pid=5373/Thread-51 INFO Received job poll request for 70028
2010-01-01 08:56:13,619:  pid=5373/Thread-28 INFO Op 1/1: Error in opcode 
NODE_REMOVE(hosting15.rennes.tld): list.remove(x): x not in list
2010-01-01 08:56:13,700:  pid=5373/Thread-28 ERROR Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/jqueue.py", line 442, in RunTask
    result = proc.ExecOpCode(input_opcode, _Log, self._NotifyStart)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 213, in ExecOpCode
    result = self._LockAndExecLU(lu, locking.LEVEL_INSTANCE)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 176, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 176, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 141, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 124, in _ExecLU
    hm.RunConfigUpdate()
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 365, in RunConfigUpdate
    self._RunWrapper(nodes, hpath, phase)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 308, in _RunWrapper
    env = self._BuildEnv()[0]
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 293, in _BuildEnv
    lu_env, lu_nodes_pre, lu_nodes_post = self.lu.BuildHooksEnv()
  File "/usr/local/lib/python2.5/site-packages/ganeti/cmdlib.py", line 1932, in BuildHooksEnv
    all_nodes.remove(self.op.node_name)
ValueError: list.remove(x): x not in list


Regards,

Maxence
```
Originally added on 2010-01-22 08:57:16 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
> - what was the state of the node before? was it offlined recently, or demoted from
> master candidate, etc.?

In both cases, the node was evacuated before.
```
Originally added on 2010-01-22 09:07:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
OK, it seems we have a locking bug here, I'll fix at least the hooks generation and
add a warning log in there.

thanks,
iustin
```
Originally added on 2010-01-25 13:43:35 +0000 UTC.

Added Labels: Type-Defect
Changed State: Started

**Comment by Ganeti-Issues-Migrator** [comment]
```
Actually, I can't find this code in our codebase. It seems you're running Ganeti
modified with your patch from issue 71, so this is yours to fix :)

In any case, I'll add a handler for the exception there, since we don't want to hard
crash.

iustin
```
Originally added on 2010-01-25 14:09:06 +0000 UTC.

Mentioned Issue with GoogleCode ID 71 has been migrated to GitHub with ID #127.
Added Labels: Type-Other
Removed Labels: Type-Defect

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi, the code I have line 1932 on cmdlib.py is : 

    env = {
      "OP_TARGET": self.op.node_name,
      "NODE_NAME": self.op.node_name,
      }
    all_nodes = self.cfg.GetNodeList()
    all_nodes.remove(self.op.node_name)
    return env, all_nodes, all_nodes

Which I can find on git :
http://git.ganeti.org/?
p=ganeti.git;a=blob;f=lib/cmdlib.py;h=3914435455883045de5f9cac347459da0387e3ef;hb=88d
31e5c350c9afd3ee280749df3fbfb1b78d125#l1932

Anyway, one line in the call was made by one of our patch :
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 308, in 
_RunWrapper
    env = self._BuildEnv()[0]
  
It seems that on 2.1dev there is now a condition to avoid this error :
http://git.ganeti.org/?
p=ganeti.git;a=blob;f=lib/cmdlib.py;h=fd75ecba69b3ac5cf2d1a959865e74becc85d286;hb=b9f
8d18f941eac2f78b72ae80e08c15be8793d9b#l2427

I think you can close this bug anyway, since it should not be caused with unpatched 
code.

Cheers,

Maxence
```
Originally added on 2010-01-27 07:25:56 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes, the cmdlib code is on git, but the one-line call in mcpu.py was the cause of
problems.

For the record, I changed both 2.0 and 2.1 to handle this condition better and log a
warning in case it happens again; this will be in 2.0.6/2.1.x.

iustin
```
Originally added on 2010-01-27 08:24:29 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-10-22 08:57:07 +0000 UTC.

Changed State: Released
