### ISSUE TITLE
ganeti node hangs after a vm issue

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#138]
Originally reported of Google Code with ID 82.

```
ganeti 2.0.4.

I have a vm which, for an unknown reason, was hanging (no ssh, no console)
on node z2-4.host.gnt. The issue is that ganeti node daemon on this node
does not answer correctly. First, I was getting timeout when I tried to do
gnt-node info z2-4.host.gnt / gnt-node list / gnt-instance info about the
vms which are on this node.

Strange thing : netstat -antp see the port 1811 is managed by ganeti
process, telnet on port 1811 works, when I try to write something, I can
see in ganeti logs : 

Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/server.py", line
524, in _IncomingConnection
    self.request_executor(self, connection, client_addr)
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/server.py", line
263, in __init__
    http.Handshake(self.sock, self.WRITE_TIMEOUT)
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/__init__.py",
line 543, in Handshake
    raise HttpError("Timeout during SSL handshake")
HttpError: Timeout during SSL handshake

So the ganeti node correctly replies.
In /var/log/ganeti/node-daemon.log, I can only see "jobqueue_update"
request, all other requests are not logged (and the command timeout on the
master).

I tried to restart ganeti on z2-4.host.gnt : the ganeti-node is not killed,
so have to kill it by hand and start ganeti. But even after daemon restart,
the telnet is still ok, but all requests from ganeti master timeouted. 

Nothing about kvm on logs.
Finally, I had to restart the node, and everything is going back to normal.

I have some questions due to this issue: 
- I can't find any kvm log, does ganeti just doesn't handle them  ? 
- Even if the vm crash may not be due to ganeti (kvm maybe , but without
logs :/), is it normal that ganeti-node does not reply anymore ?

Cheers,

Maxence
```
Originally added on 2009-12-07 10:23:10 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Log of a gnt-node list :

z2-2:~# gnt-node list
Traceback (most recent call last):
  File "/usr/local/sbin/gnt-node", line 560, in <module>
    sys.exit(GenericMain(commands, override={"tag_type": constants.TAG_NODE}))
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 750, in GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-node", line 135, in ListNodes
    output = GetClient().QueryNodes(args, selected_fields, opts.do_locking)
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 372, in QueryNodes
    return self.CallMethod(REQ_QUERY_NODES, (names, fields, use_locking))
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 307, in CallMethod
    result = self.transport.Call(send_data)
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 233, in Call
    return self.Recv()
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 211, in Recv
    data = self.socket.recv(4096)
socket.timeout: timed out

```
Originally added on 2009-12-07 10:30:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Log of a gnt-node list :

z2-2:~# gnt-node list
Traceback (most recent call last):
  File "/usr/local/sbin/gnt-node", line 560, in <module>
    sys.exit(GenericMain(commands, override={"tag_type": constants.TAG_NODE}))
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 750, in GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-node", line 135, in ListNodes
    output = GetClient().QueryNodes(args, selected_fields, opts.do_locking)
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 372, in QueryNodes
    return self.CallMethod(REQ_QUERY_NODES, (names, fields, use_locking))
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 307, in CallMethod
    result = self.transport.Call(send_data)
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 233, in Call
    return self.Recv()
  File "/usr/local/lib/python2.5/site-packages/ganeti/luxi.py", line 211, in Recv
    data = self.socket.recv(4096)
socket.timeout: timed out

```
Originally added on 2009-12-07 10:31:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Could you try restarting masterd? A luxi error suggests a stuck master daemon (which
we've seen, but only in a recoverable manner, when you submit many long-running jobs).

Thanks,

Guido

```
Originally added on 2009-12-07 10:44:39 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I could, but since it is working after the reboot of z2-4 node ... 
The master daemon was working , for exemple on gnt-cluster verify, all nodes except
z2-4 were replying.
```
Originally added on 2009-12-07 10:57:01 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
So, was there anything in the linux logs (not ganeti) of z2-4? If there would have 
been an oops or such that broken the node, it should be visible there.

Ganeti doesn't log such events to its own logs.

If that happens again, you could try strace-ing the ganeti-noded process.

regards,
iustin
```
Originally added on 2009-12-07 11:04:38 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ok, I'll try a strace. There is absolutely nothing on z2-4 node :'(
```
Originally added on 2009-12-07 11:09:13 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hmm, I have another issue on antoher node (with lvchange, will certainly open another
bug report), but the ganeti-node behavior is the same, except one thing : 

z2-3:~# ps aux|grep noded
root      6395  0.0  0.2  82108  8948 ?        S    08:57   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded
root      6409  0.0  0.2  82872  9592 ?        S    08:57   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded
root      6425  0.0  0.2  82876  9612 ?        S    09:00   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded
root     16190  0.0  0.2  82876  9600 ?        S    11:42   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded
root     16251  0.0  0.2  82876  9600 ?        S    11:44   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded
root     16261  0.0  0.2  82876  9600 ?        S    11:46   0:00 /usr/bin/python
/usr/local/sbin/ganeti-noded


I don't know why so many noded are started ...

z2-3:~# strace -p 6395
Process 6395 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>
^C <unfinished ...>
Process 6395 detached
z2-3:~# strace -p 6409
Process 6409 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
Process 6409 detached
z2-3:~# strace -p 6425
Process 6425 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
Process 6425 detached
z2-3:~# strace -p 16190
Process 16190 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
Process 16190 detached
z2-3:~# strace -p 16251
Process 16251 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
Process 16251 detached
z2-3:~# strace -p 16261
Process 16261 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
Process 16261 detached



```
Originally added on 2009-12-07 11:13:46 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2010-03-12 19:39:33 +0000 UTC.

Added to Milestone: Unplanned

**Comment by Ganeti-Issues-Migrator** [comment]
```
I haven't seen any updated on this issue in a long while, I'm going to close it.

If you want to reopen, please try first to reproduce with a more recent version of ganeti.
```
Originally added on 2011-08-02 12:13:35 +0000 UTC.

Changed State: NotRepeatable
Removed from Milestone: Unplanned
