### ISSUE TITLE
hs2py creates python2 code

### ISSUE THREAD

**Issue by atta** [ganeti/ganeti#1393]
it looks like hs2py creates python2 code 

'make hs-tests' 

```
src/hs2py --constants >> lib/_constants.py
set -e; \
VCSVER=`cat /builds/ansgar-guest/ganeti/vcs-version`; \
{ echo '# This file is automatically generated, do not edit!'; \
  echo '#'; \
  echo ''; \
  echo '"""Build-time VCS version number for Ganeti.'; \
  echo '';\
  echo 'This file is autogenerated by the build process.'; \
  echo 'For any changes you need to re-run ./configure (and'; \
  echo 'not edit by hand).'; \
  echo ''; \
  echo '"""'; \
  echo ''; \
  echo '# pylint: disable=C0301,C0324'; \
  echo '# because this is autogenerated, we do not want'; \
  echo '# style warnings' ; \
  echo ''; \
  echo "VCS_VERSION = '$VCSVER'"; \
} > lib/_vcsversion.py
cat /builds/ansgar-guest/ganeti/lib/opcodes.py.in_before > lib/opcodes.py
src/hs2py --opcodes >> lib/opcodes.py
cat /builds/ansgar-guest/ganeti/lib/opcodes.py.in_after >> lib/opcodes.py
src/hs2py --wconfd-rpc > lib/rpc/stub/wconfd.py
src/hs2py --metad-rpc > lib/rpc/stub/metad.py
```

some error output:
```
JQueue:
  JobPriorityDef: [OK]
  JobPriority: [OK, passed 500 tests]
  JobStatusDef: [OK]
  JobStatus: [OK, passed 500 tests]
  JobStatusPri_py_equiv: [Failed]
python exited with error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ganeti/jqueue/__init__.py", line 50, in <module>
    from ganeti import asyncnotifier
  File "ganeti/asyncnotifier.py", line 43, in <module>
    from ganeti import daemon
  File "ganeti/daemon.py", line 47, in <module>
    from ganeti import utils
  File "ganeti/utils/__init__.py", line 60, in <module>
    from ganeti.utils.log import *
  File "ganeti/utils/log.py", line 37, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
```

**Comment by jenshadlich** [comment]
https://docs.python.org/3.0/whatsnew/3.0.html

> The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.
