### ISSUE TITLE
Invalid formatting in mcpu.py

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#140]
Originally reported of Google Code with ID 84.

```
Hi,

ganeti 2.0.4, I'm trying to grow a disk like this : 
z2-2:~# gnt-instance grow-disk -d maggie.gna.vm.gnt 0 10G

And I get  :

DEBUG : maggie.gna.vm.gnt 0 10240 True
2009-12-11 08:23:44,279: gnt-instance grow-disk pid=1766 cli:754 ERROR
Error during command processing
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 750, in
GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-instance", line 683, in GrowDisk
    SubmitOrSend(op, opts)
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 616, in
SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn)
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 598, in
SubmitOpCode
    op_results = PollJob(job_id, cl=cl, feedback_fn=feedback_fn)
  File "/usr/local/lib/python2.5/site-packages/ganeti/cli.py", line 580, in
PollJob
    raise errors.OpExecError(str(msg))
OpExecError: not all arguments converted during string formatting
Failure: command execution error:
not all arguments converted during string formatting


this exception is normaly raised per python when, for exemple, you have for
items than "%s" :
print "foo %s bar " % ("1" , "2")

But I can't find where in the code is the issue. I'm not sure if it only
arrives for commands with more than 2 args (instance name, disk number,
size here), because I can't find another one to do that.

Cheers,

MAxence
```
Originally added on 2009-12-11 07:26:39 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Can you please give us the backtrace from the master daemon? (usually found in
/var/log/ganeti/master-daemon.log)
```
Originally added on 2009-12-11 10:23:16 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```

2009-12-11 15:06:52,945:  pid=12481/Thread-56 INFO Received new job
2009-12-11 15:06:53,002:  pid=12481/Thread-56 ERROR RPC error in jobqueue_update from
node z2-3.host.gnt: Connection failed (101: Network is unreachable)
2009-12-11 15:06:53,061:  pid=12481/Thread-56 ERROR RPC error in jobqueue_update from
node z2-3.host.gnt: Connection failed (101: Network is unreachable)
2009-12-11 15:06:53,061:  pid=12481/Thread-24 INFO Worker 4 processing job 56844
2009-12-11 15:06:53,062:  pid=12481/Thread-56 INFO Received job poll request for 56844
2009-12-11 15:06:53,062:  pid=12481/Thread-24 INFO Op 1/1: Starting opcode
INSTANCE_GROW_DISK(maggie.gna.vm.gnt)
2009-12-11 15:06:53,062:  pid=12481/Thread-56 INFO Received job poll request for 56844
2009-12-11 15:06:53,119:  pid=12481/Thread-24 ERROR RPC error in jobqueue_update from
node z2-3.host.gnt: Connection failed (101: Network is unreachable)
2009-12-11 15:06:53,120:  pid=12481/Thread-56 INFO Received job poll request for 56844
2009-12-11 15:06:53,120:  pid=12481/Thread-56 INFO Received job poll request for 56844
2009-12-11 15:06:53,785:  pid=12481/Thread-17 ERROR Worker 7: Caught unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/workerpool.py", line 118, in run
    self.RunTask(*self._current_task)
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/client.py", line 331, in
RunTask
    HttpClientRequestExecutor(pend_req.request)
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/client.py", line 175, in
__init__
    self._Connect()
  File "/usr/local/lib/python2.5/site-packages/ganeti/http/client.py", line 215, in
_Connect
    self.request.port))
  File "<string>", line 1, in connect_ex
TypeError: coercing to Unicode: need string or buffer, tuple found
2009-12-11 15:06:53,795:  pid=12481/Thread-24 ERROR RPC error in hooks_runner from
node ('z2-5.host.gnt', 'z2-6.host.gnt'): None
2009-12-11 15:06:53,796:  pid=12481/Thread-24 INFO Op 1/1: Error in opcode
INSTANCE_GROW_DISK(maggie.gna.vm.gnt): not all arguments converted during string
formatting
2009-12-11 15:06:53,852:  pid=12481/Thread-24 ERROR RPC error in jobqueue_update from
node z2-3.host.gnt: Connection failed (101: Network is unreachable)
2009-12-11 15:06:53,853:  pid=12481/Thread-24 ERROR Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/jqueue.py", line 442, in RunTask
    result = proc.ExecOpCode(input_opcode, _Log, self._NotifyStart)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 213, in ExecOpCode
    result = self._LockAndExecLU(lu, locking.LEVEL_INSTANCE)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 168, in
_LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 168, in
_LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 141, in
_LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 113, in _ExecLU
    h_results = hm.RunPhase(constants.HOOKS_PHASE_PRE)
  File "/usr/local/lib/python2.5/site-packages/ganeti/mcpu.py", line 346, in RunPhase
    node_name)
TypeError: not all arguments converted during string formatting
2009-12-11 15:06:53,910:  pid=12481/Thread-24 ERROR RPC error in jobqueue_update from
node z2-3.host.gnt: Connection failed (101: Network is unreachable)
2009-12-11 15:06:53,910:  pid=12481/Thread-24 INFO Worker 4 finished job 56844,
status = error
2009-12-11 15:06:53,911:  pid=12481/Thread-56 INFO Received job query request for 56844


(the z2-3 host is actually down, but the instance is on z2-6:z2-5)
```
Originally added on 2009-12-11 14:08:14 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

This seems to be a wrong formatting in mcpu.py.

Could you try this patch please:
diff --git a/lib/mcpu.py b/lib/mcpu.py
index 959a837..ec2b7e2 100644
--- a/lib/mcpu.py
+++ b/lib/mcpu.py
@@ -343,7 +343,7 @@ class HooksMaster(object):
         if res.failed or res.data is False or not isinstance(res.data, list):
           if not res.offline:
             self.proc.LogWarning("Communication failure to node %s" %
-                                 node_name)
+                                 (node_name, ))
           continue
         for script, hkr, output in res.data:
           if hkr == constants.HKR_FAIL:

```
Originally added on 2009-12-14 12:27:43 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
sorry not to have answered before, the patch works :)

Regards,

Maxence
```
Originally added on 2010-02-01 15:52:27 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Not a problem :)

This was committed and will be in 2.0.6 and 2.1.1.

iustin
```
Originally added on 2010-02-01 16:04:47 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-10-22 08:57:07 +0000 UTC.

Changed State: Released
