### ISSUE TITLE
Ganeti build from source code  branch stable-2.16 not success.

### ISSUE THREAD

**Issue by rchatsiri** [ganeti/ganeti#1447]
I'm follow instruction compiles source code from [link](http://docs.ganeti.org/ganeti/2.17/html/devnotes.html).  Simple steps run build source after installed required package on Ubuntu. 
```
$./autogen.sh
```
```
$./configure --localstatedir=/var --sysconfdir=/etc && \
  make
```
An error from trackback file ``` /tmp/sphinx-err-4aw786l1.log ```  show as below.

```
# Sphinx version: 3.1.0+
# Python version: 3.6.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/gntbuild.QOuM9XUr/ganeti/build/sphinx_ext.py", line 288
    except Exception, err: # pylint: disable=W0703
                    ^
SyntaxError: invalid syntax
```

**Comment by rbott** [comment]
You see this error because up to Ganeti 2.16 all Python code is Python 2 only - and you are using Python 3 to build. You either need Python 2.7 for successful building or you need to build from the current master branch, which has not been thoroughly tested yet (but aims to be Python 3 compatible).

**Comment by saschalucas** [comment]
There is probably a mistake here... and the issue was closed to early? The configure script will check whether python is python2. It refuses to work with python3:

https://github.com/ganeti/ganeti/blob/fc5809c2becb9c8726127ebd93c3137304a5618c/configure.ac#L879-L886

The error above seems to belong to generation of documentation.

@rchatsiri: please try to remove `python-sphinx`and run `./configure --disable-manpages-in-doc ...`. One of this should disable invocation of `sphinx-build` and stable-2.16 should compile fine on Ubuntu (18.04). You may also be interested in the [PPA](https://launchpad.net/~pkg-ganeti-devel/+archive/ubuntu/lts) for pre-build packages.

The error itself needs further investigation.

**Comment by rchatsiri** [comment]
I'm update version of ``` Python 3.6.9 ``` and build source code on master branch commit https://github.com/ganeti/ganeti/commit/09761f505af557be76fa605c6f7af7f6ab0c11ad. Create make file by used this command line.

```$./configure --prefix=/usr/local --sysconfdir=/etc --localstatedir=/var   --disable-manpages-in-doc```
Run make command line with ```$make```.

The result after compile source code as issues from ```sphinx-build```. 

```
sed -f autotools/replace_vars.sed < man/mon-collector.html.in > man/mon-collector.html
if test -n ''; then \
  echo 'Man pages in documentation were disabled at configure time' >&2; \
  exit 1; \
fi
dir=doc/html/ && \
/bin/mkdir -p $dir && \
PYTHONPATH=. ENABLE_MANPAGES= COPY_DOC=1 \
        HTML_THEME=classic \
./autotools/run-in-tempdir \
    /home/vagrant/workspacevm-dev/ganeti/autotools/sphinx-wrapper /home/vagrant/.local/bin/sphinx-build -q -W -b html \
        -d . \
        -D version="3.0" \
        -D release="3.0.0~alpha1" \
        -D graphviz_dot="/usr/bin/dot" \
doc /home/vagrant/workspacevm-dev/ganeti/$dir && \
rm -f $dir/.buildinfo $dir/objects.inv
/tmp/gntbuild.4LN2zweN/ganeti/build/shell_example_lexer.py:82: RemovedInSphinx40Warning: app.add_lexer() API changed; Please give lexer class instead instance
  app.add_lexer("shell-example", ShellExampleLexer())
```

My view, The flag ```--disable-manpages-in-doc``` cannot by pass an error from build Sphinx document format cause an error result as above. Compile steps to prevent an error message from Sphinx document generator by **comments** line number of code at https://github.com/ganeti/ganeti/blob/09761f505af557be76fa605c6f7af7f6ab0c11ad/Makefile.am#L1177-L1189 and https://github.com/ganeti/ganeti/blob/09761f505af557be76fa605c6f7af7f6ab0c11ad/Makefile.am#L1210
After recompile without generated Sphinx document.  It's successful for building binary file.

* Tools and compiler version.
 1. Linux version 4.15.0-99-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #100-Ubuntu SMP Wed Apr 22 20:32:56 UT
C 2020
 2. cabal-install version 1.24.0.2
 3. The Glorious Glasgow Haskell Compilation System, version 8.0.2
 4. sphinx-build 3.1.0+
 5. Python 3.6.9
