### ISSUE TITLE
python tests fail if hostname can not be resolved

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1455]
steps to reproduce:
```bash
hostname knowhost
./configure
make py-tests
```

error output:
```
======================================================================
ERROR: testUnlockedGetHvparamsString (__main__.TestConfigRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/gntbuild.uhsKzaTi/ganeti/netutils.py", line 232, in GetIP
    result = socket.getaddrinfo(hostname, None)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/py/ganeti.config_unittest.py", line 66, in setUp
    self._init_cluster(self.cfg_file)
  File "test/py/ganeti.config_unittest.py", line 87, in _init_cluster
    me = netutils.Hostname()
  File "/tmp/gntbuild.uhsKzaTi/ganeti/netutils.py", line 181, in __init__
    self.ip = self.GetIP(self.name, family=family)
  File "/tmp/gntbuild.uhsKzaTi/ganeti/netutils.py", line 236, in GetIP
    raise errors.ResolverError(hostname, err.args[0], err.args[1])
ganeti.errors.ResolverError: ('knowhost', -2, 'Name or service not known')
```

**Comment by iustin** [comment]
This is a very strange situation for which I believe a lot of software will fail in random ways. Adding a check for it will help make the error message much more clear (and earlier), but it's an unlikely situation (I think).
