### ISSUE TITLE
Ubuntu 20.04 python unit tests failures

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1476]
running python unit test `make py-tests` on Ubuntu 20.04 (Focal) yields to the following three errors:

**Running ganeti.ovf_unittest.py**
```text
.............................................................FF.....F
======================================================================
FAIL: testOVFWriterInit (__main__.TestOVFWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/py/ganeti.ovf_unittest.py", line 794, in testOVFWriterInit
    self.assertTrue(EXPORT_EMPTY in result)
AssertionError: False is not true

======================================================================
FAIL: testSaveDisksData (__main__.TestOVFWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/py/ganeti.ovf_unittest.py", line 804, in testSaveDisksData
    self.assertTrue(EXPORT_DISKS in result)
AssertionError: False is not true

======================================================================
FAIL: testSaveVirtualSystem (__main__.TestOVFWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/py/ganeti.ovf_unittest.py", line 831, in testSaveVirtualSystem
    self.assertTrue(EXPORT_SYSTEM in result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 69 tests in 0.124s

FAILED (failures=3)
FAIL: test/py/ganeti.ovf_unittest.py
```
**Running ganeti.objects_unittest.py**
```text
........................E...............
======================================================================
ERROR: testCheckISpecSyntax (__main__.TestInstancePolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/py/ganeti.objects_unittest.py", line 546, in testCheckISpecSyntax
    for param in spec:
RuntimeError: dictionary keys changed during iteration

----------------------------------------------------------------------
Ran 40 tests in 0.012s

FAILED (errors=1)
FAIL: test/py/ganeti.objects_unittest.py
```

**Running ganeti.cli_unittest.py**
```text
........./test/py/ganeti.cli_unittest.py:1151: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(buf.getvalue())
E................................................................
======================================================================
ERROR: testWithDefaults (__main__.TestFormatPolicyInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/py/ganeti.cli_unittest.py", line 1182, in testWithDefaults
    self._PrintAndCheckParsed(constants.IPOLICY_DEFAULTS)
  File "./test/py/ganeti.cli_unittest.py", line 1155, in _PrintAndCheckParsed
    self._TranslateParsedNames(parsed)
  File "./test/py/ganeti.cli_unittest.py", line 1138, in _TranslateParsedNames
    for key in minmax:
RuntimeError: dictionary keys changed during iteration

----------------------------------------------------------------------
Ran 73 tests in 0.019s

FAILED (errors=1)
FAIL: test/py/ganeti.cli_unittest.py
```

**Comment by apoikos** [comment]
The OVF test failures are because the tests compare the XML output produced by xml.etree with known-good strings. In Python 3.8 the etree output changed and XML elements now have their attributes written out in _insertion_ order rather than using alphanumeric sorting.

I have yet to find out why the other failures (in-place dict modifications) were uncovered now, but I have fixes for all of them.

**Comment by apoikos** [comment]
> I have yet to find out why the other failures (in-place dict modifications) were uncovered now, but I have fixes for all of them.

Okay, these are corner cases that do not change the key count and are only detected since Python 3.8: https://bugs.python.org/issue36452
