### ISSUE TITLE
Build problem: ganeti-cleaner missing in time for bash completions

### ISSUE THREAD

**Issue by mweinelt** [ganeti/ganeti#1520]
I'm trying to package ganeti for NixOS and I'm pretty far along, but now running into issues during bash completion generation. The build process can't find the ganeti-cleaner daemon. I attached the complete build log below and I'm looking for advice.

```pytb
PYTHONPATH=. ./autotools/run-in-tempdir \
  /build/ganeti-f3f033a/./autotools/build-bash-completion --compact > doc/examples/bash_completion
PYTHONPATH=. ./autotools/run-in-tempdir \
  /build/ganeti-f3f033a/./autotools/build-bash-completion  > doc/examples/bash_completion-debug
Traceback (most recent call last):
  File "/build/gntbuild.EO1XnhqH/ganeti/utils/process.py", line 227, in RunCmd
    out, err, status, timeout_action = _RunCmdPipe(cmd, cmd_env, shell, cwd,
  File "/build/gntbuild.EO1XnhqH/ganeti/utils/process.py", line 556, in _RunCmdPipe
    child = subprocess.Popen(cmd, shell=via_shell,
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './daemons/ganeti-cleaner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 917, in <module>
    main()
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 894, in main
    WriteHaskellCompletion(sw, "daemons/ganeti-cleaner", htools=False,
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 820, in WriteHaskellCompletion
    output = utils.RunCmd([cmd, "--help-completion"], env=env, cwd=".").output
  File "/build/gntbuild.EO1XnhqH/ganeti/utils/process.py", line 241, in RunCmd
    raise errors.OpExecError("Can't execute '%s': not found (%s)" %
ganeti.errors.OpExecError: Can't execute './daemons/ganeti-cleaner --help-completion': not found ([Errno 2] No such file or directory: './daemons/ganeti-cleaner')
Traceback (most recent call last):
  File "/build/gntbuild.WjkumsyP/ganeti/utils/process.py", line 227, in RunCmd
    out, err, status, timeout_action = _RunCmdPipe(cmd, cmd_env, shell, cwd,
  File "/build/gntbuild.WjkumsyP/ganeti/utils/process.py", line 556, in _RunCmdPipe
    child = subprocess.Popen(cmd, shell=via_shell,
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './daemons/ganeti-cleaner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 917, in <module>
    main()
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 894, in main
    WriteHaskellCompletion(sw, "daemons/ganeti-cleaner", htools=False,
  File "/build/ganeti-f3f033a/./autotools/build-bash-completion", line 820, in WriteHaskellCompletion
    output = utils.RunCmd([cmd, "--help-completion"], env=env, cwd=".").output
  File "/build/gntbuild.WjkumsyP/ganeti/utils/process.py", line 241, in RunCmd
    raise errors.OpExecError("Can't execute '%s': not found (%s)" %
ganeti.errors.OpExecError: Can't execute './daemons/ganeti-cleaner --help-completion': not found ([Errno 2] No such file or directory: './daemons/ganeti-cleaner')
make: *** [Makefile:4506: doc/examples/bash_completion] Error 1
make: *** Deleting file 'doc/examples/bash_completion'
make: *** Waiting for unfinished jobs....
make: *** [Makefile:4506: doc/examples/bash_completion-debug] Error 1
make: *** Deleting file 'doc/examples/bash_completion-debug'
touch doc/html/index.html
builder for '/nix/store/srlbz4xwq2b4hgf0inbm82wqx1hnbg95-ganeti-v3.0.0beta1-40-gf3f033a62.drv' failed with exit code 2
```

[ganeti.log](https://github.com/ganeti/ganeti/files/5212051/ganeti.log)

**Comment by saschalucas** [comment]
I assume you already checked, that the script `./daemons/ganeti-cleaner` is in the build directory? From your attached log it is created via a `sed` script (lines 1032-1034):

```
1032 sed -f autotools/replace_vars.sed < daemons/ganeti-cleaner.in > daemons/ganeti-cleaner
1033 chmod +x tools/net-common
1034 chmod +x daemons/ganeti-cleaner
```

Earlier I noticed special NixOS things:
```
8 patching script interpreter paths in autotools
9 autotools/testrunner: interpreter directive changed from "/bin/bash" to "/nix/store/6ffp6xbr6j2ryqw2dafbbvv55ggq16iv-bash-4.4-p23/bin/bash"
```
`daemons/ganeti-cleaner.in` itself is also a shell script. could it be possible, that this needs also patching of interpreter paths? I would try to run `./daemons/ganeti-cleaner` manually in the build directory after the build failure ... and see what happens ...

**Comment by mbakke** [comment]
It looks like the whole build happens in `autoreconfPhase`, is that correct?  I would have expected to see `configurePhase` and `buildPhase` too, though I haven't used NixOS in many years.

Guix has a special `patch-generated-file-shebangs` phase in between the `configure` and `build` phases, probably something like it is missing here?  Otherwise the shebang of `ganeti-cleaner` will be `#!/bin/bash` which is sensibly missing from the Nix build container.

Alternatively you can patch the shebang of `daemons/ganeti-cleaner.in` up-front.

**Comment by mweinelt** [comment]
That is an interesting observation. My current progress is this, so there is definetely an explicit configure and an implicit build phase.

```nix
{ lib, stdenv, fetchgit, fetchpatch
, autoreconfHook
, bash
, curl
, cabal-install
, fakeroot
, fping
, ghc
, glibcLocales
, graphviz
, hlint
, iproute
, man
, ndisc6
, pandoc
, python3
, qemu
, socat
}:

let
  ghc' = ghc.withPackages (g: with g; [
    attoparsec
    base64-bytestring
    Cabal_3_2_0_0
    cabal-install
    cryptonite
    g.curl
    hinotify
    hsc2hs
    hscolour
    hslogger
    json
    lens
    lifted-base
    network
    old-time
    regex-pcre
    snap-server
    PSQueue
    temporary
    test-framework-hunit
    test-framework-quickcheck2
    utf8-string
    vector
    zlib
  ]);

  python' = python3.withPackages (p: with p; [
    bitarray
    coverage
    mock
    paramiko
    pep8
    psutil
    pycurl
    pyinotify
    pylint
    pyopenssl
    pyparsing
    pyyaml
    simplejson
    sphinx
  ]);

in stdenv.mkDerivation rec {
  pname = "ganeti";
  version = "3.0.0beta1-40-gf3f033a62";

  src = fetchgit {
    url = "https://github.com/ganeti/ganeti.git";
    rev = "f3f033a62c15f63cbc091be9924a2a370c874a39";
    sha256 = "0c52fbbqd0p7xn924zkg5p8mrrd8z7wyy2lik85vycl1fjggi3ad";
    leaveDotGit = true;
  };

  postPatch = ''
    substituteInPlace Makefile.am --replace "SHELL=/bin/bash" "SHELL=${bash.out}/bin/bash"
    patchShebangs .
  '';

  nativeBuildInputs = [
    autoreconfHook
    fakeroot
    ghc'
    glibcLocales
    graphviz
    hlint
    man
    pandoc
    python'
  ];

  buildInputs = [
    curl
    fping
    iproute
    ndisc6
    python'
    qemu
    socat
  ];

  configurePhase = ''
    ./configure \
      --localstatedir=/var \
      --sharedstatedir=/var \
      --sysconfdir=/etc \
      --enable-haskell-tests
  '';

  checkPhase = ''
    make py-tests
    make hs-tests
  '';

  meta = with lib; {
    description = "Ganeti is a virtual machine cluster management tool";
    longDescription = ''
      Ganeti is a virtual machine cluster management tool built on top of existing virtualization technologies such as
      Xen or KVM and other open source software.
    '';
    license = licenses.bsd2;
    homepage = "http://www.ganeti.org/";
    maintainers = with maintainers; [ hexa ];
  };
}
```

I'M also patching shebangs in the whole source tree now. No change.

I haven't checked the build dir as everything gets built in a sandbox and I haven't gotten to inspecting things yet.

**Comment by mbakke** [comment]
I think you can use `--keep-failed` with `nix-build` to preserve the failed build tree in `/tmp/nix-build-ganeti.drv-0` or thereabouts.

**Comment by mweinelt** [comment]
Indeed the shebang is not replaced, I'll investigate in the next few days when I find some time.

**Comment by mweinelt** [comment]
Okay, this was due to no replacing shebangs everywhere properly. I'm progresing slowly.

**Comment by mweinelt** [comment]
Down to a bunch of remaining python tests, then the haskell tests and then … the module.  The guix package is a good reference, thanks @mbakke.

```
Running ganeti.hooks_unittest.py
......F.F....F.
======================================================================
FAIL: testEnv (__main__.TestHooksRunner)
Test environment execution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 205, in testEnv
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, env_snt),
AssertionError: Lists differ: [('fa[14 chars]ss', 1, "/build/tmpoeie5xx1/fake-pre.d/success[100 chars]n.")] != [('fa[14 chars]ss', 2, 'PHASE=pre')]

First differing element 0:
('fak[13 chars]ss', 1, "/build/tmpoeie5xx1/fake-pre.d/success[99 chars]on.")
('fak[13 chars]ss', 2, 'PHASE=pre')

+ [('fake-pre.d/success', 2, 'PHASE=pre')]
- [('fake-pre.d/success',
-   1,
-   "/build/tmpoeie5xx1/fake-pre.d/success: unknown program 'success'\\nTry "
-   "'/build/tmpoeie5xx1/fake-pre.d/success --help' for more information.")]

======================================================================
FAIL: testOrdering (__main__.TestHooksRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 194, in testOrdering
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}), expect)
AssertionError: Lists differ: [('fake-pre.d/00s0', 1, "/build/tmp3ygt17nv/fake-pre.d/00s0: u[723 chars]n.")] != [('fake-pre.d/00s0', 2, ''), ('fake-pre.d/10s1', 2, ''), ('fak[73 chars] '')]

First differing element 0:
('fake-pre.d/00s0', 1, "/build/tmp3ygt17nv/fake-pre.d/00s0: u[90 chars]on.")
('fake-pre.d/00s0', 2, '')

Diff is 1195 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: testSymlink (__main__.TestHooksRunner)
Test running a symlink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 148, in testSymlink
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}),
AssertionError: Lists differ: [('fa[14 chars]ss', 1, "/build/tmpfw1e6y58/fake-pre.d/success[100 chars]n.")] != [('fa[14 chars]ss', 2, '')]

First differing element 0:
('fak[13 chars]ss', 1, "/build/tmpfw1e6y58/fake-pre.d/success[99 chars]on.")
('fak[13 chars]ss', 2, '')

- [('fake-pre.d/success',
+ [('fake-pre.d/success', 2, '')]
?                        ++++++++

-   1,
-   "/build/tmpfw1e6y58/fake-pre.d/success: unknown program 'success'\\nTry "
-   "'/build/tmpfw1e6y58/fake-pre.d/success --help' for more information.")]

----------------------------------------------------------------------
Ran 15 tests in 0.025s

FAILED (failures=3)
```

```
Running ganeti.storage.filestorage_unittest.py
............F..............
======================================================================
FAIL: test (__main__.TestComputeWrongFileStoragePathsInternal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.storage.filestorage_unittest.py", line 150, in test
    self.assertEqual(vfsp(["/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31/bin/ls"]), ["/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31/bin/ls"])
AssertionError: Lists differ: [] != ['/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31/bin/ls']

Second list contains 1 additional elements.
First extra element 0:
'/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31/bin/ls'

- []
+ ['/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31/bin/ls']
```


Complete build log: https://gist.github.com/mweinelt/b692c5ede2cd6b8ee0b5d0adf54e9b3b

**Comment by mbakke** [comment]
Great.  I see you found the [disable-version-symlinks](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/ganeti-disable-version-symlinks.patch) patch.  It comes with a big caveat that `gnt-cluster upgrade` is untested and might break!  Not a big deal until Ganeti 3.1 is approaching though...

I will submit it as a draft PR in the coming days to get some discussion about it.  Note that it is actually patch 2/2 in a series that includes this mostly harmless [ganeti-haskell-pythondir.patch](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/ganeti-haskell-pythondir.patch).

**Comment by mweinelt** [comment]
I'm add odds with this check:

https://github.com/ganeti/ganeti/blob/40255a7352f9a84107a7f605dc460db50820987d/lib/storage/filestorage.py#L374

The function checks if a path (`'/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls`) is a valid storage path and checks three cases

- Is the path absolute? Sure!
- Is the path a forbidden path? No, that path is certainly not explicitly forbidden.
- Is the path below a forbidden path? No, nothing below `/nix` is forbidden.

The first two checks are rather simple, so I believe the third check is what I'm having problems with.

```
Running ganeti.storage.filestorage_unittest.py
............F..............
======================================================================
FAIL: test (__main__.TestComputeWrongFileStoragePathsInternal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.storage.filestorage_unittest.py", line 150, in test
    self.assertEqual(vfsp(["/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls"]), ["/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls"])
AssertionError: Lists differ: [] != ['/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls']

Second list contains 1 additional elements.
First extra element 0:
'/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls'

- []
+ ['/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/ls']
```

**Comment by mweinelt** [comment]
These three tests fail because they create a symlink from `success` to `true`, which itself is a symlink to `coreutils`. And `coreutils` replies that it doesn't know a `success` program. I'll guess I'll overwrite coreutils not to use symlinks for ganeti then.

```
Running ganeti.hooks_unittest.py
......F.F....F.
======================================================================
FAIL: testEnv (__main__.TestHooksRunner)
Test environment execution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 205, in testEnv
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, env_snt),
AssertionError: Lists differ: [('fa[14 chars]ss', 1, "/build/tmp2gfpprc6/fake-pre.d/success[100 chars]n.")] != [('fa[14 chars]ss', 2, 'PHASE=pre')]

First differing element 0:
('fak[13 chars]ss', 1, "/build/tmp2gfpprc6/fake-pre.d/success[99 chars]on.")
('fak[13 chars]ss', 2, 'PHASE=pre')

+ [('fake-pre.d/success', 2, 'PHASE=pre')]
- [('fake-pre.d/success',
-   1,
-   "/build/tmp2gfpprc6/fake-pre.d/success: unknown program 'success'\\nTry "
-   "'/build/tmp2gfpprc6/fake-pre.d/success --help' for more information.")]

======================================================================
FAIL: testOrdering (__main__.TestHooksRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 194, in testOrdering
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}), expect)
AssertionError: Lists differ: [('fake-pre.d/00s0', 1, "/build/tmpoa17h981/fake-pre.d/00s0: u[723 chars]n.")] != [('fake-pre.d/00s0', 2, ''), ('fake-pre.d/10s1', 2, ''), ('fak[73 chars] '')]

First differing element 0:
('fake-pre.d/00s0', 1, "/build/tmpoa17h981/fake-pre.d/00s0: u[90 chars]on.")
('fake-pre.d/00s0', 2, '')

Diff is 1195 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: testSymlink (__main__.TestHooksRunner)
Test running a symlink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 148, in testSymlink
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}),
AssertionError: Lists differ: [('fa[14 chars]ss', 1, "/build/tmp2ls2lh29/fake-pre.d/success[100 chars]n.")] != [('fa[14 chars]ss', 2, '')]

First differing element 0:
('fak[13 chars]ss', 1, "/build/tmp2ls2lh29/fake-pre.d/success[99 chars]on.")
('fak[13 chars]ss', 2, '')

- [('fake-pre.d/success',
+ [('fake-pre.d/success', 2, '')]
?                        ++++++++

-   1,
-   "/build/tmp2ls2lh29/fake-pre.d/success: unknown program 'success'\\nTry "
-   "'/build/tmp2ls2lh29/fake-pre.d/success --help' for more information.")]
```

**Comment by mweinelt** [comment]
Awesome, progress. Next up: I wonder why ganeti expects what I assume to be an exit code of 2 (hkrSuccess) from `/bin/env` and `/bin/true`.

```
Running ganeti.hooks_unittest.py
......F.F....F.
======================================================================
FAIL: testEnv (__main__.TestHooksRunner)
Test environment execution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 205, in testEnv
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, env_snt),
AssertionError: Lists differ: [('fake-pre.d/success', 0, '')] != [('fake-pre.d/success', 2, 'PHASE=pre')]

First differing element 0:
('fake-pre.d/success', 0, '')
('fake-pre.d/success', 2, 'PHASE=pre')

- [('fake-pre.d/success', 0, '')]
?                         ^

+ [('fake-pre.d/success', 2, 'PHASE=pre')]
?                         ^   +++++++++


======================================================================
FAIL: testOrdering (__main__.TestHooksRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 194, in testOrdering
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}), expect)
AssertionError: Lists differ: [('fake-pre.d/00s0', 0, ''), ('fake-pre.d/10s1', 0, ''), ('fak[73 chars] '')] != [('fake-pre.d/00s0', 2, ''), ('fake-pre.d/10s1', 2, ''), ('fak[73 chars] '')]

First differing element 0:
('fake-pre.d/00s0', 0, '')
('fake-pre.d/00s0', 2, '')

- [('fake-pre.d/00s0', 0, ''),
?                      ^

+ [('fake-pre.d/00s0', 2, ''),
?                      ^

-  ('fake-pre.d/10s1', 0, ''),
?                      ^

+  ('fake-pre.d/10s1', 2, ''),
?                      ^

-  ('fake-pre.d/10sa', 0, ''),
?                      ^

+  ('fake-pre.d/10sa', 2, ''),
?                      ^

-  ('fake-pre.d/60sd', 0, ''),
?                      ^

+  ('fake-pre.d/60sd', 2, ''),
?                      ^

-  ('fake-pre.d/80sc', 0, '')]
?                      ^

+  ('fake-pre.d/80sc', 2, '')]
?                      ^


======================================================================
FAIL: testSymlink (__main__.TestHooksRunner)
Test running a symlink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/py/ganeti.hooks_unittest.py", line 148, in testSymlink
    self.assertEqual(self.hr.RunHooks(self.hpath, phase, {}),
AssertionError: Lists differ: [('fake-pre.d/success', 0, '')] != [('fake-pre.d/success', 2, '')]

First differing element 0:
('fake-pre.d/success', 0, '')
('fake-pre.d/success', 2, '')

- [('fake-pre.d/success', 0, '')]
?                         ^

+ [('fake-pre.d/success', 2, '')]
?                         ^

```

**Comment by iustin** [comment]
I've not looked at the code, but to me the `-` lines are the expected output, and the `+` lines are the actual output (since this is just a unified diff). So it expected zero, but gets instead exit code 2?

**Comment by mweinelt** [comment]
Not according to this:

https://github.com/ganeti/ganeti/blob/4d8c16a0739c93400471023b3cf9adf73a037b8f/test/py/ganeti.hooks_unittest.py#L142-L149

https://github.com/ganeti/ganeti/blob/4d8c16a0739c93400471023b3cf9adf73a037b8f/src/Ganeti/Constants.hs#L747

**Comment by iustin** [comment]
No you are right - as I said, I did not check the code. It does expect 2 (as `hkrSuccess`), but note that this is _not_ the exit code of the script, but rather an internal constant, see:

https://github.com/ganeti/ganeti/blob/4d8c16a0739c93400471023b3cf9adf73a037b8f/lib/backend.py#L5983-L5996

And the code in `utils/process.py`:

https://github.com/ganeti/ganeti/blob/4d8c16a0739c93400471023b3cf9adf73a037b8f/lib/utils/process.py#L738-L751

To me, this looks like a bona-fide failure in the script, which is then represented via the numerical value '2', which is quite confusing, indeed.

**Comment by thielema** [comment]
> Okay, this was due to no replacing shebangs everywhere properly. I'm progresing slowly.

Would you like to share how you fixed the Nix expression in order to get the shebang patch right?

**Comment by thielema** [comment]
On Tue, 28 Oct 2025, Martin Weinelt wrote:

> NixOS/nixpkgs#99222 is all I had. I've migrated my workloads to incus in the meantime, sorry.

Here is my attempt at packaging Ganeti for Nix:

https://github.com/thielema/ganeti/tree/nix

I re-use a Guix patch for removing version-specific links. I added custom 
packages for Python packages pydoctor and lunr. I stick to Python 3.11 
because this still provides 'asyncore'.

Remaining problems: Some tests fail. In the fixupPhase gzipping the 
manpages crashes. I find it alarming that gzip can crash, at all. I have 
no idea where and how it crashes. If I run the Nix build phases manually, 
there is no crash.


There is also an attempt to move Nix packaging to flakes and even newer 
Pandoc-3.8:
   https://github.com/thielema/ganeti/pull/7
