### ISSUE TITLE
Cluster Init failed:  start-stop-daemon: no matching processes found

### ISSUE THREAD

**Issue by pvsa** [ganeti/ganeti#1532]
See thread: https://groups.google.com/g/ganeti/c/ZQTkhZrBY3k?pli=1

phi...@pilarkto.net
12.11.2020, 19:28:05 (vor 7 Tagen) 
an ganeti
Hi,

first: thank you all for stand the fight (againt python2 et.al.). Because there is no ganeti support anymore in gentoo - in special ganeti-3 - i installed ganeti-3 from source.
When i try to init a (standalone testing) cluster: 

gnt-cluster init -d hv-mgr3 - it says:

20-11-12 19:03:32,810: gnt-cluster init pid=29389 cli:1252 DEBUG Command line: gnt-cluster init -d hv-mgr3.trust
2020-11-12 19:03:32,810: gnt-cluster init pid=29389 node:94 INFO Using PycURL PycURL/7.43.0.3 libcurl/7.72.0 OpenSSL/1.1.1g zlib/1.2.11 zstd/1.4.4 nghttp2/1.41.0
2020-11-12 19:03:32,813: gnt-cluster init pid=29389 netutils:320 DEBUG Attempting to reach TCP port 1811 on target 10.0.0.30 with a timeout of 5 seconds
2020-11-12 19:03:35,871: gnt-cluster init pid=29389 process:221 INFO RunCmd vgs --noheadings --units m --nosuffix -o name,size
2020-11-12 19:03:35,900: gnt-cluster init pid=29389 bootstrap:607 DEBUG Stopping daemons (if any are running)
2020-11-12 19:03:35,900: gnt-cluster init pid=29389 process:221 INFO RunCmd /usr/local/lib/ganeti/daemon-util stop-all
2020-11-12 19:03:35,912: gnt-cluster init pid=29389 process:131 DEBUG Command '/usr/local/lib/ganeti/daemon-util stop-all' failed (exited with exit code 1); output:  * start-stop-daemon: no matching processes found

2020-11-12 19:03:35,912: gnt-cluster init pid=29389 cli:1259 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/local/share/ganeti/3.0/ganeti/cli.py", line 1255, in GenericMain
    result = func(options, args)
  File "/usr/local/share/ganeti/3.0/ganeti/rpc/node.py", line 144, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/share/ganeti/3.0/ganeti/client/gnt_cluster.py", line 349, in InitCluster
    ssh_key_bits=ssh_key_bits,
  File "/usr/local/share/ganeti/3.0/ganeti/bootstrap.py", line 612, in InitCluster
    (result.cmd, result.exit_code, result.output))
ganeti.errors.OpExecError: Could not stop daemons, command /usr/local/lib/ganeti/daemon-util stop-all had exitcode 1 and error ' * start-stop-daemon: no matching processes found
'
Failure: command execution error:
Could not stop daemons, command /usr/local/lib/ganeti/daemon-util stop-all had exitcode 1 and error ' * start-stop-daemon: no matching processes found

**Comment by pvsa** [comment]
diff  /usr/local/lib/ganeti/daemon-util_old /usr/local/lib/ganeti/daemon-util

OLD:
<   elif type -p start-stop-daemon >/dev/null; then
<     start-stop-daemon --stop --quiet --oknodo --retry 30 \
NEW:
>   elif [ -x "$(command -v start-stop-daemon >/dev/null)" ] && [ "$(pgrep "$name")" -ge 1 ]; then
>     start-stop-daemon --stop --quiet --retry 30 \

OLD:
<     _ignore_error killproc -p $pidfile $name
NEW:
>     _ignore_error pkill -f $name

OLD:
<     _ignore_error killproc \
<       -p $pidfile \
<       $daemonexec -HUP
NEW:
>     _ignore_error pkill \
>       -f $daemonexec -HUP

**Comment by saschalucas** [comment]
I'm just recording the [gentoo portage Ganeti git link](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/ganeti?id=b05155344b3a15fb088606a0d99a21bfb586ad8c) here. I think that there are workarounds/patches there, that are related to this issue. It is a good starting point, to figure out a general solution (patches are in the files/ dir).

**Comment by apoikos** [comment]
Apparently Gentoo's `start-stop-daemon` has diverged from Debian's to the extent that they don't support the same arguments anymore. Adopting the Gentoo patches will almost certainly break Ganeti on Debian + sysvinit, so we'll either need to do some magic in `daemon-util` to detect the s-s-d version (which needs to be done by someone actually using Gentoo), or leave it up to the porters to re-introduce a patched version of Ganeti to portage. My preference right now is towards the latter - I don't want to delay 3.0 for this and we can always add the fix to a stable release as long as it doesn't break other systems.

**Comment by saschalucas** [comment]
Agreed. It seems that `start-stop-daemon` does not have a common upstream? In Debian it belongs to the `dpkg` package. I have looked up in my old SLES rpm specs. There I'm shipping a binary blob for `start-stop-daemon` (a copy from the Debian package). SES11 provides an other version of `start-stop-daemon` via `sysvinit` package (not being compatible). Since SLES12 `start-stop-daemon` is missing.

**Comment by apoikos** [comment]
`start-stop-daemon` was originally written in and for Debian, as part of dpkg. Gentoo copied it over to OpenRC and at some point rewrote it from scratch (at which point it should probably have stopped being called `start-stop-daemon`).

And when I have to deal with things like these, it reminds me that systemd is actual progress :)

**Comment by iustin** [comment]
> And when I have to deal with things like these, it reminds me that systemd is actual progress :)

Well, this is offtopic, but yes, I agree that systemd is progress, and I think people in general agree, the problem is just it is doing too much.

If anything, I'm sad that systemd is not used more in Debian. On a stablebox, only the systemd daemons are marked "OK" in `systemd-analyze security`, and a few others medium or exposed, but most are unsafe.

**Comment by saschalucas** [comment]
> And when I have to deal with things like these, it reminds me that systemd is actual progress :)

In my eyes the greatest advantage with systemd is, that you can count on it to work on nearly any distro.

@pvsa In this case here, it would be interesting to know, how systemd is supported in Gentoo. Does it still default to openrc? Is systemd an usable option?

**Comment by pvsa** [comment]
Hi,  

Happy new year BTW 😉  
OpenRC is default in Gentoo, but also supporting systemd https://wiki.gentoo.org/wiki/Systemd(https://wiki.gentoo.org/wiki/Systemd#Preset_services).
Even if i never used it myself i guess it is usable.

Best Regards  

--  
Philipp von Strobl-Albeg  

Von: saschalucas <notifications@github.com>(mailto:notifications@github.com)
Antworten: ganeti/ganeti <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 31. Dezember 2020 at 14:14:36
An: ganeti/ganeti <ganeti@noreply.github.com>(mailto:ganeti@noreply.github.com)
CC: pvsa <philipp@pilarkto.net>(mailto:philipp@pilarkto.net), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Betreff: Re: [ganeti/ganeti] Cluster Init failed: start-stop-daemon: no matching processes found (#1532)

**Comment by zen2** [comment]
Hello all !

I'm using Ganeti on a gentoo cluster and I've struggle a lot to write init.d script for ganeti and so I've investigate a lot on daemon-util script.
Gentoo is not a conventional distribution since it's a meta-distribution. It let the choice to user to decide which kind of distribution you want/need. So there is no recommendation from Gentoo about openrc/systemd choice. And this choice need to be respected because it involve many system modifications even kernel ones.

It's right that start-stop daemon on gentoo is not the same than debian, related man pages are relevant.
For example, this is how I patch daemon util on my ganeti cluster (2.15.2):

Starting daemon:
```
DEBIAN:  start-stop-daemon --start --quiet --oknodo --pidfile $pidfile --startas $daemonexec --chuid $usergroup -- $args "$@"
GENTOO:  start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemonexec --user $usergroup --wait 300  -- $args "$@"
```

Stopping daemon:
```
start-stop-daemon --stop --signal 0 --quiet --pidfile $pidfile
start-stop-daemon --signal 0 --quiet --pidfile $pidfile
```
We can add a patch for this at gentoo level but since the way to lauch daemons can be different between systems I wonder if it could be more interesting to deport this command in a configuration file. Like it it would be easy to manage such modifications without have to patch a ganeti file. That will help porting ganeti to other init systems as others systems as freebsd.

**Comment by zen2** [comment]
By the way there is someting else that I've patched in daemon-util on gentoo. I don't remind actually how it is related accuratelly  to start-stop-daemon but I think it's related how start-stop-daemon manage pids and exit codes 
Actually all daemons are defined in $DAEMONS but that can bring problem because start_all and stop_all functions can generate errors trying to start/stop daemon not needed on a slave node.
So my patch simply add master daemons only if the node is a master while respecting launch orders.

**Comment by zen2** [comment]
There is a way to check if start-stop-daemon is openrc related:
```
$ start-stop-daemon --version
start-stop-daemon (OpenRC) 0.42.1 (Gentoo Linux)
```
