### ISSUE TITLE
Configuration upgrate to 2.2.0 failed

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#164]
Originally reported of Google Code with ID 108.

```
I tried to upgrade my test cluster to 2.2.0beta0 and got following:
                                                                                                     
"ConfigurationError: Cluster configuration version mismatch, got
2010000 instead of 2020000" masterd startup failed.

cfgupgrade fail with:

# /usr/lib/ganeti/tools/cfgupgrade -v 
cfgupgrade MUST be run on the master node. Is this the master node and
are ALL instances down?
y/[n]/?: y
2010-06-18 18:48:08,223: Found configuration version 2010000 (2.1.0)
2010-06-18 18:48:08,224: Writing configuration file to /var/lib/ganeti/config.data
2010-06-18 18:48:08,231: Testing the new config file...
Traceback (most recent call last):
  File "/usr/lib/ganeti/tools/cfgupgrade", line 206, in <module>
    main()
  File "/usr/lib/ganeti/tools/cfgupgrade", line 194, in main
    offline=True)
  File "/usr/lib/python2.6/site-packages/ganeti/config.py", line 155, in __init__
    self._OpenConfig()
  File "/usr/lib/python2.6/site-packages/ganeti/config.py", line 1216, in _OpenConfig
    _ValidateConfig(data)
  File "/usr/lib/python2.6/site-packages/ganeti/config.py", line 68, in _ValidateConfig
    constants.CONFIG_VERSION))
ganeti.errors.ConfigurationError: Cluster configuration version mismatch, got 2010000 instead of 2020000

```
Originally added on 2010-06-18 14:51:45 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed via:
commit a9221f098f860e1c285db2c942a87ba553e66e91
Author: Michael Hanselmann <hansmi@google.com>
Date:   Mon Jun 28 14:34:04 2010 +0200

    cfgupgrade: Add support for Ganeti 2.2
    
    Since configuration changes are now usually done in the configuration
    writer class, cfgupgrade's only task is to change the config version.
    This means we can easily support upgrading from Ganeti 2.0 and 2.1 to
    2.2.
    
    This patch also brings a couple of small cleanups.
    
    Signed-off-by: Michael Hanselmann <hansmi@google.com>
    Reviewed-by: Guido Trotter <ultrotter@google.com>

```
Originally added on 2010-07-29 20:44:59 +0000 UTC.

Added Labels: Type-Defect
Changed State: Fixed
Added to Milestone: Release2.2

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-10-22 08:57:08 +0000 UTC.

Changed State: Released
