### ISSUE TITLE
QMP communication sometimes fails during (nic?) hotplugging

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1649]
With the QA suite now running Hotplug tests I see occasional fails due to QMP communication errors while hotplugging disks or nics:

```
gnt-instance modify --net -1:modify,mac=aa:bb:cc:dd:ee:ff --hotplug --force kvm-test-instance02.staging.ganeti.org
Mon Jan 31 11:43:29 2022  - INFO: Trying to hotplug device...
Mon Jan 31 11:43:29 2022  - WARNING: Could not hotplug device: Error while executing backend function: kvm: QMP communication error (wrong server greeting
Mon Jan 31 11:43:29 2022  - INFO: Continuing execution..
Modified instance kvm-test-instance02.staging.ganeti.org
 - nic.mac/1 -> aa:bb:cc:dd:ee:ff
 - nic.link/1 -> virt-bridge
 - nic.mode/1 -> bridged
 - nic.vlan/1 ->
 - nic/1 -> hotplug:failed
Please don't forget that most parameters take effect only at the next (re)start of the instance initiated by ganeti; restarting from within the instance will not be enough.
```

This is what the noded log shows at that time:
```
2022-01-31 11:43:28,980: ganeti-noded pid=31182 INFO 192.168.1.3:35978 POST /hotplug_supported HTTP/1.1 200
2022-01-31 11:43:29,007: ganeti-noded pid=31183 INFO 192.168.1.3:35980 POST /bridges_exist HTTP/1.1 200
2022-01-31 11:43:29,037: ganeti-noded pid=31184 INFO RunCmd /usr/bin/kvm --help
2022-01-31 11:43:29,057: ganeti-noded pid=31184 INFO RunCmd /usr/bin/kvm -device '?'
2022-01-31 11:43:29,077: ganeti-noded pid=31184 INFO RunCmd /usr/lib/ganeti/kvm-ifup 'b'\''tap1'\'''
2022-01-31 11:43:29,102: ganeti-noded pid=31184 INFO Verifying hotplug command (retry 0): True
2022-01-31 11:43:29,102: ganeti-noded pid=31184 INFO Device nic-e86fb2d8-9595-444d has been correctly hot-plugged
2022-01-31 11:43:29,103: ganeti-noded pid=31184 INFO 192.168.1.3:35982 POST /hotplug_device HTTP/1.1 200
2022-01-31 11:43:29,130: ganeti-noded pid=31211 INFO 192.168.1.3:35984 POST /hooks_runner HTTP/1.1 200
2022-01-31 11:43:29,168: ganeti-noded pid=31212 INFO 192.168.1.3:35990 POST /hooks_runner HTTP/1.1 200
2022-01-31 11:43:29,823: ganeti-noded pid=31224 INFO 192.168.1.3:36014 POST /hotplug_supported HTTP/1.1 200
2022-01-31 11:43:29,849: ganeti-noded pid=31225 INFO 192.168.1.3:36016 POST /bridges_exist HTTP/1.1 200
2022-01-31 11:43:29,916: ganeti-noded pid=31226 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/3.1/ganeti/server/noded.py", line 189, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/3.1/ganeti/server/noded.py", line 660, in perspective_hotplug_device
    return backend.HotplugDevice(instance, action, dev_type, device, extra, seq)
  File "/usr/share/ganeti/3.1/ganeti/backend.py", line 3217, in HotplugDevice
    return fn(instance, dev_type, device, extra, seq)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/__init__.py", line 2354, in HotModDevice
    device.hvinfo = self.HotDelDevice(instance, dev_type, device, _, seq)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/__init__.py", line 181, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/__init__.py", line 2338, in HotDelDevice
    self._VerifyHotplugCommand(instance, kvm_devid, False)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/__init__.py", line 181, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/__init__.py", line 2234, in _VerifyHotplugCommand
    found = self.qmp.HasDevice(kvm_devid)
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/monitor.py", line 222, in wrapper
    mon.connect()
  File "/usr/share/ganeti/3.1/ganeti/hypervisor/hv_kvm/monitor.py", line 289, in connect
    raise errors.HypervisorError("kvm: QMP communication error (wrong"
ganeti.errors.HypervisorError: kvm: QMP communication error (wrong server greeting
2022-01-31 11:43:29,917: ganeti-noded pid=31226 INFO 192.168.1.3:36018 POST /hotplug_device HTTP/1.1 200
2022-01-31 11:43:29,945: ganeti-noded pid=31228 INFO 192.168.1.3:36020 POST /hooks_runner HTTP/1.1 200
2022-01-31 11:43:29,984: ganeti-noded pid=31229 INFO 192.168.1.3:36026 POST /hooks_runner HTTP/1.1 200
2022-02-01 17:36:46,142: ganeti-noded pid=32629 INFO 192.168.1.3:36032 POST /all_instances_info HTTP/1.1 200
```

I'll just leave that here for now, I have not yet done any investigation. This might actually only happen during NIC hotplugging, I need to add some more runs to provoke this kind of error.

Observed on Debian Bullseye.

**Comment by saschalucas** [comment]
With the following, one can trace QMP communication:
```bash
# after instance start
mv /var/run/ganeti/kvm-hypervisor/ctrl/<instance>.qmp /var/run/ganeti/kvm-hypervisor/ctrl/<instance>.qmp.orig
socat -t100 -v UNIX-LISTEN:/var/run/ganeti/kvm-hypervisor/ctrl/<instance>.qmp,mode=777,reuseaddr,fork UNIX-CONNECT:/var/run/ganeti/kvm-hypervisor/ctrl/<instance>.qmp.orig
```
I don't know if it's possible to integrate this into QA-suite and if it would help in this case?

**Comment by rbott** [comment]
I have some additional information:

* it affects at least Debian Buster and Bullseye
* it only happens during NIC hoptlugging (if at all), never with disk hotplugging
* it happens during adding or removing

> 
> I don't know if it's possible to integrate this into QA-suite and if it would help in this case?

That is probably not very easy to implement. However, I will try to setup a test system and remove/add NICs in a loop. As it only occurs sometimes, I will probably hit the problem sooner or later :-)

**Comment by saschalucas** [comment]
Thanks, @rbott for your investigation. According to the [QMP Reference](https://qemu-project.gitlab.io/qemu/interop/qemu-qmp-ref.html#qapidoc-2278) `device_del` is asynchronous. The best way would be, to wait for an event. However Ganeti currently can not process QMP events, and decided to skip thous messages in response to QMP commands: https://github.com/ganeti/ganeti/blob/7382df3b1494b1247cd8767d1e740f13f46b729a/lib/hypervisor/hv_kvm/monitor.py#L452-L454

The only exception, where events are not skipped is in the connection phase. It sounds reasonable, to also skip events there (as you have done with your modification).

Probably this fire-and-forget strategy of sending QMP commands for hot-remove is the best we can get ATM?
