### ISSUE TITLE
Rapi node role change

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#174]
Originally reported of Google Code with ID 118.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
2.6.1

<b>What steps will reproduce the problem?</b>
change the role name for a node. Can't seem to change the node role.



<b>What is the expected output? What do you see instead?</b>
I expect a job id but I get

=> {"code"=>400, "explain"=>"Bad request syntax or unsupported method", "message"=>"Invalid body contents, not a string"}

<b>Please provide any additional information below.</b>

I'm sending the PUT request as follow /2/nodes/nodename/role?role=master-candidate&force=0

Also tryed /2/nodes/nodename/role?master-candidate=1&force=0

```
Originally added on 2010-08-18 18:29:07 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
As the message error says, the string must be put into the body of the request, not as the "role" parameter. http://ganeti-doc.googlecode.com/svn/ganeti-2.1/html/rapi.html#nodes-node-name-role agrees with this.

Can you try and see if that works for you?

regards,
iustin
```
Originally added on 2010-08-18 18:57:09 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
At this point, I tried to send it into the body as specified, but I get an end of file error of the http library


response_body = send_request("PUT", "/2/nodes/nodename/role","master-candidate")

EOFError: end of file reached



```
Originally added on 2010-08-19 06:46:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Did some more diggining

2010-08-19 12:10:54,384: ganeti-rapi pid=11447 ERROR Error while handling the PUT request
Traceback (most recent call last):
  File "/usr/local/sbin/ganeti-rapi", line 169, in HandleRequest
    result = ctx.handler_fn()
  File "/usr/local/lib/python2.6/dist-packages/ganeti/rapi/rlib2.py", line 347, in PUT
    raise http.HttpBadRequest("Invalid body contents, not a string")
HttpBadRequest
2010-08-19 12:10:54,386: ganeti-rapi pid=11447 INFO xxxxxxxx PUT /2/nodes/nodename/role HTTP/1.1 400
 File "/usr/local/lib/python2.6/dist-packages/ganeti/rapi/rlib2.py", line 347, in PUT
    raise http.HttpBadRequest("Invalid body contents, not a string")

    if not isinstance(self.req.request_body, basestring):
      raise http.HttpBadRequest("Invalid body contents, not a string")

It looks like it checks if the request is made to en instance, but is has to be to the node. (haven't checked the isInstance method yet)
```
Originally added on 2010-08-19 10:27:25 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
You're not passing a string. Encoding a string in JSON:

python -c 'import simplejson; print simplejson.dumps("master-candidate")'
"master-candidate"

To write this directly in code: "\"master-candidate\"". Also, if you're using Python, I suggest you to look into the included RAPI client.
```
Originally added on 2010-08-19 11:01:54 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I have located the issue.

Seems like this "bug" is related to http://code.google.com/p/ganeti/issues/detail?id=117

simplejson handles a form of non-strict json encoding . A simple string doesn't cut it here. The string needs to be escaped with quotes
```
Originally added on 2010-08-19 11:29:40 +0000 UTC.

Mentioned Issue with GoogleCode ID 117 has been migrated to GitHub with ID #173.

**Comment by Ganeti-Issues-Migrator** [comment]
```
As complimentary on this:

            body = "\"#{role}\""
            response_body = send_request("PUT", url, body)

This is in Ruby btw. When using JSON.generate("master") doesn't cut, because for valid json, the string has to be enclosed in an array.

But when sending this to the resource, you get an error because it expects a string.

This behavior should also be documented, because it might cause the same error for other json libraries that don't allow "non-strict" json formats 
```
Originally added on 2010-08-19 11:34:19 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Documented in the commit mentioned below. If this is still an issue, please reopen this bug.

commit 981e01684e3c2d2ce1d3f20432b6bd3af4741e89
Author: Michael Hanselmann <hansmi@google.com>
Date:   Fri Aug 20 15:13:11 2010 +0200

    Document non-standard usage of JSON in RAPI
    
    This was requested in issue 118.
    
    Signed-off-by: Michael Hanselmann <hansmi@google.com>
    Reviewed-by: Iustin Pop <iustin@google.com>

http://git.ganeti.org/?p=ganeti.git;a=commit;h=981e01684e3c2
```
Originally added on 2010-08-20 14:22:53 +0000 UTC.

Mentioned Issue with GoogleCode ID 118 has been migrated to GitHub with ID #174.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-10-22 08:57:08 +0000 UTC.

Changed State: Released
