### ISSUE TITLE
Ganeti unit test failures with OpenSSH 9.8p1

### ISSUE THREAD

**Issue by RJSent** [ganeti/ganeti#1752]
Hi all,

With the [release](https://www.openssh.com/releasenotes.html) of OpenSSH 9.8p1, DSA support is disabled by default at compile time and will be fully removed sometime in 2025.

Ganeti still uses DSA keys in its test suite, causing tests to fail when Ganeti is built with OpenSSH 9.8p1.

I think either the DSA part of the tests should be removed or disabled when building with OpenSSH >= 9.8p1.

Related issues: #292 and #1209.

```
======================================================================
ERROR: testUpdate (__main__.TestUpdateSshRoot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/gntbuild.x6FE8Fb2/./test/py/ganeti.tools.prepare_node_join_unittest.py", line 238, in testUpdate
    prepare_node_join.UpdateSshRoot(data, False,
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/gntbuild.x6FE8Fb2/ganeti/tools/prepare_node_join.py", line 179, in UpdateSshRoot
    common.GenerateRootSshKeys(ssh_key_type, ssh_key_bits, error_fn=JoinError,
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/gntbuild.x6FE8Fb2/ganeti/tools/common.py", line 221, in GenerateRootSshKeys
    ssh.InitSSHSetup(key_type, key_bits, error_fn=error_fn,
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/gntbuild.x6FE8Fb2/ganeti/ssh.py", line 708, in InitSSHSetup
    raise error_fn("Could not generate ssh keypair, error %s" %
ganeti.tools.prepare_node_join.JoinError: Could not generate ssh keypair, error unknown key type dsa
```

**Comment by codefritzel** [comment]
Hi @RJSent,
I have created a quick fix under #1754.

Can you please test the fix in your environment?:
`PYTHONPATH=: test/py/ganeti.tools.prepare_node_join_unittest.py`

**Comment by attila-lendvai** [comment]
> Can you please test the fix in your environment?:
> `PYTHONPATH=: test/py/ganeti.tools.prepare_node_join_unittest.py`

this works, but there's another test that fails:

```
$ PYTHONPATH=: test/py/ganeti.tools.prepare_node_join_unittest.py
Running ganeti.tools.prepare_node_join_unittest.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.233s

OK
```
```
$ PYTHONPATH=: test/py/ganeti.ssh_unittest.py 
Running ganeti.ssh_unittest.py
EE.....................
======================================================================
ERROR: testNewKeysOverrideOldKeys (__main__.TestGetUserFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/source/test/py/ganeti.ssh_unittest.py", line 477, in testNewKeysOverrideOldKeys
    ssh.InitSSHSetup("dsa", 1024, _homedir_fn=self._GetTempHomedir)
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/source/ganeti/ssh.py", line 708, in InitSSHSetup
    raise error_fn("Could not generate ssh keypair, error %s" %
ganeti.errors.OpPrereqError: Could not generate ssh keypair, error unknown key type dsa


======================================================================
ERROR: testSuffix (__main__.TestGetUserFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/source/test/py/ganeti.ssh_unittest.py", line 483, in testSuffix
    ssh.InitSSHSetup("dsa", 1024, _homedir_fn=self._GetTempHomedir,
  File "/tmp/guix-build-ganeti-3.0.2.drv-0/source/ganeti/ssh.py", line 708, in InitSSHSetup
    raise error_fn("Could not generate ssh keypair, error %s" %
ganeti.errors.OpPrereqError: Could not generate ssh keypair, error unknown key type dsa


----------------------------------------------------------------------
Ran 23 tests in 0.074s

FAILED (errors=2)
$
```

**Comment by saschalucas** [comment]
> @codefritzel yep, this works, but there's another test that fails:
> ```

Thanks @attila-lendvai. Needs a second try ...

**Comment by attila-lendvai** [comment]
i can confirm: `PYTHONPATH=: test/py/ganeti.ssh_unittest.py` runs fine with the patch.

sidenote: the guix package failed to build due to a spurious failure of `PYTHONPATH=: test/py/ganeti.utils.process_unittest.py`, but i cannot reproduce it. i'm waiting for a new build to finish.
