### ISSUE TITLE
gnt-backup exits with error in finalization task when using CIFS

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#210]
Originally reported of Google Code with ID 154.

```
Cluster: "gnt-cluster (ganeti v2.4.1) 2.4.1"
on 2 Debian Lenny nodes running KVM only instances.

<b>What steps will reproduce the problem?</b>
1. mount a CIFS filesystem under /srv/ganeti/export 
2. Use an OS export script like this:

#CUSTOM IMAGE EXPORT SCRIPT
set -e

. common.sh

#MCM: Executing a full raw backup of the device using dd making a file-disk-image.
if [ ! -b $blockdev ]; then
        echo "ERROR: ${blockdev} is not a Block Device."
        cleanup
        exit 1
fi
dd if=${blockdev} bs=512
EXIT_STATUS="$?"

# execute cleanups
cleanup
trap - EXIT

exit ${EXIT_STATUS}

3. run gnt-backup export -n node2 instance.name

I'm expecting the backup is done correctly but instead I get this output:

Fri Apr  8 12:50:55 2011 Shutting down instance vmbktest.
Fri Apr  8 12:51:06 2011 Creating a snapshot of disk/0 on node deborder02
Fri Apr  8 12:51:06 2011 Starting instance vmbktest
Fri Apr  8 12:51:06 2011 Exporting snapshot/0 from deborder02 to deborder02
Fri Apr  8 12:51:10 2011 snapshot/0 is now listening, starting export
Fri Apr  8 12:51:12 2011 snapshot/0 is receiving data on deborder02
Fri Apr  8 12:51:12 2011 snapshot/0 is sending data on deborder02
Fri Apr  8 12:51:17 2011 snapshot/0 sent 95M, 15.2 MiB/s
Fri Apr  8 12:52:13 2011 snapshot/0 finished receiving data
Fri Apr  8 12:52:13 2011 snapshot/0 finished sending data
Fri Apr  8 12:52:13 2011 Removing snapshot of disk/0 on node deborder02
Fri Apr  8 12:52:13 2011 Finalizing export on deborder02
Fri Apr  8 12:52:15 2011  - WARNING: Could not finalize export for instance vmbktest.or.lan on node deborder02: Error while executing backend function: [Errno 95] Operation not supported
Failure: command execution error:
Export failed, errors in export finalization

Note: into the node log i found these lines:
2011-04-08 12:52:15,317: ganeti-noded pid=4926 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/ganeti/server/noded.py", line 152, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/local/lib/python2.5/site-packages/ganeti/server/noded.py", line 428, in perspective_finalize_export
    return backend.FinalizeExport(instance, snap_disks)
  File "/usr/local/lib/python2.5/site-packages/ganeti/backend.py", line 2309, in FinalizeExport
    data=config.Dumps())
  File "/usr/local/lib/python2.5/site-packages/ganeti/utils/io.py", line 143, in WriteFile
    os.rename(new_name, file_name)
OSError: [Errno 95] Operation not supported
2011-04-08 12:52:15,319: ganeti-noded pid=4926 INFO 10.6.128.132:53061 PUT /finalize_export HTTP/1.1 200
2011-04-08 12:52:15,406: ganeti-noded pid=4927 INFO 10.6.128.132:53062 PUT /jobqueue_update HTTP/1.1 200

I tried to check if it was a python issue using this procedure:
1. I launched "python" and I typed the following commands:

import os
os.rename("/srv/ganeti/export/vmbktest.or.lan.new", "/srv/ganeti/export/vmbktest.or.lan") 

..both of them are directories and the command worked as expected.
```
Originally added on 2011-04-08 11:10:40 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
It doesn't break on renaming a directory, but when renaming an open temporary file over a potentially existing file. You can use the following command to test this case:

python -c 'from ganeti import utils; utils.WriteFile("/srv/ganeti/export/renametest", data="test")'

Which software do you use as a CIFS server?
```
Originally added on 2011-04-08 12:34:53 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi!
Thanks a lot for the prompt answer! ^^
I don't have access to the servers right now, but I'm quite sure that the
server is a Windows 2008 R2.

Is it possible to check if the file exists (and maybe remove it) before
create the temporary file?
```
Originally added on 2011-04-08 13:53:36 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The issue isn't the temporary file. It is created with a unique name (mkstemp(3) semantics), written to, and then renamed over the existing file. POSIX rename(2) is atomic.

Could you please, in addition to the command I already gave, run the Python script below and give us the output? Make sure to change the current directory to /srv/ganeti/export before running it. Leave the script as it is for a first run, then change the “variant” variable to 1 and run it again. Variant 0 tests closing the file after renaming, variant 1 tests closing the file before renaming.

---------------------------------------
import os
variant = 0
print 40 * "-"
print "cwd = %s" % os.getcwd()
print "variant = %s" % variant
targname = "rentest230535"
fname = "%s.tmp" % targname
for i in [fname, targname]:
  if os.path.exists(i):
    os.unlink(i)
fd = os.open(fname, os.O_RDWR | os.O_CREAT | os.O_EXCL, 0600)
print "fd = %s" % fd
print "write", os.write(fd, "Hello World\n")
print "fsync", os.fsync(fd)
if variant == 0:
  print "close", os.close(fd)
os.rename(fname, targname)
for i in [fname, targname]:
  print "stat(%s) =" % i,
  try:
    print os.stat(i)
  except Exception, err:
    print err
if variant == 1:
  print "close", os.close(fd)
---------------------------------------
```
Originally added on 2011-04-08 15:02:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Guys, you're really awesome!
Unfortunately, I can't access to the servers until monday. :(
I will post you the output of this script as soon as I can.

Thanks again! ^^
```
Originally added on 2011-04-08 18:03:47 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ok, Just ran it on node 01, here's the outputs:

----------------------------------------
cwd = /srv/ganeti/export
variant = 0
fd = 3
write 12
fsync None
close None
stat(rentest230535.tmp) = [Errno 2] No such file or directory:
'rentest230535.tmp'
stat(rentest230535) = (33261, 4, 19L, 1, 0, 0, 12, 1302505527, 1302505702,
1302505702)

----------------------------------------
cwd = /srv/ganeti/export
variant = 1
fd = 3
write 12
fsync None
Traceback (most recent call last):
  File "/tmp/test.py", line 17, in <module>
    os.rename(fname, targname)
OSError: [Errno 95] Operation not supported

-- -- -- -- -- -- -- -- -- -- -- -- --

Then I ran it on node 02 and I got this:

----------------------------------------
cwd = /srv/ganeti/export
variant = 0
fd = 3
write 12
fsync None
close None
stat(rentest230535.tmp) = [Errno 2] No such file or directory:
'rentest230535.tmp'
stat(rentest230535) = (33261, 30, 19L, 1, 0, 0, 12, 1302505691, 1302505865,
1302505865)

----------------------------------------
cwd = /srv/ganeti/export
variant = 1
fd = 3
write 12
fsync None
Traceback (most recent call last):
  File "/tmp/test.py", line 17, in <module>
    os.rename(fname, targname)
OSError: [Errno 95] Operation not supported
```
Originally added on 2011-04-11 07:11:29 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you for the tests! I have prepared and sent for review a patch changing the code to close the file before renaming it. It's on the ganeti-devel mailing list (http://groups.google.com/group/ganeti-devel/browse_thread/thread/f07104489535bbd6).
```
Originally added on 2011-04-11 13:48:41 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you very much for the help!

Tomorrow I'll be at work for the whole day, so I'll have plenty of time to
apply the patch and test it on my production environment.
I will let you know if it will solve my issue as soon as I can.

Thanks again for the help. :)
```
Originally added on 2011-04-11 15:57:35 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi, I don't have "git" installed on my systems and it seems that the patch
command fails to apply these patches.
Can you send me them in standard diff format?

PS: excuse me but I think I just double-posted this..
```
Originally added on 2011-04-12 10:07:54 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Finally I was able to test the patch.
Well, it works flawlessly! :D

Thanks a lot! :)
```
Originally added on 2011-04-12 12:27:42 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Crap!.. It seems that I was blinded by the enthusiasm..
Actually the export operation ends without errors.. but it deletes the
backup.. :(
```
Originally added on 2011-04-12 12:38:49 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The code is supposed to remove the old backup (the whole directory) and then rename the new directory to the old name. Can you please elaborate a bit on what you mean with “deletes the backup”?
```
Originally added on 2011-04-13 11:44:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Well, it actually removes the old backup, then it tries to rename the new
backup but for some reason it fails (CIFS filesystem).
Then it removes the temporary directory (.new).
So, at the end of the operation I have no backups (old and new were
deleted).
```
Originally added on 2011-04-13 11:53:16 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ok, finally I figured it out.
The problem is that I have the CIFS filesystem mounted on both nodes.
So, after the finalization ganeti wants to remove the "old backups" that
lives on the other node and that have the same name.
This is a correct behavior when you don't have a shared backup directory..
but in my case it removes the just-made backup leaving me with an empty
directory.. :(

For now the solution is to use 2 different filesystems for each node.. but
it would be great if you could add a new cluster property in order to tell
ganeti that the backup directory is shared so he can avoid to remove the
backups from the other nodes. :)

Let me know.
```
Originally added on 2011-04-14 11:06:14 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I don't see much gain in that option - sure, if you want to send a patch, we'd welcome it.

In the meantime, simply mount or symlink a *subdirectory* of the shared filesytem on each node, instead of the root of the filesystem, and your problem will go away then.
```
Originally added on 2011-04-14 11:10:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I already did it and it works.
So this means the patch you gave me to solve my original issue works fine.

I guess that it could be useful to have the possibility to share all the
backups into a shared directory, so you can restore them from any node
without have to move the data.. maybe ganeti can already restore a backup
from any host to any host?

BTW: Thanks for the support.
```
Originally added on 2011-04-14 11:32:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes, it can. Have a look at the “--src-node” and “--src-dir” options for “gnt-backup import” (man gnt-backup).
```
Originally added on 2011-04-14 12:33:09 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
Cool! :)
Thanks a lot.
```
Originally added on 2011-04-14 12:55:31 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Just an FYI:

I ran into the same problem but using NFS. I solved it by creating a subdirectory for each node like Iustin mentioned above. Perhaps I should write a blog post about this sort of setup :)
```
Originally added on 2011-04-14 15:54:49 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
It's a good idea.
I think it's quite ordinary try to use a shared external filesystem for the
backups.  A mention into the documentation about this behavior could be
indeed useful.
```
Originally added on 2011-04-15 06:46:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Migrate old issues from 'fixed' to 'released'.
```
Originally added on 2012-10-22 09:16:17 +0000 UTC.

Changed State: Released
