### ISSUE TITLE
SO_PEERCRED missing in some versions of python

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#247]
Originally reported of Google Code with ID 191.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
gnt-cluster (ganeti v2.5.0beta2) 2.5.0~beta2

<b>What distribution are you using?</b>
Funtoo Linux (current branch, amd64)

<b>What steps will reproduce the problem?</b>
1. upgrade Linux kernel to 3.0
2. rebuild Python
3. run "gnt-cluster info"

<b>What is the expected output? What do you see instead?</b>
command output:
pugyah ~ # gnt-cluster info -d
2011-08-25 14:35:49,582: gnt-cluster info pid=19101 cli:2017 INFO run with arguments '-d'
Traceback (most recent call last):
  File "/usr/sbin/gnt-cluster", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib64/python2.7/site-packages/ganeti/client/gnt_cluster.py", line 1371, in Main
    aliases=aliases)
  File "/usr/lib64/python2.7/site-packages/ganeti/cli.py", line 2022, in GenericMain
    result = func(options, args)
  File "/usr/lib64/python2.7/site-packages/ganeti/client/gnt_cluster.py", line 307, in ShowClusterConfig
    result = cl.QueryClusterInfo()
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 546, in QueryClusterInfo
    return self.CallMethod(REQ_QUERY_CLUSTER_INFO, ())
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 443, in CallMethod
    version=constants.LUXI_VERSION)
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 358, in CallLuxiMethod
    response_msg = transport_cb(request_msg)
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 427, in _SendMethodCall
    return self.transport.Call(data)
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 257, in Call
    return self.Recv()
  File "/usr/lib64/python2.7/site-packages/ganeti/luxi.py", line 235, in Recv
    data = self.socket.recv(4096)
socket.error: [Errno 104] Connection reset by peer

log:
2011-08-25T14:56:50.517577+09:00 pugyah ganeti-masterd[9018]: (MainThread) ERROR Error while handling asyncore request#012Traceback (most recent call last):#012
  File "/usr/lib64/python2.7/asyncore.py", line 104, in readwrite#012
    obj.handle_read_event()#012  File "/usr/lib64/python2.7/asyncore.py", line 433, in handle_read_event#012
    self.handle_accept()#012  File "/usr/lib64/python2.7/site-packages/ganeti/daemon.py", line 140, in handle_accept#012
    client_address = netutils.GetSocketCredentials(connected_socket)#012
  File "/usr/lib64/python2.7/site-packages/ganeti/netutils.py", line 95, in GetSocketCredentials#012
    peercred = sock.getsockopt(socket.SOL_SOCKET, IN.SO_PEERCRED,#012AttributeError: 'module' object has no attribute 'SO_PEERCRED'

<b>Please provide any additional information below.</b>
pugyah ~ # python -V
Python 2.7.1
```
Originally added on 2011-08-25 06:02:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Linux 3 still has SO_PEERCRED (http://git.kernel.org/?p=linux/kernel/git/torvalds/linux.git;a=blob;f=include/asm-generic/socket.h). It seems you rebuilt your Python against a libc which doesn't export it. Why did you not use the Python provided by your distribution? You need to investigate why the constant is not exported by the “IN” module.
```
Originally added on 2011-08-25 13:12:51 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you for your reply.
I use Python which distribution provides (Funtoo Linux has a build-based package system). I understood that this was not a problem of Ganeti. I intend to report this issue in Funtoo community.
```
Originally added on 2011-08-30 18:39:34 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I'm sorry. There was a problem in the combination of the specific version of kernel and Python (https://bugs.gentoo.org/show_bug.cgi?id=374579).
Please close this issue.
```
Originally added on 2011-09-17 10:05:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2011-09-20 11:30:32 +0000 UTC.

Changed State: Invalid

**Comment by Ganeti-Issues-Migrator** [comment]
```
This happens on a default install of Ubuntu Server 13.04 and the distro supplied ganeti-2.5.2.

The distro supplied kernel is:
Linux fs1 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:16:28 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

The distro supplied python is:
Python 2.7.4 (default, Apr 19 2013, 18:28:01) 

And the error with any ganeti command is:
    peercred = sock.getsockopt(socket.SOL_SOCKET, IN.SO_PEERCRED,
AttributeError: 'module' object has no attribute 'SO_PEERCRED'


```
Originally added on 2013-04-29 23:30:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Perhaps we can work around it by catching the AttributeError and defining SO_PEERCRED to the right number.

Thanks,
Guido

```
Originally added on 2013-04-30 06:47:30 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Issue 463 has been merged into this issue.
```
Originally added on 2013-05-15 11:23:11 +0000 UTC.

Mentioned Issue with GoogleCode ID 463 has been migrated to GitHub with ID #519.

**Comment by Ganeti-Issues-Migrator** [comment]
```
From the list:

Just adding some more data for other users. This is the top Google result for "ganeti ubuntu 13.04".

Replacing SO_PEERCRED in lib/netutils.py with the value 17 makes that problem go away.

A bigger problem is that Ubuntu 13.04 uses drbd 8.4.2, which isn't currently supported by ganeti.
```
Originally added on 2013-05-21 14:27:15 +0000 UTC.

Added Labels: Priority-Medium
Changed State: Accepted
Added to Milestone: Release2.7

**Comment by Ganeti-Issues-Migrator** [comment]
```
(we should workaround this, for rc2)
```
Originally added on 2013-05-21 14:27:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I'll handle this one.
```
Originally added on 2013-05-22 13:46:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I'll handle this one.
```
Originally added on 2013-05-22 13:46:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 069a4bcf5dec3ee2038dfaf4aba0e75156ec5019
Author: Guido Trotter <ultrotter@google.com>
Date:   Wed May 22 14:57:51 2013 +0200

    Workaround missing SO_PEERCRED
    
    This bug happens in a few new distributions, so we workaround it by
    defining the constant ourselves, if it's missing.
    
    Signed-off-by: Guido Trotter <ultrotter@google.com>
    Reviewed-by: Thomas Thrainer <thomasth@google.com>

```
Originally added on 2013-05-22 14:54:21 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit a3e964cf54dd8c5aa1c0ae9cee6fd20a2ada6ff3
Author: Klaus Aehlig <aehlig@google.com>
Date:   Wed Jun 26 12:49:10 2013 +0200

    Disable pylint E1101 on hypothetical import
    
    In some versions of python the module IN does not provide
    the constant SO_PEERCRED (issue 191). So in commit 069a4b
    a work around was added. However, this work around still
    leaves lint warnings when working with those versions of
    python. So disable this warning during the work around,
    so that users of these python versions can still develop
    and contribute to ganeti.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Thomas Thrainer <thomasth@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>

```
Originally added on 2013-06-26 11:02:41 +0000 UTC.

Mentioned Issue with GoogleCode ID 191 has been migrated to GitHub with ID #247.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-07-03 04:39:25 +0000 UTC.

Changed State: Released
