### ISSUE TITLE
sudo escalation and non root ssh

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#253]
Originally reported of Google Code with ID 197.

```
Hi,

I'm evaluating ganeti for use in a PCI-DSS environment (currently ganeti-2.4.2 from squeeze-backports). One point in PCI-DSS is: 8.5.8 Do not use group, shared, or generic accounts and passwords. So the account "root" is forbidden.

I already found the patch[1]. But had no luck with it. It does not apply without errors and it seems incomplete:

[1] http://markmail.org/message/2elzvavwuyeipmln

# gnt-instance console XXXX.domain.tld 
Traceback (most recent call last):
  File "/usr/sbin/gnt-instance", line 19, in <module>
    sys.exit(main.Main())
  File "/usr/lib/pymodules/python2.6/ganeti/client/gnt_instance.py", line 1516, in Main
    override={"tag_type": constants.TAG_INSTANCE})
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 1932, in GenericMain
    result = func(options, args)
  File "/usr/lib/pymodules/python2.6/ganeti/client/gnt_instance.py", line 917, in ConnectToInstanceConsole
    opts.show_command, cluster_name)
  File "/usr/lib/pymodules/python2.6/ganeti/client/gnt_instance.py", line 950, in _DoConsole
    batch=True, quiet=False, tty=True)
TypeError: BuildCmd() takes at least 5 non-keyword arguments (4 given)

So my wish is: have non root ssh and an escalation command implemented in future ganeti versions.

TIA, Sascha.
```
Originally added on 2011-09-26 12:23:45 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Since Ganeti is a server management application, instead of a generic end-user application, we will need root permissions anyway; while the sudo method will reduce the permissions, Ganeti will still need some critical system permissions, so I'm not sure if root can be avoided entirely (and just use sudo always).

That said, we would like to move into this direction, but it will be a while…
```
Originally added on 2012-07-19 14:44:35 +0000 UTC.

Added Labels: Type-Enhancement Component-node
Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
we passed the certification with a shell wrapper around $SSH and $SCP in constants.py.

the main goal of PCI-DSS is auditability. therefore shared accounts (root) are forbidden. removeing/reduceing permissions is a side benefit.

finaly, thanks for accepting this issue. would make life a bit easier.
```
Originally added on 2012-07-19 20:46:25 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-11-29 09:22:36 +0000 UTC.

Added Labels: Priority-Medium
Removed Labels: Component-node
Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2016-01-07 15:52:56 +0000 UTC.

**Comment by ge-fa** [comment]
@saschalucas I'm still, mind to reopen?

**Comment by saschalucas** [comment]
Hi @ge-fa,

of cause I'll reopen, if there is still interest in this feature.

Thanks, Sascha.
