### ISSUE TITLE
frequent crashes of ganeti-masterd and frequent failiures to restart it due to errors with the job queue.

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#259]
Originally reported of Google Code with ID 203.

```
vhost1 queue # gnt-cluster --version
gnt-cluster (ganeti v2.4.4) 2.4.4
vhost1 queue # gnt-cluster version  
Software version: 2.4.4
Internode protocol: 2040000
Configuration format: 2040000
OS api version: 20
Export interface: 0
vhost1 queue # 


Running Gentoo and python2.7

The problem does not happen all the time, and not the exact same way either.
The most common problem now is:
python2.7: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
And often, this also happens, of which the solution is to clear/archive the queue:

2011-10-26 17:31:18,642: ganeti-masterd pid=32343/ClientReq13 INFO Received instance query request for ['build0.internal']
python2.7: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
2011-10-26 17:33:05,088: ganeti-masterd pid=839/MainThread INFO ganeti-masterd daemon startup
2011-10-26 17:33:05,089: ganeti-masterd pid=839/MainThread INFO Using PycURL libcurl/7.20.0 GnuTLS/2.10.4 zlib/1.2.5
2011-10-26 17:33:05,110: ganeti-masterd pid=839/MainThread INFO Inspecting job queue
2011-10-26 17:33:05,112: ganeti-masterd pid=839/MainThread INFO Job queue inspection: 0/2 (33.3 %)
2011-10-26 17:33:05,113: ganeti-masterd pid=839/MainThread INFO Job queue inspection: 2/2 (100.0 %)
2011-10-26 17:33:05,114: ganeti-masterd pid=839/MainThread WARNING Unfinished job 30502 found: <ganeti.jqueue._QueuedJob id=30502 ops=TAGS_SET at 0x756ed0>
Traceback (most recent call last):
  File "/usr/sbin/ganeti-masterd", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib64/python2.7/site-packages/ganeti/server/masterd.py", line 653, in Main
    ExecMasterd, multithreaded=True)
  File "/usr/lib64/python2.7/site-packages/ganeti/daemon.py", line 707, in GenericMain
    exec_fn(options, args, prep_results)
  File "/usr/lib64/python2.7/site-packages/ganeti/server/masterd.py", line 628, in ExecMasterd
    master.setup_queue()
  File "/usr/lib64/python2.7/site-packages/ganeti/server/masterd.py", line 165, in setup_queue
    self.context = GanetiContext()
  File "/usr/lib64/python2.7/site-packages/ganeti/server/masterd.py", line 404, in __init__
    self.jobqueue = jqueue.JobQueue(self)
  File "/usr/lib64/python2.7/site-packages/ganeti/jqueue.py", line 1240, in __init__
    self._InspectQueue()
  File "/usr/lib64/python2.7/site-packages/ganeti/locking.py", line 72, in sync_function
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/ganeti/jqueue.py", line 1175, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/ganeti/jqueue.py", line 1293, in _InspectQueue
    self.UpdateJobUnlocked(job)
  File "/usr/lib64/python2.7/site-packages/ganeti/jqueue.py", line 1175, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/ganeti/jqueue.py", line 1785, in UpdateJobUnlocked
    assert (finalized ^ (job.end_timestamp is None))
AssertionError


```
Originally added on 2011-10-27 09:14:13 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This is fixed in Git and will be part of the next 2.4 release (2.4.5), to be released soon™. Since it's a one-line fix you can also modify your local installation.

http://git.ganeti.org/?p=ganeti.git;a=commitdiff;h=45df0793c6bc83001aa545fda95c1ad9a35d732f
```
Originally added on 2011-10-27 12:43:51 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
the restart og the masterd is indeed fixed, however:
2011-11-15 21:30:46,650: ganeti-masterd pid=13231/JobQueue3/Job42144 INFO - device disk/0: 100.00% done, 0s remaining (estimated)
2011-11-15 21:30:46,983: ganeti-masterd pid=13231/JobQueue3/Job42144 INFO - device disk/0: 100.00% done, 0s remaining (estimated)
2011-11-15 21:30:47,059: ganeti-masterd pid=13231/ClientReq4 INFO Received job poll request for 42144
2011-11-15 21:30:47,061: ganeti-masterd pid=13231/ClientReq8 INFO Received job poll request for 42144
2011-11-15 21:30:47,465: ganeti-masterd pid=13231/JobQueue3/Job42144 INFO Instance hlt-archive.internal's disks are in sync.
2011-11-15 21:30:47,899: ganeti-masterd pid=13231/JobQueue3/Job42144 INFO Remove logical volumes for 0
2011-11-15 21:30:47,988: ganeti-masterd pid=13231/ClientReq3 INFO Received job poll request for 42144
2011-11-15 21:30:47,991: ganeti-masterd pid=13231/ClientReq16 INFO Received job poll request for 42144
python2.7: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

Is something that keeps happen quite regularly.
```
Originally added on 2011-11-15 20:36:30 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
That is an issue with gcrypt, used by GnuTLS, used by PycURL/cURL, used by Ganeti. The gcrypt engine is not initialized properly for multithreaded environments, see [1]. You will have to upgrade to GnuTLS 2.12.x and potentially adjust cURL. It also shows up on other projects if you search for “_gcry_ath_mutex_lock assertion lock”. Please contact your distribution vendor about this issue.

Alternatively you can link cURL (the library, not the CLI program) against OpenSSL.

[1] http://git.savannah.gnu.org/gitweb/?p=gnutls.git;a=commit;h=fe1b3846c8c34a103da138e375f435f72fa042a6
```
Originally added on 2011-11-16 06:15:43 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Migrate old issues from 'fixed' to 'released'.
```
Originally added on 2012-10-22 09:16:17 +0000 UTC.

Changed State: Released
