### ISSUE TITLE
gnt-backup failing with errors

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#269]
Originally reported of Google Code with ID 213.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
 gnt-cluster --version 
gnt-cluster (ganeti v2.4.5) 2.4.5

 gnt-cluster version
Software version: 2.4.5
Internode protocol: 2040000
Configuration format: 2040000
OS api version: 20
Export interface: 0


<b>What distribution are you using?</b>

 uname -a
Linux pmc-node01 2.6.32-5-amd64 #1 SMP Mon Jan 9 20:49:59 UTC 2012 x86_64 GNU/Linux

Debian 6.0.3

<b>What steps will reproduce the problem?</b>
<b>1.</b>
 gnt-backup export -d  -n pmc-node01.milestoneip.com pmc-inst-03.milestoneip.com
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

i shows all these errors

2012-02-02 11:36:13,127: gnt-backup export pid=23099 cli:1934 INFO run with arguments '-d -n pmc-node01.milestoneip.com pmc-inst-03.milestoneip.com'
Thu Feb  2 11:36:13 2012 Shutting down instance pmc-inst-03.milestoneip.com
Thu Feb  2 11:36:41 2012 Creating a snapshot of disk/0 on node pmc-node01.milestoneip.com
Thu Feb  2 11:36:41 2012 Starting instance pmc-inst-03.milestoneip.com
Thu Feb  2 11:36:41 2012 Exporting snapshot/0 from pmc-node01.milestoneip.com to pmc-node01.milestoneip.com
Thu Feb  2 11:36:44 2012 snapshot/0 is now listening, starting export
Thu Feb  2 11:36:47 2012 snapshot/0 finished receiving data
Thu Feb  2 11:36:47 2012  - WARNING: export 'export-2012-02-02_11_36_46-NUWpqE' on pmc-node01.milestoneip.com failed: Exited with status 1
Thu Feb  2 11:36:47 2012 snapshot/0 failed to send data: Exited with status 1 (recent output: device-mapper: remove ioctl failed: Device or resource busy)
Thu Feb  2 11:36:47 2012 Removing snapshot of disk/0 on node pmc-node01.milestoneip.com
Thu Feb  2 11:36:47 2012  - WARNING: Could not remove snapshot for disk/0 from node pmc-node01.milestoneip.com: Can't lvremove: exited with exit code 5 -   Can't remove open logical volume "5df1a831-f62c-4415-b089-6be47f7ce2c8.disk0.snap"\n
Thu Feb  2 11:36:47 2012 Finalizing export on pmc-node01.milestoneip.com
Thu Feb  2 11:36:47 2012 Removing snapshot of disk/0 on node pmc-node01.milestoneip.com
Thu Feb  2 11:36:47 2012  - WARNING: Could not remove snapshot for disk/0 from node pmc-node01.milestoneip.com: Can't lvremove: exited with exit code 5 -   Can't remove open logical volume "5df1a831-f62c-4415-b089-6be47f7ce2c8.disk0.snap"\n
2012-02-02 11:36:47,659: gnt-backup export pid=23099 cli:1943 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 1939, in GenericMain
    result = func(options, args)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/client/gnt_backup.py", line 83, in ExportInstance
    SubmitOpCode(op, opts=opts)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 1734, in SubmitOpCode
    reporter=reporter)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 1715, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 1537, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/errors.py", line 448, in MaybeRaise
    raise errcls, args
OpExecError: Export failed, errors in disk export: disk(s) 0
Failure: command execution error:
Export failed, errors in disk export: disk(s) 0


<b>Please provide any additional information below.</b>

```
Originally added on 2012-02-02 11:39:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
got it sorted now 
```
Originally added on 2012-02-03 14:51:33 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Mind sharing what you did to resolve it?
```
Originally added on 2012-06-05 23:40:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```

well for me it turns out I was using the wrong partitioning scheme for my virtual servers. Have a look here http://notes.ceondo.com/ganeti/#link8 or here https://code.osuosl.org/projects/ganeti-image/wiki/Creating_OS_Images
```
Originally added on 2012-06-06 09:23:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-07-19 14:53:56 +0000 UTC.

Changed State: Invalid
