### ISSUE TITLE
Cannot create os

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#288]
Originally reported of Google Code with ID 232.

```
command ran:
gnt-instance add -t plain -o image+default -s 50g -B memory=4096M -n orval.sejo.be -H kvm:vnc_bind_address=127.0.0.1,kernel_path="" mysql.ironvista.com

What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
root@orval:~# gnt-cluster --version
gnt-cluster (ganeti v2.5.0) 2.5.0
root@orval:~# gnt-cluster version
Software version: 2.5.0
Internode protocol: 2050000
Configuration format: 2050000
OS api version: 20
Export interface: 0

<b>What distribution are you using?</b>
ubuntu 
<b>What steps will reproduce the problem?</b>
1. create an new instance

<b>What is the expected output? What do you see instead?</b>

Instance created

I see this: 
root@orval:~# gnt-instance add -t plain -o image+default -s 50g -B memory=4096M -n orval.sejo.be -H kvm:vnc_bind_address=127.0.0.1,kernel_path="" mysql.ironvista.com
Mon Apr 23 10:01:50 2012 * disk 0, vg data, name 1474d0a9-af4c-4174-ac52-494ee6c270b0.disk0
Mon Apr 23 10:01:50 2012 * creating instance disks...
Mon Apr 23 10:01:50 2012 adding instance mysql.ironvista.com to cluster config
Mon Apr 23 10:01:50 2012  - INFO: Waiting for instance mysql.ironvista.com to sync disks.
Mon Apr 23 10:01:50 2012  - INFO: Instance mysql.ironvista.com's disks are in sync.
Mon Apr 23 10:01:50 2012 * running the instance OS create scripts...
Failure: command execution error:
("Could not add os for instance mysql.ironvista.com on node orval.sejo.be: OS create script failed (exited with exit code 1), last lines in the log file:\n+ cleanup\n+ '[' 5 -gt 0 ']'\n+ LAST_ELEMENT=4\n++ seq 4 -1 0\n+ REVERSE_INDEXES='4\n3\n2\n1\n0'\n+ for i in '$REVERSE_INDEXES'\n+ sync\n+ for i in '$REVERSE_INDEXES'\n+ umount /tmp/tmp.s1LHLzPZdQ/boot\n+ for i in '$REVERSE_INDEXES'\n+ umount /tmp/tmp.s1LHLzPZdQ\n+ for i in '$REVERSE_INDEXES'\n+ rmdir /tmp/tmp.s1LHLzPZdQ\n+ for i in '$REVERSE_INDEXES'\n+ unmap_disk0 /dev/data/1474d0a9-af4c-4174-ac52-494ee6c270b0.disk0\n+ /sbin/kpartx -d -p- /dev/data/1474d0a9-af4c-4174-ac52-494ee6c270b0.disk0",)


in logging this;
2012-04-22 02:26:42,950: ganeti-masterd pid=19393/Jq16/Job146534 INFO Op 1/2: opcode QUERY(instance) waiting for locks
2012-04-22 02:26:57,260: ganeti-masterd pid=19393/Jq9/Job146533 ERROR Op 1/1: Caught exception in INSTANCE_CREATE(mysql.ironvista.com)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/ganeti/jqueue.py", line 1033, in _ExecOpCodeUnlocked
    timeout=timeout, priority=op.priority)
  File "/usr/lib/pymodules/python2.6/ganeti/jqueue.py", line 1309, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 377, in ExecOpCode
    priority)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 321, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 330, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 321, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 285, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/pymodules/python2.6/ganeti/mcpu.py", line 260, in _ExecLU
    result = self._ProcessResult(lu.Exec(self.Log))
  File "/usr/lib/pymodules/python2.6/ganeti/cmdlib.py", line 9050, in Exec
    " on node %s" % (instance, pnode_name))
  File "/usr/lib/pymodules/python2.6/ganeti/rpc.py", line 265, in Raise
    raise ec(*args) # pylint: disable=W0142
OpExecError: Could not add os for instance mysql.ironvista.com on node orval.sejo.be: OS create script failed (exited with exit code 1), last lines in the log file:
+ cleanup
+ '[' 5 -gt 0 ']'
+ LAST_ELEMENT=4
++ seq 4 -1 0
+ REVERSE_INDEXES='4
3
2
1
0'
+ for i in '$REVERSE_INDEXES'
+ sync
+ for i in '$REVERSE_INDEXES'
+ umount /tmp/tmp.AMpNMecwv5/boot
+ for i in '$REVERSE_INDEXES'
+ umount /tmp/tmp.AMpNMecwv5
+ for i in '$REVERSE_INDEXES'
+ rmdir /tmp/tmp.AMpNMecwv5
+ for i in '$REVERSE_INDEXES'
+ unmap_disk0 /dev/data/534ea5e3-2432-4280-a451-4f9ce8ecc6eb.disk0
+ /sbin/kpartx -d -p- /dev/data/534ea5e3-2432-4280-a451-4f9ce8ecc6eb.disk0
2012-04-22 02:26:57,266: ganeti-masterd pid=19393/Jq9/Job146533 INFO Finished job 146533, status = error
2012-04-22 02:26:57,333: ganeti-masterd pid=19393/Jq16/Job146534 INFO Op 2/2: opcode QUERY(node) waiting for locks


<b>Please provide any additional information below.</b>

```
Originally added on 2012-04-23 08:04:38 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
fixed by adding the full path for grub-setup in /etc/ganeti/instance-image/hooks/grub

```
Originally added on 2012-04-24 10:45:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hmm, what was the full path to grub-setup? The OS scripts should have the usual /sbin:/bin:/usr/sbin:/usr/bin, so I'm curious why it wasn't picked up.
```
Originally added on 2012-07-19 15:25:33 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This seems to be a bug in instance-image, rather than Ganeti.

Thanks,

Guido

```
Originally added on 2013-05-08 08:23:33 +0000 UTC.

Changed State: Invalid
