### ISSUE TITLE
Allow for non-standard ssh ports

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#291]
Originally reported of Google Code with ID 235.

```
What software version are you running? 

gnt-cluster (ganeti v2.4.5) 2.4.5
Software version: 2.4.5
Internode protocol: 2040000
Configuration format: 2040000
OS api version: 20
Export interface: 0

<b>What distribution are you using?</b>

Debian Squeeze

<b>What steps will reproduce the problem?</b>
1. Configure your sshd to listen on any port other than 22
2. do a gnt-node add

<b>What is the expected output? What do you see instead?</b>

I expect it to be able to setup the node. What I see instead is this:

WARNING -- 
Performing this operation is going to replace the ssh daemon keypair
on the target machine (thrush.riseup.net) with the ones of the current one
and grant full intra-cluster ssh root access to/from it

/usr/lib/python2.6/dist-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
Traceback (most recent call last):
  File "/usr/lib/ganeti/tools/setup-ssh", line 496, in <module>
    main()
  File "/usr/lib/ganeti/tools/setup-ssh", line 439, in main
    transport = paramiko.Transport((host, ssh_port))
  File "/usr/lib/pymodules/python2.6/paramiko/transport.py", line 296, in __init__
    sock.connect((hostname, port))
  File "<string>", line 1, in connect
socket.error: [Errno 111] Connection refused
Failure: command execution error:
Command '/usr/lib/ganeti/tools/setup-ssh myhost.example.com' failed with exit code 1; output ''

<b>Please provide any additional information below.</b>

My /etc/ssh/ssh_config has an option line that configures the port for this domain, it appears to not be honored.
```
Originally added on 2012-05-02 18:22:40 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
You can change DAEMONS_PORTS in lib/constants.py.

> My /etc/ssh/ssh_config has an option line that configures the port for this
> domain, it appears to not be honored.

This is used by the ssh command, not by Ganeti directly, so in this case it's not enough. I'm not sure how hard is changing that (Ganeti should be rewritten to call ssh).

Bernardo
```
Originally added on 2012-05-02 19:30:01 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
That works, but its a bit odd to have to edit that file. It means that when the OS distributed package is updated, I am going to need to make sure that file is kept up-to-date with my changes. Perhaps this could go into a configuration file in /etc/ganeti?
```
Originally added on 2012-05-08 15:23:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Bernardo: ganeti will not be rewritten to call SSH; we intentionally moved away from ssh, since it doesn't offer an API.

What we need here is simply an option to use a custom ssh port that we pass to paramiko.
```
Originally added on 2012-05-10 10:47:37 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-07-19 15:29:00 +0000 UTC.

Added Labels: Type-Enhancement

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:38:05 +0000 UTC.

Added Labels: SmallTask

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-10-07 13:26:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-11-12 13:09:55 +0000 UTC.

Changed State: Started

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed in patch series:

commit 3ff2cf5542715094ac62969abd793f85880e8cd4
Author: Petr Pudlak <pudlak@google.com>
Date:   Fri Nov 8 17:21:38 2013 +0100

    Design document for custom SSH ports
    
    See issue 235. It turned out the feature is a bit more complex than expected,
    hence this design doc.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>

commit f2152285738a2d88c2b9e816045a0edfd268d7f4
Author: Petr Pudlak <pudlak@google.com>
Date:   Thu Nov 14 15:31:23 2013 +0000

    Add "ndp/ssh_port" node group configuration parameter
    
    The parameter is added to Haskell sources, from which the corresponding
    Python code is generated.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit a9f33339b9ddf8787144e8a28a9d70922b5723f5
Author: Petr Pudlak <pudlak@google.com>
Date:   Tue Nov 12 15:28:40 2013 +0100

    Use custom SSH ports in node groups when working with nodes
    
    Calling `gnt-instance console` with a custom SSH port doesn't work yet.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 33ffda6c8752a772246ae730585794232dd42e46
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:26 2013 +0100

    Update unit tests for custom SSH ports
    
    The unit tests now include the configurations of SSH ports for node
    groups/nodes.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit c42be2c044383376c2ca608f307e0d5d29e6f872
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:27 2013 +0100

    Use configured SSH ports when connecting to a console
    
    This is accomplished by passing the corresponding node group to
    hv_*.py. Tests for hv_*.py that call GetInstanceConsole updated.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 651ce6a3d3083236580a71de0ca7096fd0715315
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:28 2013 +0100

    Use custom SSH ports for other operations
    
    In particular _copyfile_ and _renew-crypto_.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit ec7b6d639abbdc08a3b3dd852b363972f2d3fa8c
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:29 2013 +0100

    Update QA to test custom SSH ports
    
    This patch adds the `ssh-port` option. If set to a non-standard port,
    the QA script sets up the default node group with this port, and before
    running tests it adds `iptable` rules to all nodes so that the nodes
    see each other's SSH servers as running on this port.
    Their SSH configuration is _not_ changed and other machines see the
    nodes on 22 as before.
    
    The `iptable` rules are reset on each QA run, trying to preserve any
    existing rules (not created by the script) that might be present.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 836ce0c853b92275fbcace3cef607fc1584b04fc
Author: Petr Pudlak <pudlak@google.com>
Date:   Tue Nov 12 15:44:49 2013 +0100

    Include *ssh_port* in the man page
    
    Added to the other node parameters in ganeti.rst.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 8cd19becf5b8b666d9bfcf0007f32d4b05fe8c32
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:31 2013 +0100

    Update custom SSH ports config when downgrading to 2.10
    
    If SSH ports other than 22 are configured, abort the config downgrade,
    as the operation would certainly fail. Otherwise just remove
    _ndparams/ssh_port_ from the configuration.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 70e6a07e4d5d947f24d64f972e9af09f5c3e1637
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:32 2013 +0100

    Update NEWS with information about custom SSH ports
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit b337aeb4e587ffd8c93966746865c5f70afb3450
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:34 2013 +0100

    Export `NodeAdd` and `NodeRemove` from qa_node
    
    This is needed for testing SSH ports so that we can remove a node from
    a group, add it to a group with a custom SSH port, and then undo the
    change.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 02911a56c64935be344c5da2e3742c175a040716
Author: Petr Pudlak <pudlak@google.com>
Date:   Mon Nov 11 16:37:35 2013 +0100

    Add a simple QA test for a group with a custom SSH port
    
    The test is turned on by setting `"group-custom-ssh-port": true` in
    the config.
    
    Unlike `"ssh-port": ...` in "options", this is a single test that
    doesn't affect the rest of the tests.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 0808e9d58f50dab77b33a9cdac804e978b9a0eee
Author: Petr Pudlak <pudlak@google.com>
Date:   Thu Nov 14 10:31:34 2013 +0100

    Add NodeGroup to InstanceConsoleInfoParams
    
    Before, calls to `gnt-instance list -o console` with an instance on a
    node with a custom SSH port failed because of missing group
    configuration. This patch fixes the problem.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit a02dbfca0cae1b7028c888f045940d20d772ee83
Author: Petr Pudlak <pudlak@google.com>
Date:   Wed Nov 20 08:40:15 2013 +0100

    Add an IPv6 check for the QA test of custom SSH ports
    
    If any of the nodes involved would be reached through IPv6, the test is
    skipped. This is because the required testing setup using "iptables" is
    suiteble only for IPv4 and doesn't work for IPv6 connections.
    
    Signed-off-by: Petr Pudlak <pudlak@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>

```
Originally added on 2013-11-29 09:29:30 +0000 UTC.

Mentioned Issue with GoogleCode ID 235 has been migrated to GitHub with ID #291.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-09 15:48:19 +0000 UTC.

Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-04-28 09:06:47 +0000 UTC.

Changed State: Released
