### ISSUE TITLE
ganeti-watcher (2.5.1) Broken on CentOS 6.2

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#297]
Originally reported of Google Code with ID 241.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

[root@node-a cron.d]# gnt-cluster --version
gnt-cluster (ganeti v2.5.1) 2.5.1

[root@node-a cron.d]# gnt-cluster version
Software version: 2.5.1
Internode protocol: 2050000
Configuration format: 2050000
OS api version: 20
Export interface: 0

<b>What distribution are you using?</b>
 
CentOS release 6.2 (Final)

<b>What steps will reproduce the problem?</b>
1. Run ganeti-watcher
2. Look in /var/log/ganeti/watcher.log
3. Find the following:

2012-05-29 14:50:01,488: ganeti-watcher pid=2058 ERROR cURL uses unsupported SSL version 'NSS/3.13.1.0'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ganeti/watcher/__init__.py", line 794, in Main
    return fn(options)
  File "/usr/lib/python2.6/site-packages/ganeti/rapi/client.py", line 162, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ganeti/watcher/__init__.py", line 614, in _GlobalWatcher
    if not IsRapiResponding(constants.IP4_ADDRESS_LOCALHOST):
  File "/usr/lib/python2.6/site-packages/ganeti/watcher/__init__.py", line 336, in IsRapiResponding
    master_version = rapi_client.GetVersion()
  File "/usr/lib/python2.6/site-packages/ganeti/rapi/client.py", line 474, in GetVersion
    return self._SendRequest(HTTP_GET, "/version", None, None)
  File "/usr/lib/python2.6/site-packages/ganeti/rapi/client.py", line 403, in _SendRequest
    curl = self._CreateCurl()
  File "/usr/lib/python2.6/site-packages/ganeti/rapi/client.py", line 347, in _CreateCurl
    self._curl_config_fn(curl, self._logger)
  File "/usr/lib/python2.6/site-packages/ganeti/rapi/client.py", line 228, in _ConfigCurl
    sslver)
NotImplementedError: cURL uses unsupported SSL version 'NSS/3.13.1.0'


<b>What is the expected output? What do you see instead?</b>

Normal watcher output, similar to:

2012-05-29 14:35:01,615: ganeti-watcher pid=11653 INFO Watcher for node group '3a48a7d1-4dfb-4d95-a42a-50dd5cc8788d'

<b>Please provide any additional information below.</b>
```
Originally added on 2012-05-29 18:53:10 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Suggested fix from Eric Rostetter (quoted below):

It appears the problem is with RHEL/CentOS combined with
/usr/lib/ganeti/daemon-util when called from ganeti-watcher.
Specifically:

   if [ -f /sbin/start-stop-daemon ]; then
     start-stop-daemon --stop --signal 0 --quiet \
       --pidfile $(_daemon_pidfile $name)
   else
     # if not Debian or Ubuntu
     checkpid $(_daemon_pidfile $name)
   fi

calls checkpid with the name of the pidfile, but CentOS/RHEL wants checkpid
called with the pid itself, not the name of the pidfile.  I "fixed" it via

   if [ -f /sbin/start-stop-daemon ]; then
     start-stop-daemon --stop --signal 0 --quiet \
       --pidfile $(_daemon_pidfile $name)
   else
     # if not Debian or Ubuntu
     #checkpid $(_daemon_pidfile $name)
     ejr=`cat $(_daemon_pidfile $name)`
     checkpid $ejr
   fi

which no longer generates any errors, and which does restart an instance
when I "kill -TERM" its kvm process and then run ganeti-watcher, but is
surely somewhat hackish...

```
Originally added on 2012-05-29 19:01:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This seems like a valid bug regarding daemon-util
```
Originally added on 2012-05-30 07:06:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
However, this does not address the original bug, I think.

The issue there is, that pycurl on Fedora/CentOS seems to be linked against another SSL library (namely Network Security Services). From lib/rapi/client.py (where the exception comes from) I see:

 # pycurl.version_info returns a tuple with information about the used
 # version of libcurl. Item 5 is the SSL library linked to it.

On a Fedora this looks like this:
$ python
>>> import pycurl
>>> pycurl.version_info()[5]
'NSS/3.13.3.0'

respectively:
>>> pycurl.version_info()
(3, '7.21.7', 464135, 'x86_64-redhat-linux-gnu', 1725, 'NSS/3.13.3.0', 0, '1.2.5', ('dict', 'file', 'ftp', 'ftps', 'gopher', 'http', 'https', 'imap', 'imaps', 'ldap', 'ldaps', 'pop3', 'pop3s', 'rtsp', 'scp', 'sftp', 'smtp', 'smtps', 'telnet', 'tftp'), None, 0, '1.22')

Looks like we need to support this as well

```
Originally added on 2012-05-30 07:18:18 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Btw this issue should be addressed in Ganeti 2.6:


commit 592eb0df47093cc32e1b38d119dc55e0f0f71d50
Author: René Nussbaumer <rn@google.com>
Date:   Wed May 30 11:17:39 2012 +0200

    Fix GenericCurlConfig when pycurl is linked against nss
    
    Redhat links its pycurl against NSS/ so this check fails and therefore
    makes ganeti-watcher unusable.
    
    Even though this seems to fix the problem and works, further testing on
    this might be needed.
    
    Signed-off-by: René Nussbaumer <rn@google.com>
    Reviewed-by: Iustin Pop <iustin@google.com>

```
Originally added on 2012-05-30 12:04:52 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
My, that was fast. Thanks René!
```
Originally added on 2012-05-30 15:01:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Migrate old issues from 'fixed' to 'released'.
```
Originally added on 2012-10-22 09:16:17 +0000 UTC.

Changed State: Released
