### ISSUE TITLE
gnt-node migrate gives python error

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#316]
Originally reported of Google Code with ID 260.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

# gnt-cluster version
Software version: 2.6.0
Internode protocol: 2060000
Configuration format: 2060000
OS api version: 20
Export interface: 0


<b>What distribution are you using?</b>

<b>What steps will reproduce the problem?</b>
1. gnt-node migrate dv-00

<b>What is the expected output? What do you see instead?</b>

# gnt-node migrate dv-00
Traceback (most recent call last):
  File "/usr/local/sbin/gnt-node", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/local/lib/python2.6/dist-packages/ganeti/client/gnt_node.py", line 1103, in Main
    env_override=_ENV_OVERRIDE)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 2222, in GenericMain
    func, options, args = _ParseArgs(sys.argv, commands, aliases, env_override)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 1552, in _ParseArgs
    usage="%%prog %s %s" % (cmd, usage))
  File "/usr/lib/python2.6/optparse.py", line 1214, in __init__
    add_help=add_help_option)
  File "/usr/lib/python2.6/optparse.py", line 1256, in _populate_option_list
    self.add_options(option_list)
  File "/usr/lib/python2.6/optparse.py", line 1039, in add_options
    self.add_option(option)
  File "/usr/lib/python2.6/optparse.py", line 1020, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.6/optparse.py", line 995, in _check_conflict
    option)
optparse.OptionConflictError: option --priority: conflicting option string(s): --priority


<b>Please provide any additional information below.</b>

How to fix:
Around line 1003 in the file '/usr/local/lib/python2.6/dist-packages/ganeti/client/gnt_node.py' the option 'PRIORITY_OPT' appears twice.

```
Originally added on 2012-08-10 15:12:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I just committed the fix for it 2 minutes ago :)

Will be released as part of 2.6.1.

thanks,
iustin
```
Originally added on 2012-08-10 15:14:30 +0000 UTC.

Added Labels: Type-Defect Component-scripts
Changed State: Fixed
Added to Milestone: Release2.6

**Comment by Ganeti-Issues-Migrator** [comment]
```
Issue 271 has been merged into this issue.
```
Originally added on 2012-09-26 21:25:07 +0000 UTC.

Mentioned Issue with GoogleCode ID 271 has been migrated to GitHub with ID #327.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Migrate old issues from 'fixed' to 'released'.
```
Originally added on 2012-10-22 09:16:17 +0000 UTC.

Changed State: Released
