### ISSUE TITLE
gnt-instance grow-disk does not work in ganeti 2.6.0

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#325]
Originally reported of Google Code with ID 269.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".

<b>What distribution are you using?</b>
ubuntu 12.04 lts

<b>What steps will reproduce the problem?</b>

<b>1.</b>
root@ubuntuxen01:~# gnt-instance add \
>         -n ubuntuxen01 \
>         -o linux+ubuntu-12.04_amd64 \
>         -t plain \
>         --disk 0:size=8G \
>         --disk 1:size=2G \
>         -B minmem=512M,maxmem=1G \
>         -H xen-pvm:kernel_path=/boot/pv-grub-4.1.2_64.gz \
>         --no-name-check \
>         --no-ip-check \
> ubuntutest01
Mon Sep 24 14:14:08 2012 * disk 0, size 8.0G
Mon Sep 24 14:14:08 2012 * disk 1, size 2.0G
Mon Sep 24 14:14:08 2012 * creating instance disks...
Mon Sep 24 14:14:09 2012 adding instance ubuntutest01 to cluster config
Mon Sep 24 14:14:09 2012  - INFO: Waiting for instance ubuntutest01 to sync disks.
Mon Sep 24 14:14:09 2012  - INFO: Instance ubuntutest01's disks are in sync.
Mon Sep 24 14:14:09 2012 * running the instance OS create scripts...
Mon Sep 24 14:15:32 2012 * starting instance...


<b>2.</b>
root@ubuntuxen01:~# gnt-instance info ubuntutest01
Instance name: ubuntutest01
UUID: 8fca004e-968f-4e37-a2f9-43d972045623
Serial number: 2
Creation time: 2012-09-24 14:14:09
Modification time: 2012-09-24 14:15:32
State: configured to be up, actual state is up
  Nodes:
    - primary: ubuntuxen01.domain.intern
      group: default (UUID 32c7a1cc-5996-4f4a-aade-fa32cb67c1e8)
    - secondaries:
  Operating system: linux+ubuntu-12.04_amd64
  Allocated network port: None
  Hypervisor: xen-pvm
    - blockdev_prefix: default (sd)
    - bootloader_args: default ()
    - bootloader_path: default ()
    - cpu_mask: default (all)
    - initrd_path: default ()
    - kernel_args: default ((hd0)/boot/grub/menu.lst)
    - kernel_path: /boot/pv-grub-4.1.2_64.gz
    - reboot_behavior: default (reboot)
    - root_path: default ()
   - use_bootloader: default (False)
  Hardware:
    - always_failover: default (False)
    - auto_balance: default (True)
    - maxmem: 1024
    - memory: default (1024)
    - minmem: 512
    - spindle_use: default (1)
    - vcpus: default (2)
    - NICs:
      - nic/0: MAC: aa:00:00:09:5c:27, IP: None, mode: bridged, link: br0
  Disk template: plain
  Disks:
    - disk/0: lvm, size 8.0G
      access mode: rw
      logical_id:  system/2f801264-fe51-4e8c-9388-f5740798e97e.disk0
      on primary:  /dev/system/2f801264-fe51-4e8c-9388-f5740798e97e.disk0 (252:2)
    - disk/1: lvm, size 2.0G
      access mode: rw
      logical_id:  system/083ab68c-64dc-4689-aa16-1022f0b68778.disk1
      on primary:  /dev/system/083ab68c-64dc-4689-aa16-1022f0b68778.disk1 (252:4)

<b>3.</b>
root@ubuntuxen01:~# gnt-instance grow-disk -d ubuntutest01 0 1G
2012-09-24 14:16:15,201: gnt-instance grow-disk pid=3988 cli:2238 INFO Command line: gnt-instance grow-disk -d ubuntutest01 0 1G
Mon Sep 24 14:16:15 2012 Growing disk 0 of instance 'ubuntutest01' by 1.0G to 9.0G
2012-09-24 14:16:21,232: gnt-instance grow-disk pid=3988 cli:2245 ERROR Error during command processing
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2241, in GenericMain
    result = func(options, args)
  File "/usr/lib/pymodules/python2.7/ganeti/client/gnt_instance.py", line 673, in GrowDisk
    SubmitOrSend(op, opts)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2053, in SubmitOrSend
    return SubmitOpCode(op, cl=cl, feedback_fn=feedback_fn, opts=opts)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2030, in SubmitOpCode
    reporter=reporter)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2011, in PollJob
    return GenericPollJob(job_id, _LuxiJobPollCb(cl), reporter)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 1833, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/usr/lib/pymodules/python2.7/ganeti/errors.py", line 506, in MaybeRaise
    raise errcls(*args)
ProgrammerError: Can only act on disks belonging to the target instance
Unhandled Ganeti error: Can only act on disks belonging to the target instance

4.
root@ubuntuxen01:~# gnt-instance info ubuntutest01
Instance name: ubuntutest01
UUID: 8fca004e-968f-4e37-a2f9-43d972045623
Serial number: 3
Creation time: 2012-09-24 14:14:09
Modification time: 2012-09-24 14:16:21
State: configured to be up, actual state is up
  Nodes:
    - primary: ubuntuxen01.domain.intern
      group: default (UUID 32c7a1cc-5996-4f4a-aade-fa32cb67c1e8)
    - secondaries:
  Operating system: linux+ubuntu-12.04_amd64
  Allocated network port: None
  Hypervisor: xen-pvm
    - blockdev_prefix: default (sd)
    - bootloader_args: default ()
    - bootloader_path: default ()
    - cpu_mask: default (all)
    - initrd_path: default ()
    - kernel_args: default ((hd0)/boot/grub/menu.lst)
    - kernel_path: /boot/pv-grub-4.1.2_64.gz
    - reboot_behavior: default (reboot)
    - root_path: default ()
    - use_bootloader: default (False)
  Hardware:
    - always_failover: default (False)
    - auto_balance: default (True)
    - maxmem: 1024
    - memory: default (1024)
    - minmem: 512
    - spindle_use: default (1)
    - vcpus: default (2)
    - NICs:
      - nic/0: MAC: aa:00:00:09:5c:27, IP: None, mode: bridged, link: br0
  Disk template: plain
  Disks:
    - disk/0: lvm, size 8.0G
      access mode: rw
      logical_id:  system/2f801264-fe51-4e8c-9388-f5740798e97e.disk0
      on primary:  /dev/system/2f801264-fe51-4e8c-9388-f5740798e97e.disk0 (252:2)
root@ubuntuxen01:~#

it seams like grow-disk removes the second disk!!!

5. 
root@ubuntuxen01:~# gnt-cluster verify
Submitted jobs 45, 46
Waiting for job 45 ...
Mon Sep 24 14:21:21 2012 * Verifying cluster config
Mon Sep 24 14:21:21 2012 * Verifying cluster certificate files
Mon Sep 24 14:21:21 2012 * Verifying hypervisor parameters
Mon Sep 24 14:21:21 2012 * Verifying all nodes belong to an existing group
Waiting for job 46 ...
Mon Sep 24 14:21:21 2012 * Verifying group 'default'
Mon Sep 24 14:21:21 2012 * Gathering data (1 nodes)
Mon Sep 24 14:21:23 2012 * Gathering disk information (1 nodes)
Mon Sep 24 14:21:23 2012 * Verifying configuration file consistency
Mon Sep 24 14:21:23 2012 * Verifying node status
Mon Sep 24 14:21:23 2012 * Verifying instance status
Mon Sep 24 14:21:23 2012 * Verifying orphan volumes
Mon Sep 24 14:21:23 2012   - ERROR: node ubuntuxen01.domain.intern: volume system/083ab68c-64dc-4689-aa16-1022f0b68778.disk1 is unknown
Mon Sep 24 14:21:23 2012   - ERROR: node ubuntuxen01.domain.intern: volume system/root is unknown
Mon Sep 24 14:21:23 2012   - ERROR: node ubuntuxen01.domain.intern: volume system/5de84566-cb73-4ce0-9aa6-c8d426a62d61.disk1 is unknown
Mon Sep 24 14:21:23 2012   - ERROR: node ubuntuxen01.domain.intern: volume system/swap is unknown
Mon Sep 24 14:21:23 2012 * Verifying N+1 Memory redundancy
Mon Sep 24 14:21:23 2012 * Other Notes
Mon Sep 24 14:21:23 2012   - NOTICE: 1 non-redundant instance(s) found.
Mon Sep 24 14:21:23 2012 * Hooks Results
<b>What is the expected output? What do you see instead?</b>

<b>Please provide any additional information below.</b>

```
Originally added on 2012-09-24 12:23:46 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hey, could you please also provide the backtrace from /var/log/ganeti/master-daemon.log? It would make it easier to find the problem :). Thank you!
```
Originally added on 2012-09-24 12:42:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
2012-09-24 14:16:15,217: ganeti-masterd pid=30982/Jq3/Job37 INFO Op 1/1: opcode INSTANCE_GROW_DISK(ubuntutest01) waiting for locks
2012-09-24 14:16:15,220: ganeti-masterd pid=30982/ClientReq2 INFO Received job poll request for 37
2012-09-24 14:16:15,221: ganeti-masterd pid=30982/ClientReq3 INFO Received job poll request for 37
2012-09-24 14:16:15,456: ganeti-masterd pid=30982/ClientReq4 INFO Received job poll request for 37
2012-09-24 14:16:15,876: ganeti-masterd pid=30982/ClientReq5 INFO Received job poll request for 37
2012-09-24 14:16:21,113: ganeti-masterd pid=30982/Jq3/Job37 ERROR Op 1/1: Caught exception in INSTANCE_GROW_DISK(ubuntutest01)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ganeti/jqueue.py", line 1020, in _ExecOpCodeUnlocked
    timeout=timeout, priority=op.priority)
  File "/usr/lib/pymodules/python2.7/ganeti/jqueue.py", line 1304, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 455, in ExecOpCode
    priority)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 394, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 403, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 394, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 394, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 356, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/pymodules/python2.7/ganeti/mcpu.py", line 328, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/lib/pymodules/python2.7/ganeti/cmdlib.py", line 11705, in Exec
    disk_abort = not _WaitForSync(self, instance, disks=[disk])
  File "/usr/lib/pymodules/python2.7/ganeti/cmdlib.py", line 4463, in _WaitForSync
    disks = _ExpandCheckDisks(instance, disks)
  File "/usr/lib/pymodules/python2.7/ganeti/cmdlib.py", line 6498, in _ExpandCheckDisks
    raise errors.ProgrammerError("Can only act on disks belonging to the"
ProgrammerError: Can only act on disks belonging to the target instance
2012-09-24 14:16:21,119: ganeti-masterd pid=30982/Jq3/Job37 INFO Finished job 37, status = error

```
Originally added on 2012-09-24 12:47:22 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This issue is pretty weird. It seems like some odd interaction with config references (the disks in this case). However, I'm not able to reproduce it for debugging :(. Do you have that only with that specific instance or with all of them?

I could track it to two possible changes (from 2.5 to 2.6) verified using: git blame v2.5.1.. -L'/^class LUInstanceGrowDisk/,/^class/' lib/cmdlib.py

One is commit e7f99087 the other one is commit 62bfbc7d. Beside of those two commits nothing has changed code in that regard.

I verified using drbd and plain (as your instance is plain) instance disks. Both worked in my environment.
```
Originally added on 2012-09-25 13:55:01 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
i have this problem with any instance i create on this two node cluster. i've also re-created the cluster and re-installed instances for testing. the problem always occurs.

system is ubuntu 12.04 amd64 with ganeti 2.6.0

if i can help with any testing let me know. the cluster is no in production state atm.... 
```
Originally added on 2012-09-26 12:34:47 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
is there anything i can do to debug this problem?

also i noticed that /var/lib/ganeti/config.data is in a strange format. everything in one line. is this a wanted behavior?
```
Originally added on 2012-10-01 08:59:26 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
> also i noticed that /var/lib/ganeti/config.data is in a strange format. everything in one line. is this a wanted behavior?

Yes, unfortunately it is: <http://git.ganeti.org/?p=ganeti.git;a=commit;h=a182a3ed7>. You can use “fmtjson” (/usr/lib/ganeti/tools/fmtjson) to format it nicely for viewing.
```
Originally added on 2012-10-01 18:02:41 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
ok, thanks for this info. but with this new format its much harder to edit cluster config manually if needed....
```
Originally added on 2012-10-04 07:34:34 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
is there anything i can do to debug this issue?
```
Originally added on 2012-10-09 13:54:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
is there anything i can do to debug this issue? ;)
```
Originally added on 2012-10-19 08:38:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I've tested this again with 2.6.1 on Debian Squeeze (python 2.6.6) with the same config as you: two-disk instance, growing first disk, and at first test it doesn't happen.

What python version do you have? I wonder if this is a changed behaviour in Python related to dictionary changes.

To debug this, it would be helpful to edit the cmdlib file and change the _ExpandCheckDisks function as follows:

      …
      raise errors.ProgrammerError("Can only act on disks belonging to the"
                                   " target instance: %r versus %r" % (disks, instance.disks))

The check looks correct, but if the hashing or something similar changed, just 'issubset' might need redoing.
```
Originally added on 2012-10-22 10:30:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

I've also tested with 2.6.1 and Debian Wheeze (Python 2.7.3) and I can't reproduce it, growing multiple types of disk (drbd, plain), growing the first or second disk, etc.

Can you still reproduce the issue?
```
Originally added on 2012-10-24 10:19:21 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I am getting this error after upgrading from 2.4 to 2.6.2 on Ubuntu 12.04. I modified _ExpandCheckDisks as suggested and got this info:

[{'logical_id': ('ganeti', '14240a76-038d-41d7-92ed-541bd2372284.disk0'), 'dev_type': 'lvm', 'params': {}, 'mode': 'rw', 'physical_id': ('ganeti', '14240a76-038d-41d7-92ed-541bd2372284.disk0'), 'iv_name': 'disk/0', 'size': 6144}]
versus
[{'logical_id': ('ganeti', '14240a76-038d-41d7-92ed-541bd2372284.disk0'), 'dev_type': 'lvm', 'params': {'stripes': 1}, 'mode': 'rw', 'physical_id': ('ganeti', '14240a76-038d-41d7-92ed-541bd2372284.disk0'), 'iv_name': 'disk/0', 'size': 5120}]

```
Originally added on 2013-02-18 17:59:58 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-08 08:05:13 +0000 UTC.

Added Labels: Priority-Medium
Changed State: Accepted
Added to Milestone: Release2.7

**Comment by Ganeti-Issues-Migrator** [comment]
```
Indeed it seems those two disks are marked as different, but should be the same.
Perhaps we should compare just on the logical id.


```
Originally added on 2013-05-22 10:59:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Question: Does this not happen when
--no-wait-for-sync is passed? How about with 2.7 rc?

While I can see why those dicts are different I still can't reproduce it neither with drbd nor with plain instances. :/
```
Originally added on 2013-05-22 12:51:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
just want to say that i never had this problem again.....
```
Originally added on 2014-01-30 09:28:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I am closing this issue because it's old and nobody has updated this in a long time. This is according to our current team effort to migrate to Github issues. Please feel free to comment and re-open this if you think it's still relevant.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.

```
Originally added on 2016-12-13 11:40:35 +0000 UTC.

Changed State: Obsolete
Removed from Milestone: Release2.7
