### ISSUE TITLE
"# gnt-node migrate NODE" not working as expected

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#327]
Originally reported of Google Code with ID 271.

```
What software version are you running? Please provide the output of "gnt-cluster --version" and "gnt-cluster version".
gnt-cluster (ganeti v2.6.0) 2.6.0
Software version: 2.6.0
Internode protocol: 2060000
Configuration format: 2060000
OS api version: 20
Export interface: 0

<b>What distribution are you using?</b>
Gentoo
vanilla-kernel 3.5.3

<b>What steps will reproduce the problem?</b>
1. gnt-node migrate node2

What is the expected output? 
Human readable error message with parameters documented in '$ man gnt-node'. I have no clue why I get this error message.

What do you see instead?

myhost ~ # gnt-node migrate node2
Traceback (most recent call last):
  File "/usr/sbin/gnt-node", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib64/python2.7/site-packages/ganeti/client/gnt_node.py", line 1103, in Main
    env_override=_ENV_OVERRIDE)
  File "/usr/lib64/python2.7/site-packages/ganeti/cli.py", line 2222, in GenericMain
    func, options, args = _ParseArgs(sys.argv, commands, aliases, env_override)
  File "/usr/lib64/python2.7/site-packages/ganeti/cli.py", line 1552, in _ParseArgs
    usage="%%prog %s %s" % (cmd, usage))
  File "/usr/lib64/python2.7/optparse.py", line 1219, in __init__
    add_help=add_help_option)
  File "/usr/lib64/python2.7/optparse.py", line 1261, in _populate_option_list
    self.add_options(option_list)
  File "/usr/lib64/python2.7/optparse.py", line 1039, in add_options
    self.add_option(option)
  File "/usr/lib64/python2.7/optparse.py", line 1020, in add_option
    self._check_conflict(option)
  File "/usr/lib64/python2.7/optparse.py", line 995, in _check_conflict
    option)
optparse.OptionConflictError: option --priority: conflicting option string(s): --priority
```
Originally added on 2012-09-26 18:26:46 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This has been fixed in git, will be released as part of 2.6.1.
```
Originally added on 2012-09-26 21:25:07 +0000 UTC.

Changed State: Duplicate
Marked as duplicate of #316
