### ISSUE TITLE
Special characters (non-ASCII) not supported in instances OS field

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#335]
Originally reported of Google Code with ID 279.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
# gnt-cluster version
Software version: 2.5.1
Internode protocol: 2050000
Configuration format: 2050000
OS api version: 20
Export interface: 0
# gnt-cluster --version
gnt-cluster (ganeti v2.5.1) 2.5.1

<b>What distribution are you using?</b>
# cat /etc/debian_version
6.0.6

# uname -a
Linux shelley.oehwu.local 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64 GNU/Linux

<b>What steps will reproduce the problem?</b>
1. Rename an instance with gnt-instance --force --force-variant -o "some name with special character" [instance_name]

<b>What is the expected output? What do you see instead?</b>

When creating an instance in fully virualized mode and installing the OS with it's install CD, some people (like me) abuse the OS field to add a small description. The use of a special character like german "Umlaute" (ä, ö, ü) every time when showing the OS field (gnt-instance list, gnt-instance info) ganeti throws some kind of unicode error:
# gnt-instance list
Traceback (most recent call last):
  File "/usr/sbin/gnt-instance", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib/pymodules/python2.6/ganeti/client/gnt_instance.py", line 1556, in Main
    override={"tag_type": constants.TAG_INSTANCE})
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 2025, in GenericMain
    result = func(options, args)
  File "/usr/lib/pymodules/python2.6/ganeti/client/gnt_instance.py", line 223, in ListInstances
    force_filter=opts.force_filter)
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 2676, in GenericList
    verbose=verbose)
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 2590, in FormatQueryResult
    table = FormatTable(result.data, columns, header, separator)
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 2786, in FormatTable
    formatted = [col.format(value) for value, col in zip(row, columns)]
  File "/usr/lib/pymodules/python2.6/ganeti/cli.py", line 2517, in __call__
    return self._fn(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 25: ordinal not in range(128)

The solution to repair this is editing the config.data file by hand and removing the umlaut.


<b>Please provide any additional information below.</b>
Accorting to Iustin this is a known bug on the internal bug tracker, related to Python 2.x
The corresponding discussion can be found here: https://groups.google.com/d/topic/ganeti/UMmW6ZJfgaw/discussion

```
Originally added on 2012-10-20 07:55:37 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Another unicode characters bug. :/ 
```
Originally added on 2013-05-08 08:10:32 +0000 UTC.

Added Labels: Priority-Low
Changed State: Accepted
Added to Milestone: Release2.7

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-07-30 11:38:29 +0000 UTC.

Now blocking: 447 (now #503);

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.
```
Originally added on 2016-12-12 14:50:37 +0000 UTC.

Changed State: PatchesWelcome
Removed from Milestone: Release2.11
