### ISSUE TITLE
Job queue caching opcode description interacts badly with changing summaries

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#345]
Originally reported of Google Code with ID 289.

```
In case an opcode's summary is changed (e.g. instance create with hostname that resolves to something different), this can result in confusing log messages, since the job queue code caches the summary:

2012-10-31 12:23:30,723: ganeti-masterd pid=587/Jq11/Job962201 ERROR Op 1/1: Caught exception in INSTANCE_CREATE(foobar)
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1020, in _ExecOpCodeUnlocked
    timeout=timeout, priority=op.priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1304, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 457, in ExecOpCode
    priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 393, in _LockAndExecLU
    errors.ECODE_FAULT)
OpPrereqError: ("Couldn't add locks (barbaz), probably because of a race condition with another job, who added them first", 'internal_error')
```
Originally added on 2012-10-31 12:49:42 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I don't feel this is that confusing, and we didn't get many reports that this was an actual issue, so I'll mark it as WontFix for now.

Thanks,

Guido

```
Originally added on 2013-12-09 14:15:33 +0000 UTC.

Changed State: WontFix
