### ISSUE TITLE
On master querying with nodes not responding causes fails

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#356]
Originally reported of Google Code with ID 300.

```
Make sure a node is not responding (mine were rebooting, still have to check if stopping noded is enough) (note that the nodes where not offlined).

gnt-node list


2012-11-05 12:21:07,732: ganeti-masterd pid=3182/ClientReq14 rpc:387 ERROR RPC error in node_info on node wpeg5.hot.corp.google.com: Error t
2012-11-05 12:21:07,732: ganeti-masterd pid=3182/ClientReq14 rpc:387 ERROR RPC error in node_info on node wpeg6.hot.corp.google.com: Error t
2012-11-05 12:21:07,732: ganeti-masterd pid=3182/ClientReq14 masterd:99 ERROR Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/ganeti/server/masterd.py", line 92, in RunTask
    result = client_ops.handle_request(method, args)
  File "/usr/lib/python2.6/dist-packages/ganeti/server/masterd.py", line 311, in handle_request
    qfilter=qfilter))
  File "/usr/lib/python2.6/dist-packages/ganeti/server/masterd.py", line 438, in _Query
    return proc.ExecOpCode(op, None)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 470, in ExecOpCode
    priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 418, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 418, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 418, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 418, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout, priority)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 360, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 331, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib.py", line 5484, in Exec
    return self.impl.NewStyleQuery(self)
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib.py", line 569, in NewStyleQuery
    return query.GetQueryResponse(self.query, self._GetQueryData(lu),
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib.py", line 5120, in _GetQueryData
    for (name, nresult) in node_data.items()
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib.py", line 5121, in <genexpr>
    if not nresult.fail_msg and nresult.payload)
  File "/usr/lib/python2.6/dist-packages/ganeti/rpc.py", line 580, in MakeLegacyNodeInfo
    return utils.JoinDisjointDicts(utils.JoinDisjointDicts(vg_info, hv_info), {
  File "/usr/lib/python2.6/dist-packages/ganeti/utils/algo.py", line 68, in JoinDisjointDicts
    assert not (set(dict_a) & set(dict_b)), ("Duplicate keys found while joining"
TypeError: 'NoneType' object is not iterable

```
Originally added on 2012-11-05 12:24:44 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Note: this is a problem even if the node is offline. :(
```
Originally added on 2012-11-05 12:33:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2012-11-05 12:34:32 +0000 UTC.

Added Labels: Type-Defect Priority-High Component-logic Usability
Changed State: Accepted
Added to Milestone: Release2.7

**Comment by Ganeti-Issues-Migrator** [comment]
```
(never mind, my mistake, this was unrelated to the node being offline)
```
Originally added on 2012-11-05 12:37:27 +0000 UTC.

Changed State: Invalid
