### ISSUE TITLE
Network address pool doesn't handle memory errors nicely

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#390]
Originally reported of Google Code with ID 334.

```
If a sufficiently small network mask is given, bitarray produces large strings, leading to running out of memory. The network pool should probably restrict the size of networks and/or give a better error message.

No nice error message is given:
$ gnt-network add --network 1.2.3.0/1 test
Failure: command execution error:

Master log:
2012-12-18 17:16:47,121: ganeti-masterd pid=5990/Jq1/Job699 jqueue:1131 ERROR Op 1/1: Caught exception in NETWORK_ADD(test)
Traceback (most recent call last):
…
  File "/usr/lib/python2.6/dist-packages/ganeti/network.py", line 226, in InitializeNetwork
    obj.Update()
  File "/usr/lib/python2.6/dist-packages/ganeti/network.py", line 104, in Update
    self.net.ext_reservations = self.ext_reservations.to01()
MemoryError

Limit memory to not kill the system:
$ ulimit -v $((1024*1024)) -d $((1024*1024)) -v $((1024*1024))

Reproduce memory error:
$ PYTHONPATH=. python -c 'from ganeti import network, objects; net = objects.Network(family=4, network="192.168.2.0/2"); network.AddressPool.InitializeNetwork(net);'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/dist-packages/ganeti/network.py", line 226, in InitializeNetwork
    obj.Update()
  File "/usr/lib/python2.6/dist-packages/ganeti/network.py", line 104, in Update
    self.net.ext_reservations = self.ext_reservations.to01()
MemoryError
```
Originally added on 2012-12-18 17:19:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-02-25 13:34:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
+helga, who has been working on networks.
Dimitris, Helga, what would you think of fixing this by putting a limit on the biggest network we can support? (would, eg, a /16 work as a minimum? should we support /8?)

Thanks,

Guido
```
Originally added on 2013-04-08 20:16:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Afair /16 is acceptably "fast", /8 is awfully slow and with /2 or so it crashes. Sure, we can limit it to /8 as a maximum as a quick fix, though I was hoping to have time for a more substantial fix. 
```
Originally added on 2013-04-08 22:57:24 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I believe then it's good to limit it to a /8 for 2.7, and then implement a more proper fix either during the 2.8 beta series or in 2.9 (depending on how big the changes are).

Thanks,
Guido
```
Originally added on 2013-04-09 02:12:22 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Assigning to helga, since she was working on it.

Thanks,
Guido

```
Originally added on 2013-04-10 14:50:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-04-10 14:58:39 +0000 UTC.

Added Labels: Priority-Medium

**Comment by Ganeti-Issues-Migrator** [comment]
```
Quick fix done with the following patches. Leaving the issue open, but change milestone for the more thorough fix.

commit 06c056d3e45cfc49a2ce84aec3918af1ec171f84
Author: Helga Velroyen <helgav@google.com>
Date:   Wed Apr 10 14:06:19 2013 +0200

    Limit the size of networks to /16
    
    This patch introduces an upper limit to the size of the networks that can
    be created.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Guido Trotter <ultrotter@google.com>

commit 59baad7aa061c923e68ce3726bf9a025ff5f9f1d
Author: Helga Velroyen <helgav@google.com>
Date:   Mon Jan 21 16:20:34 2013 +0100

    Check minimum size of networks on creation
    
    When creating a network, so far no size constraints were checked.
    We now limit the size of a network to a /30 or bigger, although
    tecnically, the ipaddr library supports even /32 networks.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Michael Hanselmann <hansmi@google.com>
    Reviewed-by: Guido Trotter <ultrotter@google.com>

```
Originally added on 2013-04-10 15:48:11 +0000 UTC.

Added to Milestone: Release2.8
Removed from Milestone: Release2.7

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
I tried a couple of this to improve the situation, among those:
- Try to use a different bit array implementation (not much different as bitarray is already quite efficient).
- Encode the reservations bit string differently in the network objects (improves configuration handling, but some operations get slower and memory is still exhausted soon enough).

However, none of these solutions worked well enough and as discussed, given that the _realistically_ used network sizes are working fine, I think we should keep the current restriction in size to /16 and don't spend more time on this.
```
Originally added on 2013-11-13 16:10:27 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-05 12:51:10 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-04-28 09:06:47 +0000 UTC.

Changed State: Released
