### ISSUE TITLE
Cluster Bootstap fails if SSH_CONFIG_DIR/ssh_host_rsa_key.pub does not exist.

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#394]
Originally reported of Google Code with ID 338.

```
What software version are you running? Please provide the output of "gnt-
cluster --version" and "gnt-cluster version".
gnt-cluster (ganeti v2.6.2-1048-g3add757) 2.6.2

<b>What distribution are you using?</b>
CentOS 6 with custom 3.6.9 kernel

<b>What steps will reproduce the problem?</b>
1. Install a new CentOS machine
2. Attempt to initialize a cluster with gnt-cluster init ...

<b>What is the expected output? What do you see instead?</b>
I get:
Traceback (most recent call last):
  File "/usr/local/sbin/gnt-cluster", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib/python2.6/site-packages/ganeti/client/gnt_cluster.py", line 1600, in Main
    aliases=aliases)
  File "/usr/lib/python2.6/site-packages/ganeti/cli.py", line 2241, in GenericMain
    result = func(options, args)
  File "/usr/lib/python2.6/site-packages/ganeti/rpc.py", line 131, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ganeti/client/gnt_cluster.py", line 226, in InitCluster
    disk_state=disk_state,
  File "/usr/lib/python2.6/site-packages/ganeti/bootstrap.py", line 473, in InitCluster
    sshline = utils.ReadFile(constants.SSH_HOST_RSA_PUB)
  File "/usr/lib/python2.6/site-packages/ganeti/utils/io.py", line 105, in ReadFile
    f = open(file_name, "r")
IOError: [Errno 2] No such file or directory: '/etc/ssh/ssh_host_rsa_key.pub'

<b>Please provide any additional information below.</b>
# ls /etc/ssh/
moduli      sshd_config       ssh_host_dsa_key  ssh_host_key.pub
ssh_config  sshd_config.ORIG  ssh_host_key      ssh_host_rsa_key

I am working on this issue already (it started as related to #236), but needed to split it off because it is distinct.

I probably need to petition for membership or some such, but I'd appreciate it if someone could assign this to me (and point me in the right direction to become a dev/contributor)
```
Originally added on 2012-12-27 01:50:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The attached patch ought to fix this issue.  I introduced a new function in lib/ssh.py called GetHostFiles(), which mirrors GetUserFiles(...) in the same file.
I also modified lib/bootstrap.py to use this function to find the host ssh keypairs.
I am sure there are other places this is useful, so I should go hunt those up and will continue making patches as I go.
```
Originally added on 2012-12-27 03:31:15 +0000 UTC.

Attachments: 
[fix-ssh-host-key-hunt.patch](https://storage.googleapis.com/google-code-attachments/ganeti/issue-338/comment-1/fix-ssh-host-key-hunt.patch)

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi Steve,

Thanks a lot for submitting a patch about this. As a first step, could you please sign the google CLA which we need for accepting patches? You can find it at: http://code.google.com/legal/individual-cla-v1.0.html
(note that at the bottom of the page you can sign electronically)

Once you have done that we can look into pushing the patch. Thanks a lot again,

Guido
```
Originally added on 2012-12-27 16:04:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Guido,
Thanks!  I just submitted my CLA.

Steve
```
Originally added on 2012-12-27 16:08:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Assigning to 2.8 so we can triage whether this patch is good as is for that version, or we should push it forward/change anything.
```
Originally added on 2013-07-26 12:45:53 +0000 UTC.

Added Labels: Type-Enhancement Priority-Medium
Changed State: Accepted
Added to Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
The attached patch does not capture the problem properly.
ssh_host_key[.pub] does contain a RSA key, but for ssh version 1. Such a key is not useful for Ganeti.

The real problem is that Ganeti requires RSA for its SSH setup. Only RSA keys are written to the known host file, and the cluster configuration right now only has a field to store the RSA public key.

In order to fix this problem, DSA has to be supported during cluster initialization, and if only DSA keys are found, those have to be used instead of the RSA ones.
```
Originally added on 2013-08-06 14:07:27 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed with:

commit a9542a4feda04ba7afb08b68ae51abb9fa384d3a
Author: Thomas Thrainer <thomasth@google.com>
Date:   Tue Aug 6 17:10:15 2013 +0200

    Support DSA SSH keys in bootstrap
    
    As outlined in issue 338, Ganeti failed to initialize a cluster if no
    RSA SSH key is present on the master node. This patch extends Ganetis
    support to DSA keys, so clusters with only DSA keys are possible now.
    
    This fixes issue 338.
    
    Signed-off-by: Thomas Thrainer <thomasth@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>
```
Originally added on 2013-08-07 08:46:13 +0000 UTC.

Mentioned Issue with GoogleCode ID 338 has been migrated to GitHub with ID #394.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-10-30 09:30:16 +0000 UTC.

Changed State: Released
