### ISSUE TITLE
Adding tags to a network raises exceptions

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#408]
Originally reported of Google Code with ID 352.

```
<b>What steps will reproduce the problem?</b>
1. Run gnt-network add-tags sometags yournetworkname

<b>What is the expected output? What do you see instead?</b>
That it does add a tag to the network. Instead, an exception is thrown:

2013-01-25 13:24:04,643: ganeti-masterd pid=4188/Jq2/Job47299 jqueue:1131 ERROR Op 1/1: Caught exception in TAGS_SET
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1098, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1409, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 531, in ExecOpCode
    calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 482, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 482, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 482, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 482, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 482, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 473, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 421, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 388, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib.py", line 15795, in Exec
    self.target.AddTag(tag)
AttributeError: 'NoneType' object has no attribute 'AddTag'

```
Originally added on 2013-01-25 13:27:38 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
2013/1/25 Dimitris Aragiorgis <dimara@grnet.gr>:
> This is caused due to the fact that the  _UnlockedLookupNetwork() config method
> returns None, instead of raising OpPrereqError if target network is not
> found. I will fix that and check if it breaks the code elsewhere.
```
Originally added on 2013-01-25 15:20:39 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
fixed with:

commit 0ae4b3551221e980262dadae9735dd652ba9eb58
Author: Helga Velroyen <helgav@google.com>
Date:   Wed Jan 30 16:56:20 2013 +0000

    Removes check for conflicts from NetworkDisconnect
    
    This removes the check for conflicts from the Haskell
    version of the OpCode NetworkDisconnect. This alignes
    the Haskell code with the patch
    "Force conflicts check in LUNetworkDisconnect" (which
    is currently under review). I will submit these patches
    together then.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Michael Hanselmann <hansmi@google.com>

commit 1cce2c47da54574b7face60da45665af3e19795f
Author: Helga Velroyen <helgav@google.com>
Date:   Wed Jan 30 17:35:10 2013 +0100

    If _UnlockedLookupNetwork() fails raise error
    
    Make _UnlockedLookupNetwork() raise OpPrereqError (instead of returning
    None) in case it does not find the requested network. Remove useless and
    duplicate code such as:
    
    if net_uuid is None:
      raise...
    
    Signed-off-by: Dimitris Aragiorgis <dimara@grnet.gr>
    Reviewed-by: Helga Velroyen <helgav@google.com>

commit 6bb939a2171bcfa554736260543c0bd7b5ae0e51
Author: Helga Velroyen <helgav@google.com>
Date:   Wed Jan 30 17:12:26 2013 +0100

    Force conflicts check in LUNetworkDisconnect
    
    Until now if one disconnects a network with --no-conflicts-check
    and then remove it, there is a possibility to leave instances with NICs
    referencing non-existing networks. This causes network queries,
    instance removal and modification to fail.
    
    This patch allows a network to be disconnected from a nodegroup,
    only if instances residing in the nodegroup do not have NICs attached
    to the network. Otherwise OpPrereqError is raised. The
    --no-conflicts-check option is removed from the gnt-network disconnect
    command as well.
    
    Signed-off-by: Dimitris Aragiorgis <dimara@grnet.gr>
    Reviewed-by: Helga Velroyen <helgav@google.com>

```
Originally added on 2013-01-31 12:40:15 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-09 05:49:16 +0000 UTC.

Added to Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-05 13:02:18 +0000 UTC.
