### ISSUE TITLE
Ubuntu 13.04, Python

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#519]
Originally reported of Google Code with ID 463.

```
Hello,

i run Ubuntu 13.04 with Ganeti 2.6.2. 

I cant run some gnt-commands without a python error like this:

root@vmnode1:~# gnt-cluster verify
Traceback (most recent call last):
  File "/usr/sbin/gnt-cluster", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/lib/pymodules/python2.7/ganeti/client/gnt_cluster.py", line 1600, in Main
    aliases=aliases)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2241, in GenericMain
    result = func(options, args)
  File "/usr/lib/pymodules/python2.7/ganeti/client/gnt_cluster.py", line 580, in VerifyCluster
    result = SubmitOpCode(op, cl=cl, opts=opts)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 2027, in SubmitOpCode
    job_id = SendJob([op], cl=cl)
  File "/usr/lib/pymodules/python2.7/ganeti/cli.py", line 1762, in SendJob
    job_id = cl.SubmitJob(ops)
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 476, in SubmitJob
    return self.CallMethod(REQ_SUBMIT_JOB, (ops_state, ))
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 466, in CallMethod
    version=constants.LUXI_VERSION)
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 378, in CallLuxiMethod
    response_msg = transport_cb(request_msg)
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 447, in _SendMethodCall
    return self.transport.Call(data)
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 277, in Call
    return self.Recv()
  File "/usr/lib/pymodules/python2.7/ganeti/luxi.py", line 255, in Recv
    data = self.socket.recv(4096)
socket.error: [Errno 104] Connection reset by peer

more info:
https://code.google.com/p/ganeti/issues/detail?id=191

What can i do?
```
Originally added on 2013-05-15 10:57:10 +0000 UTC.

Mentioned Issue with GoogleCode ID 191 has been migrated to GitHub with ID #247.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Please see this discussion (https://groups.google.com/d/msg/ganeti/p9SjSgmngpU/cA1IZTfJd_cJ) for further details and a workaround.
```
Originally added on 2013-05-15 11:23:11 +0000 UTC.

Changed State: Duplicate
Marked as duplicate of #247
