### ISSUE TITLE
creating diskless instances fails

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#534]
Originally reported of Google Code with ID 478.

```
<b>What steps will reproduce the problem?</b>
1. run QA with "instance-add-diskless" enabled
2. see:

---- 2013-05-29 13:42:47.508658 start gnt-instance add -t diskless -----
---- 2013-05-29 13:42:47.508737 time=0:00:00.000079 gnt-instance add -t diskless
Traceback (most recent call last):
  File "./ganeti-qa.py", line 888, in <module>
    main()
  File "/usr/local/google/home/helgav/git_ganeti/ganeti/ganeti/rapi/client.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 883, in main
    RunQa()
  File "./ganeti-qa.py", line 791, in RunQa
    RunInstanceTests()
  File "./ganeti-qa.py", line 681, in RunInstanceTests
    instance = RunTest(create_fun, inodes)
  File "./ganeti-qa.py", line 93, in RunTest
    retval = fn(*args, **kwargs)
  File "[...]/ganeti/qa/qa_utils.py", line 710, in wrapper
    _InstanceCheckInner(after, instarg, args, result)
  File "[...]/ganeti/qa/qa_utils.py", line 687, in _InstanceCheckInner
    RunInstanceCheck(instance, (expected == INST_UP))
  File "[...]/ganeti/qa/qa_utils.py", line 640, in RunInstanceCheck
    instance_name = _GetName(instance, operator.attrgetter("name"))
  File "[...]/ganeti/qa/qa_utils.py", line 146, in _GetName
    result = fn(entity)
AttributeError: 'NoneType' object has no attribute 'name'

Trying to add a diskless instance manually:
> gnt-instance add -t diskless -o busybox instancename
Failure: command execution error:
Node 'nodename' returned invalid value for 'vg_size': None

from /var/log/ganeti/master-daemon.log:
2013-05-29 11:52:36,282: ganeti-masterd pid=26558/Jq17/Job14 jqueue:1148 ERROR Op 1/1: Caught exception in INSTANCE_CREATE(helgav-gnt2.hot.corp.google.com)
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1115, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1426, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/lib/python2.6/dist-packages/ganeti/mcpu.py", line 353, in _ExecLU
    lu.CheckPrereq()
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib/instance.py", line 940, in CheckPrereq
    self._RunAllocator()
  File "/usr/lib/python2.6/dist-packages/ganeti/cmdlib/instance.py", line 573, in _RunAllocator
    ial = iallocator.IAllocator(self.cfg, self.rpc, req)
  File "/usr/lib/python2.6/dist-packages/ganeti/masterd/iallocator.py", line 398, in __init__
    self._BuildInputData(req)
  File "/usr/lib/python2.6/dist-packages/ganeti/masterd/iallocator.py", line 620, in _BuildInputData
    self._ComputeClusterData()
  File "/usr/lib/python2.6/dist-packages/ganeti/masterd/iallocator.py", line 451, in _ComputeClusterData
    i_list, config_ndata, has_lvm)
  File "/usr/lib/python2.6/dist-packages/ganeti/masterd/iallocator.py", line 554, in _ComputeDynamicNodeData
    total_disk = get_attr("vg_size")
  File "/usr/lib/python2.6/dist-packages/ganeti/masterd/iallocator.py", line 532, in get_attr
    (nname, attr, value))
OpExecError: Node 'nodename' returned invalid value for 'vg_size': None



```
Originally added on 2013-05-29 11:56:17 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-05-29 12:03:47 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I investigated a bit here. (The excerpt from master-daemon.log is actually not relevant here, please ignore it.) I figured out, that on master, creating diskless instances does not work at all right now. Ganeti creates the instance, which then immediately crashes and is shown as ERROR_down. I think we did not catch this bug, because QA is not run for diskless instances.

I am unassigning this though, because I am not actively working on it.
```
Originally added on 2013-06-06 08:13:26 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I can't reproduce this on stable-2.8 or master.

~# gnt-instance add -t diskless -o busybox instance.example.com
Fri Jun 28 11:22:40 2013  - INFO: Selected nodes for instance instance.example.com via iallocator hail: node.example.com
Fri Jun 28 11:22:41 2013 * creating instance disks...
Fri Jun 28 11:22:41 2013 adding instance instance.example.com to cluster config
Fri Jun 28 11:22:41 2013 * starting instance...
~# gnt-instance list
Instance                          Hypervisor OS      Primary_node               Status     Memory
instance.example.com              xen-pvm    busybox node.example.com           ERROR_down      -

I don't think that it's a problem that the instance is in ERROR_down state after being created. After all, it can't run without any disks/drives/whatever attached to it.

Diskless instances do work, however, with the fake hypervisor (who just pretends that instances can always start).
```
Originally added on 2013-06-28 11:26:51 +0000 UTC.

Changed State: NotRepeatable

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ack, indeed. There are also "ways" to make diskless instances work with real hypervisor, it will just take more toggling (they'll need to have an initrd with busybox, for example)
```
Originally added on 2013-06-28 11:36:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I filed this bug, because this way we cannot run a QA for diskless instances. I did not remember if we ever ran it. If you don't think it is worth the effort, close this bug.
```
Originally added on 2013-07-01 08:46:38 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
We run the VCluster QA using diskless instances now, so they are pretty well covered IMHO. I'll leave the bug closed as WontFix then.
```
Originally added on 2013-07-01 08:54:33 +0000 UTC.

Changed State: WontFix
