### ISSUE TITLE
cluster info fails with --disable-split-query

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#541]
Originally reported of Google Code with ID 485.

```
<b>What steps will reproduce the problem?</b>
1. configure ganeti with --disable-split-query
2. create a cluster, for example with:
gnt-cluster init -s >IP> --master-netdev=eth0 --nic-parameters mode=bridged,link=<SOMELINK> --file-storage-dir=/srv/ganeti/file-storage/ --enabled-disk-templates=drbd,plain,file,diskless <CLUSTERNAME>
3. run gnt-cluster info.

<b>What is the expected output? What do you see instead?</b>

root@...:~# gnt-cluster info
Traceback (most recent call last):
  File "/usr/local/sbin/gnt-cluster", line 21, in <module>
    sys.exit(main.Main())
  File "/usr/local/lib/python2.6/dist-packages/ganeti/client/gnt_cluster.py", line 1658, in Main
    aliases=aliases)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cli.py", line 2550, in GenericMain
    result = func(options, args)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/client/gnt_cluster.py", line 486, in ShowClusterConfig
    utils.CommaJoin(result["enabled_disk_templates"])),
KeyError: 'enabled_disk_templates'

<b>Please use labels and text to provide additional information.</b>
```
Originally added on 2013-06-11 15:24:13 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit fe782deb0635db80a6565dc36bb8ce2ec24bdc85
Author: Helga Velroyen <helgav@google.com>
Date:   Thu Jun 20 11:44:16 2013 +0200

    gnt-cluster info (py): add enabled disk templates
    
    This fixes issue 485. In the python implementation of
    the cluster config info, the enabled_disk_templates
    were missing.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Guido Trotter <ultrotter@google.com>

```
Originally added on 2013-07-03 08:34:02 +0000 UTC.

Mentioned Issue with GoogleCode ID 485 has been migrated to GitHub with ID #541.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-10-30 09:30:16 +0000 UTC.

Changed State: Released
