### ISSUE TITLE
Burnin fails handling non-ascii characters

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#550]
Originally reported of Google Code with ID 494.

```
Here, for example the "-" are not real dashes, and are interpreted as instance names (ok), but then the failure is not clear at all.

# /usr/lib/ganeti/tools/burnin -p -t drbd --disk-size 50G --no-importexport -o goobuntu-precise_server-stable-amd64 --reboot-types=hard,full test-{1..3}.example.com
- Testing global parameters
- Creating instances
 * instance --no-importexport
   on node3.example.com, node4.example.com
 * instance --reboot-types=hard,full
   on node4.example.com, node9.example.com
 * instance test-1.example.com
   on node9.example.com, node3.example.com
 * instance test-2.example.com
   on node3.example.com, node4.example.com
 * instance test-3.example.com
   on node4.example.com, node9.example.com
- Jobs failed: Caught exception: 'ascii' codec can't encode characters in position 16-17: ordinal not in range(128)
- Non-idempotent jobset failed, aborting
- Error detected: opcode buffer follows:


-
-


- Removing instances
Traceback (most recent call last):
 File "/usr/lib/ganeti/tools/burnin", line 21, in <module>
   sys.exit(main.Main())
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 1164, in Main
   return Burner().BurninCluster()
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 1069, in BurninCluster
   self.BurnCreateInstances()
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 273, in wrapper
   val = fn(self, *args, **kwargs)
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 294, in batched
   self.CommitQueue()
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 427, in CommitQueue
   self.queued_ops)
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 350, in MaybeRetry
   val = fn(*args)
 File "/usr/lib/python2.6/dist-packages/ganeti/tools/burnin.py", line 448, in ExecJobSet
   raise BurninFailure()
ganeti.tools.burnin.BurninFailure


```
Originally added on 2013-06-20 08:30:19 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-07-30 11:38:29 +0000 UTC.

Now blocking: 447 (now #503);

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-01-09 11:34:14 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Moving all issues that won't be addressed in 2.11 anymore to 2.12.
```
Originally added on 2014-05-14 11:28:37 +0000 UTC.

Added to Milestone: Release2.12
Removed from Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.
```
Originally added on 2016-12-15 11:06:23 +0000 UTC.

Now blocked by: 447 (now #503);

Changed State: PatchesWelcome
Removed from Milestone: Release2.12

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2016-12-15 11:08:06 +0000 UTC.

No longer blocking: 447 (now #503);
