### ISSUE TITLE
instance add fails due to missing node specs

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#551]
Originally reported of Google Code with ID 495.

```
<b>What steps will reproduce the problem?</b>
1. # gnt-instance add --os-type=busybox --disk-template=drbd -B minmem=512M,maxmem=1G --disk 0:size=512M,name=disk0 instancename

Output:

Failure: command execution error:
'NoneType' object is not iterable

From ma2013-06-20 10:39:35,421: ganeti-masterd pid=2609/Jq1/Job50 jqueue:1148 ERROR Op 1/1: Caught exception in INSTANCE_CREATE(helgav-gnt1.hot.corp.google.com)
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1115, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/jqueue.py", line 1426, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
ster-daemon.log:
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/mcpu.py", line 353, in _ExecLU
    lu.CheckPrereq()
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cmdlib/instance.py", line 944, in CheckPrereq
    self._RunAllocator()
  File "/usr/local/lib/python2.6/dist-packages/ganeti/cmdlib/instance.py", line 574, in _RunAllocator
    self.cfg.GetNodeNames(node_whitelist))
  File "/usr/local/lib/python2.6/dist-packages/ganeti/locking.py", line 87, in sync_function
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/config.py", line 1990, in GetNodeNames
    return self._UnlockedGetNodeNames(node_specs)
  File "/usr/local/lib/python2.6/dist-packages/ganeti/config.py", line 1978, in _UnlockedGetNodeNames
    return [self._UnlockedGetNodeName(node_spec) for node_spec in node_specs]
TypeError: 'NoneType' object is not iterable

```
Originally added on 2013-06-20 10:43:26 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ganeti 2.9.0 has been released
```
Originally added on 2013-11-05 13:56:36 +0000 UTC.

Changed State: Released
