### ISSUE TITLE
Xen instance status collector test fails for exclusive storage

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#568]
Originally reported of Google Code with ID 512.

```
Run QA on a cluster with exclusive storage.
---- 2013-07-03 13:58:56.047471 start Test the Xen instance status collector
Command: ssh NODE2 '/usr/local/lib/ganeti/mon-collector inst-status-xen'
{"name":"inst-status-xen","version":"B","format_version":1,"timestamp":1372852736000000000,"category":"instance","kind":1,"data":{"instances":[],"status":{"code":0,"message":""}}}
Shared connection to NODE2 closed.
Command: ssh NODE2 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE1:NODE2 -B minmem=512M,maxmem=1024M --disk 0:size=512M,name=disk0,spindles=2 --net 0:mac=aa:00:01:11:99:af INSTANCE1'
Failure: prerequisites not met for this operation:
error type: wrong_state, error details:
Disk template drbd not supported with exclusive storage
Shared connection to NODE2 closed.
---- 2013-07-03 13:59:07.924517 time=0:00:11.877046 Test the Xen instance status collector
Traceback (most recent call last):
  File "./ganeti-qa.py", line 923, in <module>
    main()
  File "PATH/ganeti/rapi/client.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 918, in main
    RunQa()
  File "./ganeti-qa.py", line 880, in RunQa
    RunMonitoringTests()
  File "./ganeti-qa.py", line 756, in RunMonitoringTests
    RunTest(qa_monitoring.TestInstStatusCollector)
  File "./ganeti-qa.py", line 95, in RunTest
    retval = fn(*args, **kwargs)
  File "PATH/qa/qa_monitoring.py", line 57, in TestInstStatusCollector
    instance = CreateInstanceByDiskTemplate([node1, node2], template)
  File "PATH/qa/qa_instance_utils.py", line 169, in CreateInstanceByDiskTemplate
    return CreateInstanceDrbd8(nodes, fail=fail)
  File "PATH/qa/qa_instance_utils.py", line 127, in CreateInstanceDrbd8
    constants.DT_DRBD8, fail=fail)
  File "PATH/qa/qa_instance_utils.py", line 99, in _CreateInstanceByDiskTemplateRaw
    AssertCommand(cmd, fail=fail)
  File "PATH/qa/qa_utils.py", line 193, in AssertCommand
    _AssertRetCode(rcode, fail, cmdstr, nodename)
  File "PATH/qa/qa_utils.py", line 163, in _AssertRetCode
    (cmdstr, nodename, rcode))
qa_error.Error: Command 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE1:NODE2 -B minmem=512M,maxmem=1024M --disk 0:size=512M,name=disk0,spindles=2 --net 0:mac=aa:00:01:11:99:af INSTANCE1' on node NODE2 failed, exit code 1

Possible solutions:
- either make QA skip the test execution when exclusive storage is enabled
- or (if possible) use a disk template that is supported for exclusive storage
```
Originally added on 2013-07-03 12:28:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Move non-critical bugs scheduled for 2.8 or 2.9 to 2.11, as in those versions only critical bug fixes will be integrated.
```
Originally added on 2013-10-30 09:48:16 +0000 UTC.

Added to Milestone: Release2.11
Removed from Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Moving all issues that won't be addressed in 2.11 anymore to 2.12.
```
Originally added on 2014-05-14 11:28:37 +0000 UTC.

Added to Milestone: Release2.12
Removed from Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
Removed the milestone as it's long past. As an effort to migrate all our issues to Github, I'll let someone from the community pick it up if they are interested. We'd be happy to accept patches about this.

See https://groups.google.com/forum/#!topic/ganeti/b2-eukpsXpk for more details.
```
Originally added on 2016-12-15 11:10:07 +0000 UTC.

Changed State: PatchesWelcome
Removed from Milestone: Release2.12

**Comment by ge-fa** [comment]
hypervisor: xen
