### ISSUE TITLE
Network query fails

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#579]
Originally reported of Google Code with ID 523.

```
# gnt-cluster --version
gnt-cluster (ganeti v2.8.0beta1-24-gb3907cf) 2.8.0~beta1

<b>What steps will reproduce the problem?</b>
1. from ganeti.cli import GetClient
    c = GetClient(query=True)
    c.QueryNetworks([], [], False)

<b>What is the expected output? What do you see instead?</b>

Expected output: [[], []]

Instead:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "ganeti/luxi.py", line 572, in QueryNetworks
    return self.CallMethod(REQ_QUERY_NETWORKS, (names, fields, use_locking))
  File "ganeti/luxi.py", line 471, in CallMethod
    version=constants.LUXI_VERSION)
  File "ganeti/luxi.py", line 396, in CallLuxiMethod
    raise RequestError(result)
RequestError: Failed to parse request: key 'method': Invalid string value for type LuxiReq: "QueryNetworks"

```
Originally added on 2013-07-10 10:12:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
reproduced.

Will look into this.
```
Originally added on 2013-07-10 12:46:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 795d035de90739e0d7dbad0b13930ee2a94ea770
Author: Klaus Aehlig <aehlig@google.com>
Date:   Thu Jul 11 10:33:50 2013 +0200

    Add luxiReqQueryNetworks to LuxiOp
    
    When the QueryNetwork was introduced as a method, apparently
    it was forgotten in the Haskell world. Add it here as well.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>

```
Originally added on 2013-07-12 14:02:05 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-17 09:24:37 +0000 UTC.

Changed State: Released
Added to Milestone: Release2.8
