### ISSUE TITLE
cfgupgrade to 2.9~rc1 fails

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#650]
Originally reported of Google Code with ID 594.

```
<b>What steps will reproduce the problem?</b>
1. Setup a 2.8 cluster with at least one DRBD instance
2. Install 2.9~rc1
3. cfgupgrade

cfgupgrade fails:
# /usr/share/ganeti/cfgupgrade --debug
Please make sure you have read the upgrade notes for Ganeti 2.9.0~rc1
(available in the UPGRADE file and included in other documentation
formats). Continue with upgrading configuration?
y/[n]/?: y
2013-10-02 11:41:21,735: Found configuration version 2080000 (2.8.0)
2013-10-02 11:41:21,735: Writing configuration file to /var/lib/ganeti/config.data
2013-10-02 11:41:21,737: Backing up /var/lib/ganeti/config.data at /var/lib/ganeti/config.data.backup-2013-10-02_11_41_21.xmcS8K
2013-10-02 11:41:21,769: Testing the new config file...
Traceback (most recent call last):
  File "/usr/share/ganeti/cfgupgrade", line 579, in <module>
    main()
  File "/usr/share/ganeti/cfgupgrade", line 552, in main
    offline=True)
  File "/usr/share/ganeti/ganeti/config.py", line 205, in __init__
    self._OpenConfig(accept_foreign)
  File "/usr/share/ganeti/ganeti/config.py", line 2347, in _OpenConfig
    self._UpgradeConfig()
  File "/usr/share/ganeti/ganeti/config.py", line 2391, in _UpgradeConfig
    self._WriteConfig()
  File "/usr/share/ganeti/ganeti/config.py", line 2455, in _WriteConfig
    config_errors = self._UnlockedVerifyConfig()
  File "/usr/share/ganeti/ganeti/config.py", line 818, in _UnlockedVerifyConfig
    _, duplicates = self._UnlockedComputeDRBDMap()
  File "/usr/share/ganeti/ganeti/config.py", line 1006, in _UnlockedComputeDRBDMap
    instance, disk, my_dict))
  File "/usr/share/ganeti/ganeti/config.py", line 989, in _AppendUsedMinors
    (get_node_name_fn(node_uuid), instance.name))
  File "/usr/share/ganeti/ganeti/config.py", line 2073, in _UnlockedGetNodeName
    raise errors.OpExecError("Unknown node: %s" % node_spec)
ganeti.errors.OpExecError: Unknown node: gntest1.example.com

As is evident, _UnlockedComputeDRBDMap calls _UnlockedGetNodeName with a node name instead of a UUID.
```
Originally added on 2013-10-02 09:25:19 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This call happens in an assert. The actual problem is that node names in logical_id's of disks are not translated to node UUIDs during the upgrade.
```
Originally added on 2013-10-02 09:32:23 +0000 UTC.

Added Labels: Type-Defect Priority-High
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes, I have spotted the error already. It's because cd3b4ff4 replaced LDS_DRBD from frozenset(["drbd8"]) to frozenset(["drbd"]) and cfgupgrade does not consider "drbd8" disks for upgrade.
```
Originally added on 2013-10-02 09:37:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-10-02 09:37:39 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
That's because disk.dev_type holds a disk template type as of 2.9, no longer a logical disk type. Unfortunately, LD_DRBD8 was "drbd8" while DT_DRBD8 is "drbd".

We might have to change this value in disk.dev_type during upgrades, and make sure that LDS_DRBD is no longer used in the codebase (as the LD_* constants should be removed).

I cc'd Helga who originally performed this refactoring.
```
Originally added on 2013-10-02 09:43:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
In the meanwhile, I added an explicit requirement to check the upgrade/downgrade functionality as part of the release procedure, so that future releases should be immediately be OK from this point of view.
```
Originally added on 2013-10-02 09:54:33 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
As far as I remember, I added a routine to the online-update that converts all old ld_lv constants to the new ones. so "drbd8" would be changed to "drbd". With that, I assumed that no changes in cfgupgrade are necessary. If that's not the case, assign it to me and I can have a look on monday.
```
Originally added on 2013-10-02 10:06:12 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
So the only missing piece is downgrades then, as we should convert the new values back to the old ones when going back to 2.8.
```
Originally added on 2013-10-02 11:48:10 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed with:
commit 8cb2b4f49efcac19925947ea25cddcb04e2d1aeb
Author: Helga Velroyen <helgav@google.com>
Date:   Mon Oct 7 16:01:06 2013 +0200

    Fix lint errors
    
    This fixes a couple of lint errors that I missed with
    the patch "Fix upgrade and downgrade regarding
    disk.dev_type".
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Thomas Thrainer <thomasth@google.com>

commit 7187a8772842d3a080e47abee530d94b11e6ecb3
Author: Helga Velroyen <helgav@google.com>
Date:   Mon Oct 7 13:00:01 2013 +0200

    Fix upgrade and downgrade regarding disk.dev_type
    
    The up/downgrade procedure so far did not consider the
    changes in the 'dev_type' attribute of disks. This patch
    adds relevant checks and updates. A related problem
    was that the logical IDs of disks were adjusted depending
    on the dev_type, which made the order of updates not
    arbitrary anymore. To make this more robust, the upgrade
    procedure also considers the old versions of dev_types
    (at least for 2.9).
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Thomas Thrainer <thomasth@google.com>

commit 66a37e7ad70bfb967f3b2cf70beee552dd229581
Author: Helga Velroyen <helgav@google.com>
Date:   Mon Oct 7 13:50:07 2013 +0200

    Rename LDS_DRBD to DTS_DRBD
    
    This patch renames the constant 'LDS_DRBD' to 'DTS_DRBD'
    to make it consistent with the renaming of LD_* constants
    to DT_* constants.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Thomas Thrainer <thomasth@google.com>

```
Originally added on 2013-10-07 14:46:27 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ganeti 2.9.0 has been released
```
Originally added on 2013-11-05 13:56:36 +0000 UTC.

Changed State: Released
