### ISSUE TITLE
Instance console not working in 2.9.0

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#664]
Originally reported of Google Code with ID 608.

```
<b>What steps will reproduce the problem?</b>
1. Create a new KVM instance
2. Try to attach its console
3. The operation fails

<b>What is the expected output? What do you see instead?</b>
# gnt-instance console test
Unhandled Ganeti error: Cannot change directory permissions on '/var/run/ganeti/kvm-hypervisor': [Errno 1] Operation not permitted: '/var/run/ganeti/kvm-hypervisor'

The full backtrace from the master daemon is:
2013-11-08 10:34:23,109: ganeti-masterd pid=2719/ClientReq14 ERROR Unexpected exception
Traceback (most recent call last):
  File "/usr/share/ganeti/ganeti/server/masterd.py", line 106, in RunTask
    result = client_ops.handle_request(method, args)
  File "/usr/share/ganeti/ganeti/server/masterd.py", line 385, in handle_request
    return self._Query(op)
  File "/usr/share/ganeti/ganeti/server/masterd.py", line 466, in _Query
    return proc.ExecOpCode(op, None)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 374, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/share/ganeti/ganeti/cmdlib/instance_query.py", line 217, in Exec
    return self.iq.OldStyleQuery(self)
  File "/usr/share/ganeti/ganeti/cmdlib/base.py", line 539, in OldStyleQuery
    return self.query.OldStyleQuery(self._GetQueryData(lu),
  File "/usr/share/ganeti/ganeti/cmdlib/instance_query.py", line 170, in _GetQueryData
    lu.cfg.GetNodeInfo(inst.primary_node))
  File "/usr/share/ganeti/ganeti/cmdlib/instance_operation.py", line 436, in GetInstanceConsole
    hyper = hypervisor.GetHypervisor(instance.hypervisor)
  File "/usr/share/ganeti/ganeti/hypervisor/__init__.py", line 75, in GetHypervisor
    return cls()
  File "/usr/share/ganeti/ganeti/hypervisor/hv_kvm.py", line 610, in __init__
    utils.EnsureDirs(dirs)
  File "/usr/share/ganeti/ganeti/utils/io.py", line 597, in EnsureDirs
    " '%s': %s" % (dir_name, err))
GenericError: Cannot change directory permissions on '/var/run/ganeti/kvm-hypervisor': [Errno 1] Operation not permitted: '/var/run/ganeti/kvm-hypervisor'

This is due to GetInstanceConsole instantiating a KVMHypervisor object, which calls EnsureDirs during __init__(). The operation fails because masterd is running as a non-privileged user. Also, this is a logic error since operating on an instance residing on an arbitrary node shouldn't impact hypervisor files on the master.

This bug was introduced with the following stanza in commit 8ef418bb92fab256f5013d1be37f96e862ac137d:

diff --git a/lib/cmdlib/instance_operation.py b/lib/cmdlib/instance_operation.py
index e9e5eb2..480ba32 100644
--- a/lib/cmdlib/instance_operation.py
+++ b/lib/cmdlib/instance_operation.py
@@ -440,7 +440,7 @@ def GetInstanceConsole(cluster, instance):
   @rtype: dict
 
   """
-  hyper = hypervisor.GetHypervisorClass(instance.hypervisor)
+  hyper = hypervisor.GetHypervisor(instance.hypervisor)
   # beparams and hvparams are passed separately, to avoid editing the
   # instance and then saving the defaults in the instance itself.
   hvparams = cluster.FillHV(instance)

The same commit also changed XenHypervisor.GetInstanceConsole from a class to an instance method, while leaving it a class method for the other hypervisor classes.
```
Originally added on 2013-11-08 08:49:59 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed with:

commit f92d9674fe5ee2d65b1fb1809695988123388e89
Author: Helga Velroyen <helgav@google.com>
Date:   Tue Nov 12 14:45:53 2013 +0100

    Fix retrieval of xen command in class method
    
    This patch fixes issue 608. When introducing the
    configurability of the xen toolstack in commit
    8ef418bb92, the hypervisor api was accidentally changed
    in a way that let to this error in KVM.
    
    Signed-off-by: Helga Velroyen <helgav@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>

```
Originally added on 2013-11-12 15:10:03 +0000 UTC.

Mentioned Issue with GoogleCode ID 608 has been migrated to GitHub with ID #664.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-11-13 12:27:00 +0000 UTC.

Changed State: Released

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-05 12:56:02 +0000 UTC.
