### ISSUE TITLE
TypeError when GetKVMOutput fails

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#672]
Originally reported of Google Code with ID 616.

```
2013-11-19 14:28:03,882: ganeti-noded pid=10682 noded:197 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/server/noded.py", line 181, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/local/lib/python2.7/dist-packages/ganeti/server/noded.py", line 617, in perspective_instance_start
    return backend.StartInstance(instance, startup_paused, trail)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/backend.py", line 1666, in StartInstance
    hyper.StartInstance(instance, block_devices, startup_paused)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/hypervisor/hv_kvm.py", line 1702, in StartInstance
    kvmhelp = self._GetKVMOutput(kvmpath, self._KVMOPT_HELP)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/hypervisor/hv_kvm.py", line 1774, in _GetKVMOutput
    " ".join(cls._KVMOPTS_CMDS[option]))
TypeError: sequence item 0: expected string, list found


It should be possible to reproduce this having a wrong kvm path, for example
```
Originally added on 2013-11-19 13:33:48 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
What kind of fix do you suggest exactly here? A more meaningful error message saying that it was not possible to get a proper output from KVM?
```
Originally added on 2013-11-27 13:22:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-11-27 13:54:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 3ddc765099fd74b291956dc721ff0ab0186f8e7e
Author: Jose A. Lopes <jabolopes@google.com>
Date:   Fri Nov 22 14:44:02 2013 +0100

    Fix error printing
    
    Fixes issue 616.
    
    Signed-off-by: Jose A. Lopes <jabolopes@google.com>
    Reviewed-by: Michele Tartara <mtartara@google.com>
```
Originally added on 2013-11-27 14:54:37 +0000 UTC.

Mentioned Issue with GoogleCode ID 616 has been migrated to GitHub with ID #672.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-13 16:18:23 +0000 UTC.

Changed State: Released
