### ISSUE TITLE
Split brain problem

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#673]
Originally reported of Google Code with ID 617.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

Primary Node:
hspace (ganeti-htools) version v0.3.1
compiled with ghc 7.4
running on linux x86_64

gnt-cluster (ganeti v2.4.5) 2.4.5

Software version: 2.4.5
Internode protocol: 2040000
Configuration format: 2040000
OS api version: 20
Export interface: 0

Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise

What distribution are you using on secondary node?
Distributor ID:	Ubuntu
Description:	Ubuntu 12.10
Release:	12.10
Codename:	quantal


<b>What steps will reproduce the problem?</b>
On Primary node:
1.root@primary:~# drbd-overview 
  0:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
  1:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
  2:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
  3:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
  4:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
  5:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
  7:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
  9:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 10:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 11:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 14:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 15:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 18:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 20:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 22:??not-found??  WFConnection Primary/Unknown UpToDate/Inconsistent C r----- 
 23:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 34:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 38:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 39:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 
 41:??not-found??  WFConnection Primary/Unknown UpToDate/DUnknown     C r----- 

2.On secondary Node:
root@secondary:~# drbd-overview 
  2:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
  5:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
  9:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
 10:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
 11:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
 18:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 
 22:??not-found??  StandAlone Secondary/Unknown Inconsistent/DUnknown r----- 

3.root@mprimary:~# drbdsetup /dev/drbdX invalidate
/dev/drbd38: State change failed: (-2) Need access to UpToDate data


<b>What is the expected output? What do you see instead?</b>

I need to recover the nodes from split brain.

<b>Please provide any additional information below.</b>

The secondary node has been upgradeD to 12.10 quantal and the primary node is running 12.04 LTS precise. The drbd.conf is empty and there is no .res file. Any drbdadm command output " No resources defined".

The vms has been failedover to the primary node. Afraid to do anything that might bring the primary node down as this could bring the whole production down.

What is the best safe way to resolve this. 

Please help.

```
Originally added on 2013-11-21 08:21:21 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

If I understood correctly, you updated your secondary node while there were secondary DRBD devices on it, right? This broke the DRBD connections, and they have to be re-established by Ganeti so DRBD can resync the secondaries and bring them back to a consistent state.

As you are using a very old version of Ganeti, with which I personally don't have a lot of experience, I can only give you some general advice.

Try to re-activate the instance disks. This should re-configure DRBD and start syncing the disks. This command should be executed for all affected instances:

gnt-instance activate-disks $INSTANCE

Please test this with one instance first and verify that the DRBD devices go back to a syncing state and eventually to the Connected state.

If this doesn't work, try replacing the disks on the secondary with:

gnt-instance replace-disks -s $INSTANCE


As I don't see a Ganeti bug here and as we don't support 2.4.5 any more, I'll mark this bug as WontFix. Please post general questions about Ganeti to ganeti@googlegroups.com next time, there are more people who could potentially help you with your issues.

```
Originally added on 2013-11-21 09:12:12 +0000 UTC.

Changed State: WontFix

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi

Thank you for your willingness to help me.

But there is no connection between the two nodes. I cant run the commands
on secondary node.

Running the commnads on primary node give the below results:

gnt-instance activate-disks INSTANCENAME
Thu Nov 21 11:35:46 2013  - WARNING: Could not prepare block device disk/0
on node SECONDARY_NODE (is_primary=False, pass=1): Error while assembling
disk: drbd41: can't attach local disk: /dev/drbd41: Failure: (127) Device
minor not allocated\n
Failure: command execution error:
Cannot activate block devices

gnt-instance activate-disks tracker.sanren.ac.za
Thu Nov 21 11:35:46 2013  - WARNING: Could not prepare block device disk/0
on node SECONDARY_NODE (is_primary=False, pass=1): Error while assembling
disk: drbd41: can't attach local disk: /dev/drbd41: Failure: (127) Device
minor not allocated\n
Failure: command execution error:
Cannot activate block devices
```
Originally added on 2013-11-21 09:37:52 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The problem is that the DRBD device on the secondary is not created at all.
Did you try `gnt-instance replace-disks -s $INSTANCE`?


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 09:49:23 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes I did try it:

root@secondary:~# gnt-instance replace-disks -s INSTANCENAME
Failure: prerequisites not met for this operation:
This is not the master node, please connect to node 'PRIMARY_NODE' and
rerun the command

There has been so many strange things.When I check the drbd.conf file it's
empty and no resources are defined.

I am new to ganeti + drbd and dont know how to create/define the resources
```
Originally added on 2013-11-21 09:56:54 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
All gnt-* commands have to be run on the master node, so you have to issue
those commands there rather than on the secondary (which apparently is not
the master in your case).

Ganeti does not use the drbd.conf file or drbdadm. It rather issues
drbdsetup commands directly where appropriate and stores all the relevant
configuration in the Ganeti config rather than in drbd.conf.


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 10:02:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you for the explanation.

gnt-instance activate-disks INST commnad run succesfully on the master
node, but the gnt-node info INST shows
on primary:   /dev/drbd1 (147:1) in sync, status *DEGRADED*
      on secondary: /dev/drbd1 (147:1) in sync, status *DEGRADED*
*UNCERTAIN STATE*

gnt-instance replace-disks -s INST shows:
root@mort:~# gnt-instance replace-disks -s INST
Thu Nov 21 12:16:07 2013 Replacing disk(s) 0 for INST
Thu Nov 21 12:16:07 2013 STEP 1/6 Check device existence
Thu Nov 21 12:16:07 2013  - INFO: Checking disk/0 on PRMARY_NODE
Thu Nov 21 12:16:07 2013  - INFO: Checking disk/0 on SECONDARY_NODE
Thu Nov 21 12:16:10 2013  - INFO: Checking volume groups
Thu Nov 21 12:16:11 2013 STEP 2/6 Check peer consistency
Thu Nov 21 12:16:11 2013  - INFO: Checking disk/0 consistency on node
PRIMARY_NODE
Failure: command execution error:
Node PRIMARY_NODE has degraded storage, unsafe to replace disks for
instance INST
```
Originally added on 2013-11-21 10:19:27 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Did the DRBD status change on either the primary or the secondary once you
issued `gnt-instance activate-disks`?

And do you have only two nodes at your disposal? I just realized that
replacing disks on the secondary only works if the disks are in consistent
state (that's why you get the error message), but you could move the
secondary to another node temporarily to fix the situation (with
`gnt-instance replace-disks -n $NEW_SECONDARY $INSTANCE).


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 10:39:29 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes I have two nodes at my disposal. The DRBD status did not change.

I have failedover the instances to the primary node. I was running the
gnt-instance replace-disks command on the instance running on the master
node. The master node is also in the  inconsistent state.

root@master:~# /etc/init.d/drbd status
drbd driver loaded OK; device status:
version: 8.3.11 (api:88/proto:86-96)
srcversion: 71955441799F513ACA6DA60
m:res             cs            ro               ds                     p
 mounted  fstype
0:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
1:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
2:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
3:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
4:??not-found??   WFConnection  Primary/Unknown  UpToDate/DUnknown      C
5:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
7:??not-found??   WFConnection  Primary/Unknown  UpToDate/DUnknown      C
9:??not-found??   WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
10:??not-found??  WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
11:??not-found??  WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
14:??not-found??  WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
15:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
18:??not-found??  WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
20:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
22:??not-found??  WFConnection  Primary/Unknown  UpToDate/Inconsistent  C
23:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
34:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
39:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
41:??not-found??  WFConnection  Primary/Unknown  UpToDate/DUnknown      C
```
Originally added on 2013-11-21 11:05:25 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
If you don't have the option to recreate the secondaries on a third node,
you could try to manually reconnect the secondary DRBD devices to the
primaries.
But I have to warn you, that's somewhat dangerous and tricky...

Basically, you have to invoke the following command for every disk on the
secondary:

drbdsetup /dev/drbd$IDX net ipv4:$SECONDARY_IP_OF_SECONDARY:$PORT
ipv4:$SECONDARY_IP_OF_PRIMARY:$PORT -A discard-zero-changes -B consensus -a
md5 -x $SECRET

Where
 $IDX is the index of the disk you are about to fix
 $SECONDARY_IP_OF_SECONDARY is the secondary IP of the secondary node. See
`gnt-node info $SECONDARY_NODE | grep secondary`
 $SECONDARY_IP_OF_PRIMARY is the secondary IP of the primary node. See
`gnt-node info $PRIMARY_NODE | grep secondary`

For $PORT and $SECRET you have to look in Ganetis configuration file. On
you master node, perform `cat /var/lib/ganeti/config.data | python
-mjson.tool | less`. This should give you a raw view the configuration.
In there you have to find the disk you are about to fix. Disk objects are
nested under the instance object they belong to. Search for "logical_id"
arrays, but only take those into account which have 6 elements. The meaning
of those fields is (in order):
 * primary node (of the DRBD device)
 * secondary node (of the DRBD device)
 * port
 * minor on primary
 * minor on secondary
 * secret

So now you have to find the "logical_id" array which has the right
secondary node at position 2 and at its 5th position (minor on secondary)
the $IDX you want to fix. Now you can find the $PORT and $SECRET in this
array at position 3 and 6 respectively.

With all this information you can invoke the command mentioned above, which
should reconnect the DRBD device to the primary, which in turn should
resync the disks again.

Sorry that there is no simpler solution for this with only two nodes.



-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 11:59:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thank you, but I wont try this now. Will request a permission from my
manager first.

Urgent, on of my instances is now showing up but ERROR_down. It was failed
over to the primary node and it was running untill I killed some drbdX
processes.

I have activated the disks with other instances and they are now running.
But this one is showing errors:
root@master:~# gnt-instance activate-disks instancename
Thu Nov 21 14:17:16 2013  - WARNING: Could not prepare block device disk/0
on node master (is_primary=False, pass=1): Error while assembling disk:
drbd41: can't attach local disk: /dev/drbd41: Failure: (127) Device minor
not allocated\n
Thu Nov 21 14:17:32 2013  - WARNING: Could not prepare block device disk/0
on node master (is_primary=True, pass=2): Error while assembling disk:
drbd41: can't attach local disk: /dev/drbd41: Failure: (127) Device minor
not allocated\n
Failure: command execution error:
Cannot activate block devices



please help, this is a production vm
```
Originally added on 2013-11-21 12:19:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
What do you mean with "killed some drbdX processes"? DRBD does work as a
kernel module, so what exactly did you kill?

Can you take a look at /var/log/ganeti/node-daemon.log on the primary and
secondary node and look for errors when you perform an activate-disks?
Please post the relevant sections here.


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 12:37:36 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
on Primary node:

013-11-21 15:02:26,782: ganeti-noded pid=29513 ERROR drbd41: can't attach
local disk: /dev/drbd41: Failure: (127) Device minor not allocated

2013-11-21 15:02:26,782: ganeti-noded pid=29513 ERROR Error while
assembling disk: drbd41: can't attach local disk: /dev/drbd41: Failure:
(127) Device minor not allocated
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/backend.py", line
1510, in BlockdevAssemble
    result = _RecursiveAssembleBD(disk, owner, as_primary)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/backend.py", line
1486, in _RecursiveAssembleBD
    r_dev = bdev.Assemble(disk.dev_type, disk.physical_id, children,
disk.size)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/bdev.py", line 2109,
in Assemble
    device.Assemble()
  File "/usr/local/lib/python2.7/dist-packages/ganeti/bdev.py", line 1736,
in Assemble
    self._FastAssemble()
  File "/usr/local/lib/python2.7/dist-packages/ganeti/bdev.py", line 1826,
in _FastAssemble
    self._children[1].dev_path, self.size)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/bdev.py", line 1356,
in _AssembleLocal
    _ThrowError("drbd%d: can't attach local disk: %s", minor, result.output)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/bdev.py", line 72, in
_ThrowError
    raise errors.BlockDeviceError(msg)
BlockDeviceError: drbd41: can't attach local disk: /dev/drbd41: Failure:
(127) Device minor not allocated

2013-11-21 15:02:26,784: ganeti-noded pid=29513 INFO
155.232.195.1:37032PUT /blockdev_assemble HTTP/1.1 200

On secondary:
2013-11-21 15:10:06,322: ganeti-noded pid=9460 INFO 155.232.195.1:52053 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:10:06,432: ganeti-noded pid=9461 INFO 155.232.195.1:52055 PUT
/jobqueue_rename HTTP/1.1 200
2013-11-21 15:10:06,453: ganeti-noded pid=9462 INFO 155.232.195.1:52056 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:10:06,473: ganeti-noded pid=9463 INFO 155.232.195.1:52057 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:10:06,498: ganeti-noded pid=9464 INFO 155.232.195.1:52058 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:10:06,521: ganeti-noded pid=9465 INFO 155.232.195.1:52059 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:10:15,802: ganeti-noded pid=9466 INFO 155.232.195.1:52060 PUT
/blockdev_assemble HTTP/1.1 200
2013-11-21 15:10:16,664: ganeti-noded pid=9495 INFO 155.232.195.1:52066 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,244: ganeti-noded pid=9525 INFO 155.232.195.1:52163 PUT
/jobqueue_rename HTTP/1.1 200
2013-11-21 15:15:02,273: ganeti-noded pid=9526 INFO 155.232.195.1:52164 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,292: ganeti-noded pid=9527 INFO 155.232.195.1:52165 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,314: ganeti-noded pid=9528 INFO 155.232.195.1:52166 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,340: ganeti-noded pid=9529 INFO 155.232.195.1:52167 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,360: ganeti-noded pid=9530 INFO 155.232.195.1:52168 PUT
/all_instances_info HTTP/1.1 200
2013-11-21 15:15:02,409: ganeti-noded pid=9531 INFO 155.232.195.1:52170 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,430: ganeti-noded pid=9532 INFO 155.232.195.1:52171 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:02,451: ganeti-noded pid=9533 INFO 155.232.195.1:52172 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:05,166: ganeti-noded pid=9534 INFO 155.232.195.1:52173 PUT
/node_info HTTP/1.1 200
2013-11-21 15:15:05,190: ganeti-noded pid=9537 INFO 155.232.195.1:52176 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:05,423: ganeti-noded pid=9538 INFO 155.232.195.1:52177 PUT
/jobqueue_rename HTTP/1.1 200
2013-11-21 15:15:05,445: ganeti-noded pid=9539 INFO 155.232.195.1:52178 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:05,465: ganeti-noded pid=9540 INFO 155.232.195.1:52179 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:05,486: ganeti-noded pid=9541 INFO 155.232.195.1:52180 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:05,510: ganeti-noded pid=9543 INFO 155.232.195.1:52181 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:07,495: ganeti-noded pid=9544 INFO 155.232.195.1:52182 PUT
/lv_list HTTP/1.1 200
2013-11-21 15:15:07,520: ganeti-noded pid=9546 INFO 155.232.195.1:52185 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:07,611: ganeti-noded pid=9547 INFO 155.232.195.1:52186 PUT
/jobqueue_rename HTTP/1.1 200
2013-11-21 15:15:07,633: ganeti-noded pid=9548 INFO 155.232.195.1:52187 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:07,653: ganeti-noded pid=9549 INFO 155.232.195.1:52188 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:07,679: ganeti-noded pid=9550 INFO 155.232.195.1:52189 PUT
/jobqueue_update HTTP/1.1 200
2013-11-21 15:15:07,703: ganeti-noded pid=9552 INFO 155.232.195.1:52190 PUT
/jobqueue_update HTTP/1.1 200
```
Originally added on 2013-11-21 13:16:09 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ganeti is using the --create-device switch of drbdsetup, so DRBD should
allocate the minor for you. Maybe you are already at the maximum number of
minors configured for DRBD.
Please check this using

cat /sys/module/drbd/parameters/minor_count


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 13:40:12 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The minor-count is 32 on primary node and 128 on secondary node
```
Originally added on 2013-11-21 13:56:45 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Please try to increase it (to something like 250) via

echo 250 > /sys/module/drbd/parameters/minor_count

on both nodes.

Does activate-disks work then?


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-21 14:04:47 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Will increase it.

Still not working, maybe the problem could be that the instance is on
ERROR_down status. I am scared to try it on running instances

The drbd status no is connected with some drbd devices:
Secondary Node
0:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
1:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
2:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
3:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
4:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
5:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
7:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
9:??not-found??   Connected     Secondary/Primary  UpToDate/UpToDate      C
10:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
11:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
14:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
15:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
18:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
20:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
22:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
23:??not-found??  Connected     Secondary/Primary  UpToDate/UpToDate      C
34:??not-found??  WFConnection  Secondary/Unknown  Inconsistent/DUnknown  C
38:??not-found??  WFConnection  Primary/Unknown    UpToDate/DUnknown      C
39:??not-found??  WFConnection  Secondary/Unknown  Inconsistent/DUnknown  C
41:??not-found??  WFConnection  Secondary/Unknown  Inconsistent/DUnknown  C


Primary Node:
root@mort:~# service drbd status
drbd driver loaded OK; device status:
version: 8.3.11 (api:88/proto:86-96)
srcversion: 71955441799F513ACA6DA60
m:res             cs         ro                 ds                 p
 mounted  fstype
0:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
1:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
2:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
3:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
4:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
5:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
7:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
9:??not-found??   Connected  Primary/Secondary  UpToDate/UpToDate  C
10:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
11:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
14:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
15:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
18:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
20:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
22:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C
23:??not-found??  Connected  Primary/Secondary  UpToDate/UpToDate  C


But these " ??not-found??" are not looking good.
```
Originally added on 2013-11-21 14:12:48 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Could you please post the output of `cat /proc/drbd` on the primary and
secondary node? And are your /dev/drbdX devices present?

Minor 0-23 look good to me, the other four are a bit weird. I'd suspect
that those are blocking the instance from starting again, so try to shut
them down on the secondary (after having verified that they actually belong
to the down instance). Use `drbdsetup /dev/drbd34 down` for that. Note that
this is save, as the data is stored on the underlying LVM volumes, so no
data loss can happen with this operation. Then try to restart the instance
which is down.


-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-22 08:16:19 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
PRIMARY:
 0:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  1:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  2:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  3:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  4:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  5:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  7:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
  9:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 10:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 11:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 14:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 15:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 18:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 20:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 22:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----
 23:??not-found??  Connected Primary/Secondary UpToDate/UpToDate C r-----


SECONDARY:
0:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C r-----
  1:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  2:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  3:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  4:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  5:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  7:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
  9:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 10:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 11:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 14:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 15:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 18:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 20:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 22:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 23:??not-found??  Connected    Secondary/Primary UpToDate/UpToDate C
r-----
 41:??not-found??  WFConnection Secondary/Unknown UpToDate/DUnknown C
r-----
this is after bringind down the problematic drbd devices and trying to
restart the device drbd41, that instance is on ERROR_ down. How do you
 create a minor on primary, because its says it is not active on primary.
```
Originally added on 2013-11-22 08:36:21 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Which version(s) of DRBD do you use on your nodes? My content of /proc/drbd
is quite different (see below), that's puzzling me a bit.
Did you increase the minor_count on your primary node? Did you double-check
that it actually increased? As 41 > 32, it might very well be that you
still hit this limitation. You could work around this problem by assigning
a lower minor on the primary to the affected disks, but that would require
manual fiddling in the Ganeti configuration file.

Here my output of `cat /proc/drbd`:

version: 8.3.15 (api:88/proto:86-97)
GIT-hash: 0ce4d235fc02b5c53c1c52c53433d11a694eab8c build by root@example.com,
2012-12-20 21:52:53
 0: cs:Connected ro:Primary/Secondary ds:UpToDate/UpToDate C r-----
    ns:12791468 nr:0 dw:8597164 dr:5123788 al:951 bm:256 lo:0 pe:0 ua:0
ap:0 ep:1 wo:f oos:0
 1: cs:Unconfigured
 2: cs:Unconfigured
 3: cs:Connected ro:Primary/Secondary ds:UpToDate/UpToDate C r-----
    ns:212555264 nr:0 dw:181097984 dr:35817420 al:11526 bm:1920 lo:0 pe:0
ua:0 ap:0 ep:1 wo:f oos:0
 4: cs:Unconfigured
 5: cs:Unconfigured



-- 
Thomas Thrainer | Software Engineer | thomasth@google.com |

Google Germany GmbH
Dienerstr. 12
80331 M�nchen

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Gesch�ftsf�hrer: Graham Law, Christine Elizabeth Flores
```
Originally added on 2013-11-22 08:49:23 +0000 UTC.
