### ISSUE TITLE
Assertion Error: Node locks differ from node resource locks

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#678]
Originally reported of Google Code with ID 622.

```
What software version are you running?

 2.8.2

<b>What distribution are you using?</b>

Debian

<b>What steps will reproduce the problem?</b>

 Not sure. Probably, creating many instances with opportunistic locking.

<b>What is the expected output? What do you see instead?</b>

 Instance creation fails with assertion error:

Job ID: 689408
  Status: error
  Received:         2013-11-22 17:03:41.419819
  Processing start: 2013-11-22 17:03:41.554081 (delta 0.134262s)
  Processing end:   2013-11-22 17:03:45.652421 (delta 4.098340s)
  Total processing time: 4.232602 seconds
  Opcodes:
    OP_INSTANCE_CREATE
      Status: error
      Processing start: 2013-11-22 17:03:41.554081
      Execution start:  2013-11-22 17:03:43.491267
      Processing end:   2013-11-22 17:03:45.652372
      Input fields:
        beparams: {'auto_balance': True, 'minmem': 1024, 'vcpus': 1, 'maxmem': 1024}
        comment: None
        conflicts_check: True
        debug_level: 0
        depends: None
        disk_template: drbd
        disks: {'size': 10240}
        dry_run: False
        force_variant: False
        hvparams: {'serial_console': False, 'security_model': 'pool'}
        hypervisor: kvm
        iallocator: hail
        identify_defaults: False
        ignore_ipolicy: False
        instance_name: snf-95836
        ip_check: False
        mode: create
        name_check: False
        nics: {'ip': '192.168.4.23', 'name': 'snf-nic-258532'}
        opportunistic_locking: True
        os_type: snf-image+default
        osparams: {..}
        pnode: node2
        priority: 0
        reason: ['gnt:library:rlib2:instances', '', 1385132621136025856],['gnt:opcode:op_instance_create', 'job=689408;index=0', 1385132621419811072]
        snode: node1
        source_shutdown_timeout: 120
        start: True
        tags: 
        wait_for_sync: False
      Result:
        OpExecError
        [Internal assertion error: please report this as a bug.
Error message: 'Node locks differ from node resource locks'; location:
  File "/usr/share/ganeti/ganeti/cmdlib/instance.py", line 956, in CheckPrereq
    "Node locks differ from node resource locks"
]
      Execution log:
        1:2013-11-22 17:03:45.630453:message  - INFO: Selected nodes for instance snf-95836 via iallocator hail: node2, node1


<b>Please provide any additional information below.</b>

Snippet from master-daemon log file:

2013-11-22 17:03:45,630: ganeti-masterd pid=20904/Jq10/Job689408/I_CREATE INFO Selected nodes for instance snf-95836 via iallocator hail: node2, node1
2013-11-22 17:03:45,651: ganeti-masterd pid=20904/Jq10/Job689408/I_CREATE ERROR Detected AssertionError
Traceback (most recent call last):
  File "/usr/share/ganeti/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 353, in _ExecLU
    lu.CheckPrereq()
  File "/usr/share/ganeti/ganeti/cmdlib/instance.py", line 956, in CheckPrereq
    "Node locks differ from node resource locks"
AssertionError: Node locks differ from node resource locks
2013-11-22 17:03:45,651: ganeti-masterd pid=20904/Jq10/Job689408 ERROR Op 1/1: Caught exception in INSTANCE_CREATE(snf-95836)
Traceback (most recent call last):
  File "/usr/share/ganeti/ganeti/jqueue.py", line 1115, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/share/ganeti/ganeti/jqueue.py", line 1426, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/share/ganeti/ganeti/mcpu.py", line 418, in _LockAndExecLU
    " location:\n%s" % (str(err), err_info[-1]))
OpExecError: Internal assertion error: please report this as a bug.
Error message: 'Node locks differ from node resource locks'; location:
  File "/usr/share/ganeti/ganeti/cmdlib/instance.py", line 956, in CheckPrereq
    "Node locks differ from node resource locks"
```
Originally added on 2013-11-22 16:08:34 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi all,

just an idea about this:

LUInstanceCreate takes all 'NODE' and 'NODE_RES' locks. If opportunistic locking is
used, 'opportunistic_locking' is set for both levels. Is there any possibility that
due to opportunistic locking, one can acquire a 'NODE_RES' lock without first acquiring the
'NODE' lock ?
```
Originally added on 2013-11-22 17:24:22 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi,

In case the previews comment is true, then I think ExpandNames() in
LUInstanceCreate should have *only* NODE level in opportunistic mode
while a DeclareLocks() will try to acquire all NODE_RES level locks
already acquired in NODE level. And finally pass the NODE_RES owned locks as
node_whitelist in _CreateInstanceAllocRequest(). What do you think?

```
Originally added on 2013-11-22 18:13:10 +0000 UTC.

Added Labels: Type-Defect Priority-Critical Component-logic Component-instances Component-master

**Comment by Ganeti-Issues-Migrator** [comment]
```
Yes, I also think we can't just set NODE level and NODE_RES level locks to opportunistic and hope that we get the same set.
I'll fix that accordingly, thanks for investigating!
```
Originally added on 2013-11-25 09:16:44 +0000 UTC.

Added to Milestone: Release2.8

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed with:

commit 4289f617a9d603a9763caf5b4e0231e1061714c7
Author: Thomas Thrainer <thomasth@google.com>
Date:   Mon Nov 25 11:37:06 2013 +0100

    Fix NODE/NODE_RES locking in LUInstanceCreate
    
    Both NODE and NODE_RES locks were acquired opportunistically if so
    requested by the user. LUInstanceCreate requires, however, that the
    actually locked elements on NODE and NODE_RES level are the same.
    
    This patch changes the locking of NODE_RES such that those locks are not
    acquired opportunistically any more. Instead, the mandatory locks are
    set to the acquired NODE locks once they are actually granted.
    
    This fixes issue 622.
    
    Signed-off-by: Thomas Thrainer <thomasth@google.com>
    Reviewed-by: Petr Pudlak <pudlak@google.com>
```
Originally added on 2013-11-27 13:07:50 +0000 UTC.

Mentioned Issue with GoogleCode ID 622 has been migrated to GitHub with ID #678.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-13 16:18:23 +0000 UTC.

Changed State: Released
