### ISSUE TITLE
Ganeti Cluster verify doen't notice that confd on master is down

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#681]
Originally reported of Google Code with ID 625.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".
root@node1 ~ # gnt-cluster --version
gnt-cluster (ganeti v2.8.2) 2.8.2
root@node1 ~ # gnt-cluster version
Software version: 2.8.2
Internode protocol: 2080000
Configuration format: 2080000
OS api version: 20
Export interface: 0
VCS version: v2.8.2

AND

root@joe /etc/ganeti/hooks # gnt-cluster --version
gnt-cluster (ganeti v2.7.2) 2.7.2
root@joe /etc/ganeti/hooks # gnt-cluster version
Software version: 2.7.2
Internode protocol: 2070000
Configuration format: 2070000
OS api version: 20
Export interface: 0


<b>What distribution are you using?</b>
root@joe ~ # cat /etc/debian_version
7.2


<b>What steps will reproduce the problem?</b>
1. ... dont know ...
2a. root@joe ~ # service ganeti restart
Restarting Ganeti cluster:ganeti-confd...done.
ganeti-rapi...done.
ganeti-masterd...done.
ganeti-noded...done.
ganeti-noded...done.
ganeti-masterd...ERROR:root:Can't activate master IP address: Failed to start the master IP. Script return value: 1, output: 'RTNETLINK answers: File exists
Error during the activation of the master IP address
'
done.
ganeti-rapi...done.
ganeti-confd...Traceback (most recent call last):
  File "/usr/sbin/ganeti-confd", line 11, in <module>
    import ganeti.server.confd as main
ImportError: No module named confd
failed (exit code 1).
2b. Alternativly (skip 1. and) kill the confd with `kill [pid-of-confd]`
3. root@joe ~ # gnt-cluster verify
Submitted jobs 1260, 1261
Waiting for job 1260 ...
Sun Nov 24 21:52:30 2013 * Verifying cluster config
Sun Nov 24 21:52:30 2013 * Verifying cluster certificate files
Sun Nov 24 21:52:30 2013 * Verifying hypervisor parameters
Sun Nov 24 21:52:30 2013 * Verifying all nodes belong to an existing group
Waiting for job 1261 ...
Sun Nov 24 21:52:31 2013 * Verifying group 'default'
Sun Nov 24 21:52:31 2013 * Gathering data (2 nodes)
Sun Nov 24 21:52:31 2013 * Gathering disk information (2 nodes)
Sun Nov 24 21:52:31 2013 * Verifying configuration file consistency
Sun Nov 24 21:52:31 2013 * Verifying node status
Sun Nov 24 21:52:31 2013 * Verifying instance status
Sun Nov 24 21:52:31 2013 * Verifying orphan volumes
Sun Nov 24 21:52:31 2013 * Verifying N+1 Memory redundancy
Sun Nov 24 21:52:31 2013 * Other Notes
Sun Nov 24 21:52:31 2013   - NOTICE: 1 non-redundant instance(s) found.
Sun Nov 24 21:52:32 2013 * Hooks Results

<b>What is the expected output? What do you see instead?</b>
An Error / Warning that the Confd isn't running.
No Error, no Warning, no Notice or any other message.


<b>Please provide any additional information below.</b>

on node1 (Ganeti 2.8) i killed the confd with `kill [pid]`
on joe (Ganeti 2.7) the confd thinks it doesn't exist - don't know why, the error doen't sound logic - files are there and nothing was changed (just /etc/default/ganeti, but that was reverted)
ganeti-confd...Traceback (most recent call last):
  File "/usr/sbin/ganeti-confd", line 11, in <module>
    import ganeti.server.confd as main
ImportError: No module named confd
failed (exit code 1).
... but i'll have a deeper look at that because i think this is a problem with the installation

and the listen is missing (of course):
root@joe ~ # netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          20671       4078/sshd       
tcp6       0      0 :::1811                 :::*                    LISTEN      0          67558       13458/python    
tcp6       0      0 :::22                   :::*                    LISTEN      0          20673       4078/sshd       
tcp6       0      0 :::5080                 :::*                    LISTEN      0          69798       13550/python    

```
Originally added on 2013-11-24 21:07:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
gnt-cluster verify is not meant to verify the Ganeti installation in its current state. Rather, it verifies the health of nodes and instances and checks for certain left-overs from failed jobs.

I don't think that it would make sense to include checks for a working installation in gnt-cluster verify, as this job would probably not run correctly if the installation is broken (especially for more complex failure situations).

Having said that, I know that the installation of Ganeti will get more complicated in the future. There is work currently in progress to split Ganeti into more daemons, so a tool to verify the runtime state of the Ganeti installation would come in handy. I'll file a feature request for that against a newer version of Ganeti.

Regarding your additional problem (... No module named confd ...): This does sound like an installation issue indeed. Did you manage to resolve it for your case?
```
Originally added on 2013-11-25 15:24:49 +0000 UTC.

Changed State: WontFix
