### ISSUE TITLE
select.poll is not thread safe (python issue 8865)

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#683]
Originally reported of Google Code with ID 627.

```
<b>What steps will reproduce the problem?</b>
1. Using Debian Jessie
2. Branch master
3. Run `make check'

<b>What is the expected output? What do you see instead?</b>

Running ganeti.locking_unittest.py
.................FException in thread Thread-248:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./test/py/ganeti.locking_unittest.py", line 2460, in _Acquire
    lock.acquire(shared=shared, test_notify=next.set)
  File "/tmp/gntbuild.SDQ66CwJ/ganeti/locking.py", line 769, in acquire
    return self.__acquire_unlocked(shared, timeout, priority)
  File "/tmp/gntbuild.SDQ66CwJ/ganeti/locking.py", line 732, in __acquire_unlocked
    wait_condition.wait(timeout)
  File "/tmp/gntbuild.SDQ66CwJ/ganeti/locking.py", line 347, in wait
    cond.wait(timeout)
  File "/tmp/gntbuild.SDQ66CwJ/ganeti/locking.py", line 286, in wait
    wait_fn(timeout)
  File "/tmp/gntbuild.SDQ66CwJ/ganeti/locking.py", line 136, in __call__
    result = self._poller.poll(remaining_time)
RuntimeError: concurrent poll() invocation


<b>Please use labels and text to provide additional information.</b>

It seems like select.poll is not thread safe in python. This is a known issue [1], that was reported back in 2010. Until now the python code did not handle this. It seems like a patch that makes python raise a RuntimeError has been introduced between python version 2.7.3 (wheezy version) and python version 2.7.5 (jessie version).

This issue is by no means presented only in Debian Jessie. As it is stated here [1], invoking select.poll.poll() concurrently from multiple threads frequently yields garbage in one thread.

Since masterd has multiple workers (threads) that are competing for the same locks this issue can cause severe inconsistencies.

[1] http://bugs.python.org/issue8865
```
Originally added on 2013-11-28 13:16:06 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thanks for the extensive report. Could you also attach here your patch and sign the Google CLA? I can then test tomorrow how much impact it has on speed and apply it.

Thanks,

Guido

```
Originally added on 2013-11-28 14:53:36 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
Note: I didn't open this issue, but thanks to whoever did the work for me!

Minor correction: it's from version 2.7.6 (not 2.7.5) that Python raises a RuntimeError[1] when it detects the use of a select.poll.poll() object from multiple threads.

Regards,
Daniel Néri

[1] http://hg.python.org/cpython/raw-file/99d03261c1ba/Misc/NEWS
```
Originally added on 2013-11-28 23:12:36 +0000 UTC.

Attachments: 
[no-concurrent-poll.patch](https://storage.googleapis.com/google-code-attachments/ganeti/issue-627/comment-2/no-concurrent-poll.patch)

**Comment by Ganeti-Issues-Migrator** [comment]
```
Thanks for the report. I double checked the situation and I can clarify that:

- this affects Ganeti usage with newer versions of Python, as python refuses to share the poller between threads at any rate, as such I will send a patch similar to the one Daniel proposed. I will not apply Daniel's patch directly, as since we're recreating the poller at each "wait" call it makes more sense to do it directly in _SingleNotifyPipeConditionWaiter directly.

- this does *not* affect Ganeti with older versions of python, as the conditions for triggering the bug (quoting: "while poll_poll in thread 1 is parsing its result, another thread 2 calling poll may overwrite...") can't hold: in fact Ganeti threads hold the condition lock while parsing results, and as such are protected.

Considering this, I will apply the patch just to Ganeti 2.9, which is the latest stable. I don't believe it needs to be fixed in older versions, as they act correctly for their versions of python, and use this in a thread safe manner.

```
Originally added on 2013-11-29 10:26:31 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-11-29 10:31:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-09 13:47:00 +0000 UTC.

Changed State: Fixed
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 546c5100dece06b92ffa0804b6838b5125450bde
Author: Guido Trotter <ultrotter@google.com>
Date:   Fri Nov 29 11:09:07 2013 +0100

    SingleNotifyPipeCondition: don't share pollers
    
    As widely known Ganeti uses a better[1] lock condition notification
    library based on operating system pipes.
    
    Inside this library we were using a shared poller for all threads
    waiting for a condition. While poller is not thread safe, since (1)
    we're holding the condition lock while calling poll and while parsing
    results, and (2) we don't reuse the poller between different conditions,
    or with newer fds our usage *is* actually safe. Unfortunately newer
    versions of python take a hand-holding approach and don't trust us to do
    the right thing. As such we are forced to create a new poller each time
    we call wait.
    
    This costs one system call more per wait, but practical measurements
    have shown no significant impact on Ganeti. This is also a temporary
    measures as newer versions will get away with the threading altogether
    and move job schedulers to luxid.
    
    The patch is losely based on a patch submitted by Daniel Néri, but has
    been modified to reduce even further the scope of the poller variable to
    just the waiter class.
    
    [1] because I say so.
    [1 bis] also because it produces fairer results, avoids possible
    starvation and eliminates busy-wait polling.
    [2] http://bugs.python.org/issue8865
    
    Signed-off-by: Guido Trotter <ultrotter@google.com>
    Reviewed-by: Michele Tartara <mtartara@google.com>

```
Originally added on 2013-12-09 13:47:13 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-13 16:17:10 +0000 UTC.

Changed State: Released
