### ISSUE TITLE
Migration of ext type instances fail due to physical_id missing

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#689]
Originally reported of Google Code with ID 633.

```
<b>What steps will reproduce the problem?</b>
1. Add a second disk in a test instance with ext disk template
2. Migrate the instance
3. Accept instance fails

Target node's noded-daemon log:

2013-12-03 14:25:02,853: ganeti-noded pid=1799 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/ganeti/server/noded.py", line 181, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/ganeti/server/noded.py", line 645, in perspective_accept_instance
    return backend.AcceptInstance(instance, info, target)
  File "/usr/share/ganeti/ganeti/backend.py", line 1537, in AcceptInstance
    _GatherAndLinkBlockDevs(instance)
  File "/usr/share/ganeti/ganeti/backend.py", line 1315, in _GatherAndLinkBlockDevs
    device = _RecursiveFindBD(disk)
  File "/usr/share/ganeti/ganeti/backend.py", line 2112, in _RecursiveFindBD
    return bdev.FindDevice(disk, children)
  File "/usr/share/ganeti/ganeti/bdev.py", line 3419, in FindDevice
    disk.params)
  File "/usr/share/ganeti/ganeti/bdev.py", line 2994, in __init__
    raise ValueError("Invalid configuration data %s" % str(unique_id))
ValueError: Invalid configuration data None
2013-12-03 14:25:02,863: ganeti-noded pid=1799 INFO 192.168.2.2:51978 POST /accept_instance HTTP/1.1 200



<b>What is the expected output? What do you see instead?</b>

This happens because when adding a disk in 2.8, SetDiskID() does not get
invoked. As a result disk entries inside config.data have no physical_id.
In case of EXT, before accepting the instance we invoke _GatherAndLinkBlockDevices(). This takes `instance` as an argument which includes disks without physical_id and thus FindDevice() fails.

As far as I know physical_id is meant to be deprecated right? In
future releases it will be removed from the file. So I propose
the following fix:

--- a/lib/cmdlib/instance_migration.py
+++ b/lib/cmdlib/instance_migration.py
@@ -709,6 +709,8 @@ class TLMigrateInstance(Tasklet):
       self._WaitUntilSync()
 
     self.feedback_fn("* preparing %s to accept the instance" % target_node)
+    for disk in instance.disks:
+      self.cfg.SetDiskID(disk, target_node)
     result = self.rpc.call_accept_instance(target_node,
                                            instance,
                                            migration_info,


Any comments on that?

```
Originally added on 2013-12-03 13:12:44 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-06 13:01:22 +0000 UTC.

Changed State: Started

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi Dimitris, the fix you suggests seems good to me. Could you please send it as a patch on the mailing list so that I can push it?

Thanks.
```
Originally added on 2013-12-09 10:39:51 +0000 UTC.

Changed State: NeedFeedback

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit a63985f3d1612d7e4c05f9eeb65572e7c9ef11f2
Author: Dimitris Aragiorgis <dimara@grnet.gr>
Date:   Mon Dec 9 14:00:27 2013 +0200

    SetDiskID() before accepting an instance
    
    SetDiskID() fills physical_id slot of a Disk object.
    
    LUInstanceSetParams() does not invoke SetDiskID() upon creation of a
    new disk. As a result the physical_id slot of the Disk object in
    config data is missing.
    
    In case of ext disk template, in AcceptInstance() we invoke
    _GatherAndLinkBlockDevices(). This takes `instance` as an argument
    which includes current disks info. So, after adding a disk,
    migration of ext instances will fail because FindDevice() expects
    the physical_id slot.
    
    With this patch we invoke SetDiskID() for every disk of the instance
    before accept_instance() RPC.
    
    Fixes Issue 633.
    
    Signed-off-by: Dimitris Aragiorgis <dimara@grnet.gr>
    Signed-off-by: Michele Tartara <mtartara@google.com>
    Reviewed-by: Michele Tartara <mtartara@google.com>

```
Originally added on 2013-12-09 12:56:24 +0000 UTC.

Mentioned Issue with GoogleCode ID 633 has been migrated to GitHub with ID #689.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-13 16:18:23 +0000 UTC.

Changed State: Released
