### ISSUE TITLE
make htest should depend on opcode generation

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#690]
Originally reported of Google Code with ID 634.

```
<b>What steps will reproduce the problem?</b>
1. make clean
2. make test/hs/htest
3. ./test/hs/htest

<b>What is the expected output? What do you see instead?</b>

Some haskell tests fail due to the python opcodes and constants not being generated.

For example:

Runtime:
  LogFiles: [Failed]
python exited with error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ganeti/constants.py", line 33, in <module>
    from ganeti._constants import *
ImportError: No module named _constants

Running a 'make' before 'make test/hs/htest' fixes the problem, but I think htest should have proper dependecy rather than requiring this extra step.

<b>Please use labels and text to provide additional information.</b>

```
Originally added on 2013-12-05 15:33:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 543937ce198e2655edaf80ae6e98986fb29bb0bf
Author: Jose A. Lopes <jabolopes@google.com>
Date:   Thu Dec 5 17:06:45 2013 +0100

    Fix 'htest' related targets dependencies
    
    This fixes issue 634.
    
    Signed-off-by: Jose A. Lopes <jabolopes@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>
```
Originally added on 2013-12-06 08:51:39 +0000 UTC.

Mentioned Issue with GoogleCode ID 634 has been migrated to GitHub with ID #690.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-04-28 09:06:47 +0000 UTC.

Changed State: Released
