### ISSUE TITLE
gnt-debug test-jobqueue fails in some setups

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#702]
Originally reported of Google Code with ID 646.

```
While in most setups 'gnt-debug test-jobqueue' works fine with luxid,
in some setups it fails, apparently to a race. The relevant parts of
the log files are attached. The 20:37:51,473 update of
/var/lib/ganeti/queue/job-10 seems to be missed by luxid; also note that
the file read at 20:37:52,897349 shows the job waiting but this change
of state is not propagated back to the WaitForJobChange reqeust.

master:

2013-12-17 20:37:51,472: ganeti-masterd pid=19769/Jq13/Job10 jqueue:1230 INFO Op 1/1: opcode TEST_JQUEUE waiting for locks
2013-12-17 20:37:51,473: ganeti-masterd pid=19769/Jq13/Job10/TEST_JQUEUE test:118 DEBUG Creating temporary socket at /tmp/tmpLcMdQy/sock
2013-12-17 20:37:51,473: ganeti-masterd pid=19769/Jq13/Job10/TEST_JQUEUE jqueue:2244 DEBUG Writing job 10 to /var/lib/ganeti/queue/job-10
2013-12-17 20:37:52,897: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:37:55,902: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:37:58,926: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:38:01,951: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:38:04,976: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:38:07,980: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:38:11,005: ganeti-masterd pid=19769/MainThread daemon:178 INFO Accepted connection from pid=19845, uid=0, gid=0
2013-12-17 20:38:11,547: ganeti-masterd pid=19769/Jq13/Job10 jqueue:1150 ERROR Op 1/1: Caught exception in TEST_JQUEUE
Traceback (most recent call last):
  File "/usr/share/ganeti/2.11/ganeti/jqueue.py", line 1117, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/share/ganeti/2.11/ganeti/jqueue.py", line 1428, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/share/ganeti/2.11/ganeti/mcpu.py", line 533, in ExecOpCode
    lu.ExpandNames()
  File "/usr/share/ganeti/2.11/ganeti/cmdlib/test.py", line 194, in ExpandNames
    self._Notify(True, constants.JQT_EXPANDNAMES, None)
  File "/usr/share/ganeti/2.11/ganeti/cmdlib/test.py", line 180, in _Notify
    errcls)
  File "/usr/share/ganeti/2.11/ganeti/cmdlib/test.py", line 132, in _NotifyUsingSocket
    raise errcls("Client didn't connect in time (%s)" % err)
OpPrereqError: Client didn't connect in time (timed out)
2013-12-17 20:38:11,548: ganeti-masterd pid=19769/Jq13/Job10 jqueue:2244 DEBUG Writing job 10 to /var/lib/ganeti/queue/job-10

luxi:

2013-12-17 20:37:51,134715000000 UTC: ganeti-luxid pid=19845 INFO Starting jobs: 10
2013-12-17 20:37:51,134637000000 UTC: ganeti-luxid pid=19845 DEBUG Result (truncated): 10
2013-12-17 20:37:51,134881000000 UTC: ganeti-luxid pid=19845 INFO Successfully handled SubmitJob
2013-12-17 20:37:51,135374000000 UTC: ganeti-luxid pid=19845 DEBUG Received message: RecvOk "{\"args\": [10, [\"status\"], null, null, 29], \"method\": \"WaitForJobChange\", \"version\": 2110000}\n"
2013-12-17 20:37:51,135464000000 UTC: ganeti-luxid pid=19845 DEBUG Request: WaitForJobChange (JobId {fromJobId = 10}) ["status"] JSNull JSNull 29
2013-12-17 20:37:51,137823000000 UTC: ganeti-luxid pid=19845 DEBUG Inspecting fields ["status"] of job 10
2013-12-17 20:37:51,138048000000 UTC: ganeti-luxid pid=19845 DEBUG Updates for job 10 are [["queued"],[]]
2013-12-17 20:37:51,138193000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 changed during setup of inotify
2013-12-17 20:37:51,138291000000 UTC: ganeti-luxid pid=19845 DEBUG Result (truncated): [["queued"],[]]
2013-12-17 20:37:51,138369000000 UTC: ganeti-luxid pid=19845 INFO Successfully handled WaitForJobChange
2013-12-17 20:37:51,138556000000 UTC: ganeti-luxid pid=19845 DEBUG Received message: RecvOk "{\"args\": [10, [\"status\"], [\"queued\"], null, 29], \"method\": \"WaitForJobChange\", \"version\": 2110000}\n"
2013-12-17 20:37:51,138646000000 UTC: ganeti-luxid pid=19845 DEBUG Request: WaitForJobChange (JobId {fromJobId = 10}) ["status"] (JSArray [JSString (JSONString {fromJSString = "queued"})]) JSNull 29
2013-12-17 20:37:51,138836000000 UTC: ganeti-luxid pid=19845 DEBUG Inspecting fields ["status"] of job 10
2013-12-17 20:37:51,139063000000 UTC: ganeti-luxid pid=19845 DEBUG Updates for job 10 are [["queued"],[]]
2013-12-17 20:37:51,239270000000 UTC: ganeti-luxid pid=19845 DEBUG Notified of change in /var/lib/ganeti/queue/job-10
2013-12-17 20:37:51,266933000000 UTC: ganeti-luxid pid=19845 DEBUG Inspecting fields ["status"] of job 10
2013-12-17 20:37:51,267105000000 UTC: ganeti-luxid pid=19845 DEBUG Updates for job 10 are [["queued"],[]]
2013-12-17 20:37:52,894927000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:37:52,895036000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:37:52,895113000000 UTC: ganeti-luxid pid=19845 INFO Rereading job 10
2013-12-17 20:37:52,897349000000 UTC: ganeti-luxid pid=19845 DEBUG Read job 10, staus is JOB_STATUS_WAITING
2013-12-17 20:37:52,897429000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:37:55,901821000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:37:55,901927000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:37:55,902000000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:37:55,902065000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:37:58,926377000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:37:58,926481000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:37:58,926551000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:37:58,926614000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:38:01,950962000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:01,951078000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:38:01,951147000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:38:01,951209000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:38:02,992812000000 UTC: ganeti-luxid pid=19845 DEBUG Config-reader watcher timer fired
2013-12-17 20:38:04,975652000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:04,975761000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:38:04,975861000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:38:04,975925000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:38:07,980181000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:07,980284000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:38:07,980353000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:38:07,980416000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:38:11,004939000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:11,005043000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:38:11,005124000000 UTC: ganeti-luxid pid=19845 DEBUG File /var/lib/ganeti/queue/job-10 not changed on disk.
2013-12-17 20:38:11,005189000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: [10]
2013-12-17 20:38:14,029406000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:14,029555000000 UTC: ganeti-luxid pid=19845 DEBUG Checking if /var/lib/ganeti/queue/job-10 changed on disk.
2013-12-17 20:38:14,029631000000 UTC: ganeti-luxid pid=19845 INFO Rereading job 10
2013-12-17 20:38:14,029862000000 UTC: ganeti-luxid pid=19845 DEBUG Read job 10, staus is JOB_STATUS_ERROR
2013-12-17 20:38:14,029938000000 UTC: ganeti-luxid pid=19845 INFO Finished jobs: (10,JOB_STATUS_ERROR)
2013-12-17 20:38:14,030007000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: []
2013-12-17 20:38:17,054371000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:17,054547000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: []
2013-12-17 20:38:20,018939000000 UTC: ganeti-luxid pid=19845 DEBUG Config-reader watcher timer fired
2013-12-17 20:38:20,079180000000 UTC: ganeti-luxid pid=19845 DEBUG Job queue watcher timer fired
2013-12-17 20:38:20,079283000000 UTC: ganeti-luxid pid=19845 INFO Waiting jobs: []; running jobs: []
2013-12-17 20:38:20,239660000000 UTC: ganeti-luxid pid=19845 DEBUG Inspecting fields ["status"] of job 10
2013-12-17 20:38:20,240009000000 UTC: ganeti-luxid pid=19845 DEBUG Updates for job 10 are [["error"],[[1,[1387312671,473141],"jqueue-test",["/tmp/tmpLcMdQy/sock","expandnames",null]]]]
2013-12-17 20:38:20,240135000000 UTC: ganeti-luxid pid=19845 DEBUG Result (truncated): [["error"],[[1,[1387312671,473141],"jqueue-test",["/tmp/tmpLcMdQy/sock","expandnames",null]]]]
2013-12-17 20:38:20,240216000000 UTC: ganeti-luxid pid=19845 INFO Successfully handled WaitForJobChange
2013-12-17 20:38:20,252298000000 UTC: ganeti-luxid pid=19845 DEBUG Received message: RecvConnClosed
2013-12-17 20:38:20,252472000000 UTC: ganeti-luxid pid=19845 DEBUG Connection closed

```
Originally added on 2013-12-18 09:42:45 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit e97cce9f38201a4bab5a6547fcae20d1076789de
Author: Klaus Aehlig <aehlig@google.com>
Date:   Fri Dec 20 13:32:56 2013 +0100

    Reinstantiate inotify after a lost file
    
    When watching a file, reinstantiate the inotify if notified
    of an event that removes the watch. Such events are likely
    to happen, as our usual way to "modify" a file is to atomically
    replace it by another one.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Helga Velroyen <helgav@google.com>

```
Originally added on 2013-12-20 13:51:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2013-12-20 15:12:19 +0000 UTC.

Changed State: Fixed
Added to Milestone: Release2.11
Removed from Milestone: Release2.12

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-04-28 09:06:47 +0000 UTC.

Changed State: Released
