### ISSUE TITLE
drbd84 QA is flaky

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#703]
Originally reported of Google Code with ID 647.

```
The drbd84 QA is flaky. It frequently fails due to race conditions when releasing devices. Since flaky tests are rather annoying we should either fix the flakiness in the implementation if possible or at least in the QA.

Example of such a failed QA:

<<<< 2013-12-19 07:11:03.317911 start [TestRapiInstanceRemove] Test removing instance via RAPI
DELETE /2/instances/INSTANCE
GET /2/jobs/758
Thu Dec 19 07:11:47 2013  - WARNING: Could not remove disk 0 on node NODE, continuing anyway: Can't lvremove: exited with exit code 5 -   Logical volume xenvg/a6c2dff7-4f74-4555-bd5b-2c04c9958745.disk0 is used by another device.\n
---- FAILED [TestRapiInstanceRemove] Test removing instance via RAPI: Can't remove instance's disks
>>>> 2013-12-19 07:11:48.864398 time=0:00:45.546487 [TestRapiInstanceRemove] Test removing instance via RAPI
Traceback (most recent call last):
  File "./ganeti-qa.py", line 1025, in <module>
    main()
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/ganeti/rapi/client.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 1020, in main
    RunQa()
  File "./ganeti-qa.py", line 905, in RunQa
    RunTest(qa_rapi.TestRapiInstanceRemove, rapi_instance, use_client)
  File "./ganeti-qa.py", line 103, in RunTest
    retval = fn(*args, **kwargs)
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/qa/qa_utils.py", line 713, in wrapper
    result = fn(*args, **kwargs)
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/qa/qa_rapi.py", line 641, in TestRapiInstanceRemove
    _WaitForRapiJob(job_id)
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/qa/qa_rapi.py", line 510, in _WaitForRapiJob
    cli.StdioJobPollReportCb())
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/ganeti/rapi/client_utils.py", line 98, in PollJob
    return cli.GenericPollJob(job_id, RapiJobPollCb(rapi_client), reporter)
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/ganeti/cli.py", line 2101, in GenericPollJob
    errors.MaybeRaise(msg)
  File "/buildbot/qa-drbd84/qa-drbd84-full/build/ganeti/errors.py", line 501, in MaybeRaise
    raise errcls(*args)
ganeti.errors.OpExecError: Can't remove instance's disks
program finished with exit code 1
elapsedTime=20392.453384
```
Originally added on 2013-12-19 09:09:31 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
There's a fix in 2.8(?) which retries to remove LV's when they are still used by some other process. This should fix the flakiness of the test, but we should keep an eye on it after the merge to master.
```
Originally added on 2013-12-19 10:03:31 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Seems to no longer occur.
```
Originally added on 2014-05-14 11:21:49 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-14 11:22:07 +0000 UTC.

Changed State: Released
