### ISSUE TITLE
RpcCallJobqueueUpdate does not virtualize the file path

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#721]
Originally reported of Google Code with ID 665.

```
<b>What steps will reproduce the problem?</b>
1. Set up a vcluster with a couple of nodes.
2. Run ./cmd 'gnt-cluster verify'
3. Get lots of error messages about ssh problems:

Thu Jan  9 14:10:36 2014 * Verifying node status
Thu Jan  9 14:10:36 2014   - ERROR: node node1: ssh communication with node 'node11': ssh problem: ssh_exchange_identification: Connection closed by remote host\'r\n
Thu Jan  9 14:10:36 2014   - ERROR: node node1: ssh communication with node 'node10': ssh problem: ssh_exchange_identification: Connection closed by remote host\'r\n
Thu Jan  9 14:10:36 2014   - ERROR: node node1: ssh communication with node 'node20': ssh problem: ssh_exchange_identification: Connection closed by remote host\'r\n
Thu Jan  9 14:10:36 2014   - ERROR: node node1: ssh communication with node 'node22': ssh problem: ssh_exchange_identification: Connection closed by remote host\'r\n
Thu Jan  9 14:10:36 2014   - ERROR: node node1: ssh communication with node 'node3': ssh problem: ssh_exchange_identification: Connection closed by remote host\'r\n
...

Digging through the code I found out that the problem is in Rpc.hs RpcCallJobqueueUpdate. The path in the variable 'file_name' of the RPC call needs to be virtualized, but this is missing here.

For comparison, the virtualization in the python code is done in jqueue.py, CallJqUpdate:

virt_file_name = vcluster.MakeVirtualPath(file_name)

So basically, the functionality of "MakeVirtualPath" needs to be implemented in Haskell.

<b>Please use labels and text to provide additional information.</b>

To verify, that it is indeed this call, I logged the jobqueue_update RPC calls in the backend and marked the haskell ones with "ZZZ". Excerpt from node2/var/log/ganeti/node-daemon.log:

2014-01-09 13:56:37,764: ganeti-noded pid=30803 ERROR XXX backend file_name before /###-VIRTUAL-PATH-###,/var/lib/ganeti/queue/job-2
2014-01-09 13:56:37,764: ganeti-noded pid=30803 ERROR XXX backend file_name after /srv/ganeti/vcluster/node2/var/lib/ganeti/queue/job-2
2014-01-09 13:56:37,766: ganeti-noded pid=30803 INFO 192.0.2.11:35877 POST /jobqueue_update HTTP/1.1 200
2014-01-09 13:56:40,742: ganeti-noded pid=30867 ERROR XXX backend file_name before ZZZ/srv/ganeti/vcluster/node1/var/lib/ganeti/queue/serialZZZ
2014-01-09 13:56:40,742: ganeti-noded pid=30867 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 182, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 1055, in perspective_jobqueue_update
    return backend.JobQueueUpdate(file_name, content)
  File "/usr/local/share/ganeti/2.11/ganeti/backend.py", line 3503, in JobQueueUpdate
    file_name = vcluster.LocalizeVirtualPath(file_name)
  File "/usr/local/share/ganeti/2.11/ganeti/vcluster.py", line 260, in LocalizeVirtualPath
    assert os.path.isabs(path)
AssertionError
2014-01-09 13:56:40,745: ganeti-noded pid=30867 INFO 192.0.2.11:35883 POST /jobqueue_update HTTP/1.1 200
2014-01-09 13:56:40,885: ganeti-noded pid=30868 ERROR XXX backend file_name before ZZZ/srv/ganeti/vcluster/node1/var/lib/ganeti/queue/job-3ZZZ
2014-01-09 13:56:40,886: ganeti-noded pid=30868 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 182, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 1055, in perspective_jobqueue_update
    return backend.JobQueueUpdate(file_name, content)
  File "/usr/local/share/ganeti/2.11/ganeti/backend.py", line 3503, in JobQueueUpdate
    file_name = vcluster.LocalizeVirtualPath(file_name)
  File "/usr/local/share/ganeti/2.11/ganeti/vcluster.py", line 260, in LocalizeVirtualPath
    assert os.path.isabs(path)
AssertionError


```
Originally added on 2014-01-09 14:18:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-01-09 14:23:30 +0000 UTC.

Added Labels: Type-Defect Priority-Medium
Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
Some corrections, the quoted exception is the wrong one (the quoted one complains about the path being not absolute due to the prepended 'ZZZ', just ignore it). The correct exception was:

2014-01-09 11:54:26,901: ganeti-noded pid=26300 INFO 192.0.2.11:52705 POST /hooks_runner HTTP/1.1 200
2014-01-09 11:54:26,993: ganeti-noded pid=26302 ERROR Error in RPC call 
Traceback (most recent call last):
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 182, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/share/ganeti/2.11/ganeti/server/noded.py", line 1055, in perspective_jobqueue_update
    return backend.JobQueueUpdate(file_name, content)
  File "/usr/local/share/ganeti/2.11/ganeti/backend.py", line 3502, in JobQueueUpdate
    file_name = vcluster.LocalizeVirtualPath(file_name)
  File "/usr/local/share/ganeti/2.11/ganeti/vcluster.py", line 266, in LocalizeVirtualPath
    raise RuntimeError("Path '%s' is not a virtual path" % path)
RuntimeError: Path '/srv/ganeti/vcluster/node1/var/lib/ganeti/queue/job-2' is not a virtual path 


I debugged some more and I realized that the ssh error message, that gnt cluster verify shows is not related to this exception. I suspect it is due to my test setup, so ignore it for now. However, the exception in the RPC handling is still a valid issue, I think.
```
Originally added on 2014-01-09 17:56:24 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-01-14 12:10:16 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 4a43365cd0de9afcf4d4aff3ba7fed22d31fb94b
Author: Klaus Aehlig <aehlig@google.com>
Date:   Fri Jan 17 10:56:07 2014 +0100

    Add a module to support virtual clusters
    
    Virtual clusters are an efficient way to test how Ganeti behaves
    on a large cluster without requiring a large number of machines.
    Now that more tasks like job replication are done by luxid, provide
    that functionality in Haskell as well.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Petr Pudlak <pudlak@google.com>

commit 7767641518492828c207eb891b95f3abc41d7ab1
Author: Klaus Aehlig <aehlig@google.com>
Date:   Fri Jan 17 11:37:34 2014 +0100

    When updating job queue, support virtual paths
    
    When replicating parts of the job queue, allow for virtual
    paths in the RPC call. In this way, replication will also
    work correctly in a vcluster setup. Note that makeVirtualPath
    lives in IO, and hence cannot be part of the pure encoding
    function of the RPC.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Petr Pudlak <pudlak@google.com>

```
Originally added on 2014-01-20 09:56:48 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-04-28 09:06:48 +0000 UTC.

Changed State: Released
