### ISSUE TITLE
Removing all disks from filebased instance ends up with unmanageable instance

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#753]
Originally reported of Google Code with ID 697.

```
When doing the following, I end up with an unmanageable instance:

# gnt-cluster --version
gnt-cluster (ganeti v2.9.3-1-g94e252a) 2.9.3

# gnt-instance add -t file --disk=0:size=1G .... test_1
# gnt-instance modify --disk 0:remove test_1
Failure: command execution error:
list index out of range
# gnt-instance remove test_1
This will remove the volumes of the instance test_1 (including
mirrors), thus removing all the data of the instance. Continue?
y/[n]/?: y
Failure: command execution error:
list index out of range


In the 'master-daemon.log' file I see the following:

For the `add disk` command:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1115, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1426, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 374, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance.py", line 3390, in Exec
    self._RemoveDisk)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance.py", line 2209, in _ApplyContainerMods
    (item, changes) = create_fn(addidx, params, private)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance.py", line 3239, in _CreateNewDisk
    (file_driver, file_path) = self.instance.disks[0].logical_id
IndexError: list index out of range

For the `remove instance` command:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1115, in _ExecOpCodeUnlocked
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/jqueue.py", line 1426, in _WrapExecOpCode
    return execop_fn(op, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 517, in ExecOpCode
    calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 459, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 468, in _LockAndExecLU
    result = self._LockAndExecLU(lu, level + 1, calc_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 407, in _LockAndExecLU
    result = self._ExecLU(lu)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/mcpu.py", line 374, in _ExecLU
    result = _ProcessResult(submit_mj_fn, lu.op, lu.Exec(self.Log))
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance.py", line 1675, in Exec
    RemoveInstance(self, feedback_fn, self.instance, self.op.ignore_failures)
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance_utils.py", line 229, in RemoveInstance
    if not RemoveDisks(lu, instance, ignore_failures=ignore_failures):
  File "/usr/local/lib/python2.7/dist-packages/ganeti/cmdlib/instance_utils.py", line 294, in RemoveDisks
    file_storage_dir = os.path.dirname(instance.disks[0].logical_id[1])
IndexError: list index out of range


It seems that in case of filebased disk templates, ganeti uses the
first disk of an instance to determine the 'file_storage_dir', but it
doesn't handle the case where all disks of an instance has been
removed.
```
Originally added on 2014-01-29 13:35:24 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Reproduced the problem. Thanks for the report. This definitely should be fixed for the 2.9.4 release.
```
Originally added on 2014-01-29 15:50:28 +0000 UTC.

Added Labels: Type-Defect Priority-High
Changed State: Accepted
Added to Milestone: Release2.9

**Comment by Ganeti-Issues-Migrator** [comment]
```
I'll have a look
```
Originally added on 2014-01-30 13:44:21 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 099ed3b201d5d2d0a022e7f40b51b8cc34bb8beb
Author: Klaus Aehlig <aehlig@google.com>
Date:   Thu Jan 30 16:30:00 2014 +0100

    Gracefully handle degraded instances in verification
    
    The current code assumes that every instance either is of type
    diskless or has at least one disk. However, with the option to
    remove individual disk degraded 0-disk non-diskless instances
    can occur. While such instances usually are not useful, Ganeti
    still should be operational in their presence.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>

commit 7e219d1bfad48beadb79dc7362b726c8ba7a59b8
Author: Klaus Aehlig <aehlig@google.com>
Date:   Thu Jan 30 16:08:06 2014 +0100

    Be aware of the degraded case when cleaning up an instance
    
    In the case of a degraded file-based instance, the file storage directory
    for that instance cannot be obtained by looking at the first disk. Use
    the standard location, computed from first principles, in this case.
    
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Hrvoje Ribicic <riba@google.com>


```
Originally added on 2014-01-30 16:30:46 +0000 UTC.

Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
Ganeti 2.9.4 has been released
```
Originally added on 2014-02-10 14:22:51 +0000 UTC.

Changed State: Released
