### ISSUE TITLE
Can't compute PV info for vg xenvg

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#819]
Originally reported of Google Code with ID 763.

```
QA fails with the error "Can't compute PV info for vg xenvg", most likely being introduced by the recent changes in DRBD syncing. This seems pretty sporadic and is most likely also present in 2.11 and master by now.

<<<< 2014-03-19 12:26:43.203444 start [TestClusterModifyDiskTemplates] gnt-cluster modify --enabled-disk-templates=
Command: ssh NODE7 'gnt-cluster modify --enabled-disk-templates=drbd,plain,file --ipolicy-disk-templates=drbd,plain,file --vg-name=xenvg'
Wed Mar 19 12:26:43 2014 Cluster LVM configuration already in desired state, not changing
...
Wed Mar 19 12:27:10 2014 Cluster LVM configuration already in desired state, not changing
Command: ssh NODE7 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE7:NODE8.com -B minmem=512M,maxmem=1G --disk 0:size=512M,name=disk0 INSTANCE1'
Wed Mar 19 12:27:22 2014 * creating instance disks...
Wed Mar 19 12:27:23 2014  - WARNING: Device creation failed
Failure: command execution error:
Can't create block device <LogicalVolume(/dev/xenvg/5960fa66-bdb7-4150-8cc5-8e2d30ca6a2a.disk0_data, not visible, size=512m)> on node NODE8 for instance INSTANCE1: Can't create block device: Can't compute PV info for vg xenvg
---- FAILED [TestClusterModifyDiskTemplates] gnt-cluster modify --enabled-disk-templates=: Command 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE7:NODE8 -B minmem=512M,maxmem=1G --disk 0:size=512M,name=disk0 INSTANCE1' on node NODE7 failed, exit code 1
>>>> 2014-03-19 12:27:23.922797 time=0:00:40.719353 [TestClusterModifyDiskTemplates] gnt-cluster modify --enabled-disk-templates=
---- BLOCK FAILED [RunClusterTests] Runs tests related to gnt-cluster: Command 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE7:NODE8 -B minmem=512M,maxmem=1G --disk 0:size=512M,name=disk0 INSTANCE1' on node NODE7 failed, exit code 1
^^^^ BLOCK 2014-03-19 12:27:23.922983 time=0:03:47.643019 [RunClusterTests] Runs tests related to gnt-cluster
Traceback (most recent call last):
  File "./ganeti-qa.py", line 1011, in <module>
    main()
  File "/buildbot/qa-kvm/qa-kvm-quick/build/ganeti/rapi/client.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 1006, in main
    RunQa()
  File "./ganeti-qa.py", line 842, in RunQa
    RunTestBlock(RunClusterTests)
  File "./ganeti-qa.py", line 145, in RunTestBlock
    return fn(*args, **kwargs)
  File "./ganeti-qa.py", line 251, in RunClusterTests
    RunTestIf(test, fn)
  File "./ganeti-qa.py", line 122, in RunTestIf
    RunTest(fn, *args, **kwargs)
  File "./ganeti-qa.py", line 101, in RunTest
    retval = fn(*args, **kwargs)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_cluster.py", line 597, in TestClusterModifyDiskTemplates
    instance = qa_instance.CreateInstanceByDiskTemplate(nodes, instance_template)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_instance_utils.py", line 169, in CreateInstanceByDiskTemplate
    return CreateInstanceDrbd8(nodes, fail=fail)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_instance_utils.py", line 127, in CreateInstanceDrbd8
    constants.DT_DRBD8, fail=fail)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_instance_utils.py", line 99, in _CreateInstanceByDiskTemplateRaw
    AssertCommand(cmd, fail=fail)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_utils.py", line 199, in AssertCommand
    _AssertRetCode(rcode, fail, cmdstr, nodename)
  File "/buildbot/qa-kvm/qa-kvm-quick/build/qa/qa_utils.py", line 169, in _AssertRetCode
    (cmdstr, nodename, rcode))
qa_error.Error: Command 'gnt-instance add --os-type=busybox --disk-template=drbd --node=NODE7:NODE8.com -B minmem=512M,maxmem=1G --disk 0:size=512M,name=disk0 INSTANCE1' on node NODE7 failed, exit code 1
program finished with exit code 1
elapsedTime=333.293589
```
Originally added on 2014-03-19 12:57:36 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Luckily (phew), this was not caused by mysterious DRBD syncing errors, but by a PV that was set as unallocatable. Doing a pvchange -x y disk fixed things on the test cluster.

Should it happen again, we indeed do have a bug where something is changing PV flags, and then this issue should be reopened.
```
Originally added on 2014-03-19 14:44:35 +0000 UTC.

Changed State: NotRepeatable
