### ISSUE TITLE
gnt-node list returns blank info when file storage paths do not exist on disk

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#840]
Originally reported of Google Code with ID 784.

```
<b>What steps will reproduce the problem?</b>
1. Upgrade a cluster with enabled file/sharedfile storage from 2.8/2.9 to 2.10
2. Make sure a storage path does not exist
3. Run gnt-node list

<b>What is the expected output? What do you see instead?</b>

gnt-node list will return questionmarks on all fields. This is because
storage.filestorage.GetFileStorageSpaceInfo() raises an unhandled exception and
causes backend.GetNodeInfo() to fail. The output in the node daemon log is:

 2014-03-20 14:02:43,602: ganeti-noded pid=16382 ERROR Error in RPC call
 Traceback (most recent call last):
   File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 181, in HandleRequest
     result = (True, method(serializer.LoadJson(req.request_body)))
   File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 762, in perspective_node_info
     return backend.GetNodeInfo(storage_units, hv_specs)
   File "/usr/share/ganeti/2.10/ganeti/backend.py", line 752, in GetNodeInfo
     (lambda (storage_type, storage_key, storage_params):
   File "/usr/share/ganeti/2.10/ganeti/backend.py", line 731, in _GetNamedNodeInfo
     return map(fn, names)
   File "/usr/share/ganeti/2.10/ganeti/backend.py", line 753, in <lambda>
     _ApplyStorageInfoFunction(storage_type, storage_key, storage_params)))
   File "/usr/share/ganeti/2.10/ganeti/backend.py", line 806, in _ApplyStorageInfoFunction
     return fn(storage_key, *args)
   File "/usr/share/ganeti/2.10/ganeti/backend.py", line 770, in _GetFileStorageSpaceInfo
     return filestorage.GetFileStorageSpaceInfo(path)
   File "/usr/share/ganeti/2.10/ganeti/storage/filestorage.py", line 56, in GetFileStorageSpaceInfo
     " path: %s - %s" % (path, e.strerror))
 CommandError: Failed to retrieve file system information about path:  - No such file or directory
 
Most likely, GetFileStorageSpaceInfo() should check for path existence and
return available and used size of zero for non-existing paths.

```
Originally added on 2014-03-31 08:05:51 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-03-31 08:45:48 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
This is actually working as intended. The question mark is the gnt-* list way to say 'there is something wrong'. We deliberately did not use zero here, because we wanted to make sure that there is a visible difference between the valid state of storage location that has no space left and a misconfiguration/error state.

In order to detect what exactly the problem is, 'gnt-cluster verify' correctly reports the source of the question marks:

Tue Apr  1 08:15:45 2014   - ERROR: node blablabla: The configured file storage path is unusable: Path '/srv/ganeti/file-storage' is not existing or not a directory.

The question marks are also used in other error cases (nodes not reachable, daemons crashed etc.), thus we stuck to that pattern of displaying '?' and having gnt-cluster verify to report the actual error.
```
Originally added on 2014-04-01 08:21:53 +0000 UTC.

Changed State: WontFix

**Comment by Ganeti-Issues-Migrator** [comment]
```
I get the same error, even after creating '/srv/ganeti/file-storage' directory on all nodes. 'gnt-cluster verify' no longer reports an error, but 'gnt-node list' still gives question marks and the exception is still raised in the node daemon log. It's important to notice that the exception does not include '/srv/ganeti/file-storage' as the non-existing path, but reports no path at all, as if the path is set by mistake to an empty string in the code:

Traceback (most recent call last):
  File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 181, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 762, in perspective_node_info
    return backend.GetNodeInfo(storage_units, hv_specs)
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 752, in GetNodeInfo
    (lambda (storage_type, storage_key, storage_params):
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 731, in _GetNamedNodeInfo
    return map(fn, names)
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 753, in <lambda>
    _ApplyStorageInfoFunction(storage_type, storage_key, storage_params)))
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 806, in _ApplyStorageInfoFunction
    return fn(storage_key, *args)
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 770, in _GetFileStorageSpaceInfo
    return filestorage.GetFileStorageSpaceInfo(path)
  File "/usr/share/ganeti/2.10/ganeti/storage/filestorage.py", line 56, in GetFileStorageSpaceInfo
    " path: %s - %s" % (path, e.strerror))
CommandError: Failed to retrieve file system information about path:  - No such file or directory
```
Originally added on 2014-05-21 10:54:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
We'll look into this. Thanks for providing more detailed information here.
```
Originally added on 2014-05-21 11:14:23 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
So, I had a look at this, and I had trouble reproducing it. I did:

1. install ganeti 2.8
2. create a cluster with file storage enabled
3. delete /srv/ganeti-file-storage
4. 'gnt-cluster verify' does not complain, but 'gnt-node list' does not show '?'
5. installed ganeti 2.10
6. ran cfgupgrade 
7. /etc/init.d/ganeti restart
8. gnt-cluster redist-conf
9. 'gnt-cluster verify' complains about the missing dir, 'gnt-node list' shows '?'
10. mkdir /srv/ganeti/file-storage
11. 'gnt-cluster verify' is happy, but 'gnt-node list' is also happy.

I tried the same going from 2.9 to 2.10.

What did I do differently than you?

To debug this, can you please look up the following things for me:

Did you have file storage enabled before the update?

In particular, can you give me, what 'gnt-cluster info' says for "file storage path" and "enabled disk templates" (if possible before and after the upgrade).

Can you look at /var/lib/ganeti/config.data and check the values for 'file-storage-path' and 'enabled-disk-templates'.

Thanks!
```
Originally added on 2014-05-21 14:02:08 +0000 UTC.

Changed State: NeedFeedback

**Comment by Ganeti-Issues-Migrator** [comment]
```
Sorry for the late reply. First I have to say that I run ganeti on Debian wheezy and I am using the packages from wheezy-backports. Also, the OP happens to be the maintainer of these packages. So, could that be related with the debian package itself (e.g. if it was touching config.data in some custom way)?

To answer your questions, I have never used the file storage template and I don't remember if that template was enabled before the upgrade but all recent backups of config.data say that it was enabled. After the upgrade, "file-storage-path" still pointed to "/srv/ganeti/file-storage" but the path did not exist, 'gnt-node list' was giving '?'s and 'gnt-cluster verify' complained about the missing path. I created the path on all nodes which fixed the 'gnt-cluster verify' error but 'gnt-node list' was still giving '?'s. Then I disabled the 'file' template and 'gnt-node list' output was finally ok. I left it in that condition for some days (I don't need the 'file' template) until today, when I thought to reenable the 'file' template to see if 'gnt-node list' continues to give correct output. Indeed it does. It does not give '?'s anymore.

Most recent backups of /var/lib/ganeti/config.data all contained 'file' in the enabled templates and the path was '/srv/ganeti/file-storage'. Also, just in case this is somehow related, the dictionary key for that path in config.data is not called 'file_storage_path' but 'file_storage_dir'.

Anyway, I consider this issue minor and it seems that disabling and reenabling the 'file' template is a viable workaround.
```
Originally added on 2014-06-04 12:43:47 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2016-01-07 15:52:23 +0000 UTC.

Changed State: New
