### ISSUE TITLE
ganeti Failed to migrate instance: Too many 'info migrate' broken answers

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#884]
Originally reported of Google Code with ID 828.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

# gnt-cluster --version
gnt-cluster (ganeti v2.5.2) 2.5.2

# gnt-cluster version
Software version: 2.5.2
Internode protocol: 2050000
Configuration format: 2050000
OS api version: 20
Export interface: 0

# hspace --version
hspace (ganeti-htools) version v2.5.2
compiled with ghc 7.4
running on linux x86_64


<b>What distribution are you using?</b>

Debian GNU/Linux 7


<b>What steps will reproduce the problem?</b>

gnt-instance migrate guest


<b>What is the expected output? What do you see instead?</b>

This command sometimes fails with the following output:

Mon May 12 11:10:25 2014 Migrating instance guest.domain
Mon May 12 11:10:25 2014 * checking disk consistency between source and target
Mon May 12 11:10:26 2014 * switching node vmhost11.domain to secondary mode
Mon May 12 11:10:26 2014 * changing into standalone mode
Mon May 12 11:10:28 2014 * changing disks into dual-master mode
Mon May 12 11:10:29 2014 * wait until resync is done
Mon May 12 11:10:35 2014 * preparing vmhost11.domain to accept the instance
Mon May 12 11:10:37 2014 * migrating instance to vmhost11.domain
Mon May 12 11:17:20 2014 Migration failed, aborting
Mon May 12 11:17:50 2014 * switching node vmhost11.domain to secondary mode
Mon May 12 11:17:52 2014 * changing into standalone mode
Mon May 12 11:17:53 2014 * changing disks into single-master mode
Mon May 12 11:17:54 2014 * wait until resync is done
Failure: command execution error:
Could not migrate instance guest.domain: Failed to migrate instance: Too many 'info migrate' broken answers


In the node-daemon.log on the primary for the instance, I see the following:


2014-05-12 11:10:39,956: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:10:42,464: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:11:01,956: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:11:31,074: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:11:49,064: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:11:51,573: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:11:54,082: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:13:03,621: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:13:09,297: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:13:14,325: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:13:42,823: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:14:08,148: ganeti-noded pid=2216 WARNING KVM: unknown 'info migrate' result: QEMU 1.1.2 monitor - type 'help' for more information
(qemu) iESC[K
2014-05-12 11:14:44,654: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:14:49,710: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:15:05,637: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:15:08,146: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:15:10,656: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:15:39,015: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:16:56,444: ganeti-noded pid=2216 WARNING KVM: unknown 'info migrate' result: QEMU 1.1.2 monitor - type 'help' for more information
(qemu) iESC[K
2014-05-12 11:16:58,954: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:17:01,463: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:17:15,384: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:17:18,582: ganeti-noded pid=2216 INFO KVM: empty 'info migrate' result
2014-05-12 11:17:20,585: ganeti-noded pid=2216 ERROR Failed to migrate instance: Too many 'info migrate' broken answers
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ganeti/backend.py", line 1329, in MigrateInstance
    hyper.MigrateInstance(instance, target, live)
  File "/usr/lib/pymodules/python2.7/ganeti/hypervisor/hv_kvm.py", line 1235, in MigrateInstance
    raise errors.HypervisorError("Too many 'info migrate' broken answers")
HypervisorError: Too many 'info migrate' broken answers


<b>Please provide any additional information below.</b>

I can't tell if this relates to https://code.google.com/p/ganeti/issues/detail?id=297.

Thanks,
Dan Bradley

```
Originally added on 2014-05-12 16:41:14 +0000 UTC.

Mentioned Issue with GoogleCode ID 297 has been migrated to GitHub with ID #353.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-14 10:56:57 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Unassigning myself as I'm won't be able to work on this.

There have been lots of improvements around the QEMU monitor interface in 2.8 and 2.10, so it might be worth trying those versions if at all possible.
```
Originally added on 2014-05-20 07:55:51 +0000 UTC.

Added Labels: Type-Defect Hypervisor-KVM
Added to Milestone: Release2.5

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-20 08:17:59 +0000 UTC.

Changed State: Accepted
Added to Milestone: Release2.13
Removed from Milestone: Release2.5

**Comment by Ganeti-Issues-Migrator** [comment]
```
As this was reported for an old version of Ganeti and a lot of changes happened both in Ganeti KVM code as well as QEMU, please try if this error still happens with the current Ganeti and QEMU versions. If so, please reopen the issue, thanks.
```
Originally added on 2015-07-15 13:41:32 +0000 UTC.

Changed State: NotRepeatable

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2015-07-15 13:41:48 +0000 UTC.

Added to Milestone: Unplanned
Removed from Milestone: Release2.13
