### ISSUE TITLE
ganeti fails with cpu_mask=63 

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#901]
Originally reported of Google Code with ID 845.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

<b>What distribution are you using?</b>
Debian Jessie 

<b>What steps will reproduce the problem?</b>
1. On a suitable host (4x 16core Opterons in my case) create an instance with "cpu_mask=63". This will also happen with anything that includes 63 as the upper limit of the cpu_mask.
2. Start it.
3. Enjoy the silence (non-working VM).

<b>What is the expected output? What do you see instead?</b>

root@comp-01:~# gnt-instance modify -H cpu_mask=63 vm-064
Modified instance vm-064
 - hv/cpu_mask -> 63
Please don't forget that most parameters take effect only at the next (re)start of the instance initiated by ganeti; restarting from within the instance will not be enough.
root@comp-01:~# gnt-instance start vm-064
Waiting for job 29090 for vm-064 ...
Job 29090 for vm-064 has failed: Failure: command execution error:
Could not start instance: Error while executing backend function: Python int too large to convert to C long


<b>Please provide any additional information below.</b>

The relevant entry from the node-deamon log:

2014-05-29 09:22:24,766: ganeti-noded pid=54441 INFO RunCmd echo 'info cpus' |  /usr/bin/socat STDIO UNIX-
CONNECT:/var/run/ganeti/kvm-hypervisor/ctrl/vm-064.monitor
2014-05-29 09:22:24,818: ganeti-noded pid=54441 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 181, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/2.10/ganeti/server/noded.py", line 616, in perspective_instance_start
    return backend.StartInstance(instance, startup_paused, trail)
  File "/usr/share/ganeti/2.10/ganeti/backend.py", line 1691, in StartInstance
    hyper.StartInstance(instance, block_devices, startup_paused)
  File "/usr/share/ganeti/2.10/ganeti/hypervisor/hv_kvm.py", line 2016, in StartInstance
    self._ExecuteKVMRuntime(instance, kvm_runtime, kvmhelp)
  File "/usr/share/ganeti/2.10/ganeti/hypervisor/hv_kvm.py", line 1994, in _ExecuteKVMRuntime
    self._ExecuteCpuAffinity(instance.name, up_hvp[constants.HV_CPU_MASK])
  File "/usr/share/ganeti/2.10/ganeti/hypervisor/hv_kvm.py", line 1174, in _ExecuteCpuAffinity
    self._AssignCpuAffinity(cpu_mask, pid, thread_dict)
  File "/usr/share/ganeti/2.10/ganeti/hypervisor/hv_kvm.py", line 1127, in _AssignCpuAffinity
    process_id, cls._BuildAffinityCpuMask(all_cpu_mapping))
OverflowError: Python int too large to convert to C long


```
Originally added on 2014-05-29 00:50:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-30 13:10:52 +0000 UTC.

Changed State: Accepted
Added to Milestone: Release2.10

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fortunately or unfortunately, the problem is not with Ganeti - the affinity library we use does not make use of functions for setting up cpu_set_t in an extendable way. It forces the conversion to long, failing miserably, causing this issue.

As a short-term fix, we can emit a warning and abort, stating that this is temporarily not working. Does not fix the problem, but handles silently broken VMs.

Long-term, looking into some other library allowing affinities to be set looks like a good idea: ps-util looks like a promising candidate. A patch for affinity could also work, but I am not seeing any signs of active development or maintenance, making a replacement preferable.
```
Originally added on 2014-05-30 15:01:20 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-05-30 15:01:54 +0000 UTC.

Added Labels: Type-Defect Hypervisor-KVM

**Comment by Ganeti-Issues-Migrator** [comment]
```
I was afraid it would be in that cursed affinity library.

And I say cursed because there is no Debian package for it, thus not only one has to read the fine print and get it via easy_install, it also means that in cases like this an updated version will not automagically make it into the system.

So yes, pretty please replace it with something more mainline or pull the code into ganeti itself.

```
Originally added on 2014-05-31 04:23:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
As this introduces a new dependency, it could only be fixed in stable-2.12.
Fixed in commit:

commit b04158d00d599f91c100b9134ac24c07a7d2d90a
Author: Hrvoje Ribicic <riba@google.com>
Date:   Tue Jun 17 10:30:45 2014 +0000

    Refactor process affinity setting into function
    
    This patch modifies the KVM code to move duplicated functionality into
    a new function, easing later changes.
    
    Signed-off-by: Hrvoje Ribicic <riba@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>

commit 0b26f68123857f566373a97eba307152281c09f8
Author: Hrvoje Ribicic <riba@google.com>
Date:   Tue Jun 17 16:10:50 2014 +0000

    Replace the affinity library with psutil
    
    This patch replaces the old and lacking affinity library with the
    psutil library, fixing issue 845.
    
    Signed-off-by: Hrvoje Ribicic <riba@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>



```
Originally added on 2014-06-18 18:18:43 +0000 UTC.

Mentioned Issue with GoogleCode ID 845 has been migrated to GitHub with ID #901.
Changed State: Fixed

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-06-27 10:11:59 +0000 UTC.

Added to Milestone: Release2.12
Removed from Milestone: Release2.10

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-10-10 11:40:54 +0000 UTC.

Changed State: Released
