### ISSUE TITLE
Unhandled Xen isntance states '------' and '--p-cd'

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#945]
Originally reported of Google Code with ID 889.

```
After an upgrade to 2.11

I got random issue saying "while contacting node: Error while executing backend function: hv_xen._XenToHypervisorInstanceState: unhandled Xen instance state '------'" but it on a different node everytime).

on the node:

2014-07-17 17:55:26,212: ganeti-noded pid=666 INFO RunCmd xm list
2014-07-17 17:55:26,381: ganeti-noded pid=666 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/2.11/ganeti/server/noded.py", line 182, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/2.11/ganeti/server/noded.py", line 761, in perspective_node_info
    return backend.GetNodeInfo(storage_units, hv_specs)
  File "/usr/share/ganeti/2.11/ganeti/backend.py", line 742, in GetNodeInfo
    hv_info = _GetHvInfoAll(hv_specs)
  File "/usr/share/ganeti/2.11/ganeti/backend.py", line 706, in _GetHvInfoAll
    result.append(_GetHvInfo(hvname, hvparams, get_hv_fn))
  File "/usr/share/ganeti/2.11/ganeti/backend.py", line 689, in _GetHvInfo
    return get_hv_fn(name).GetNodeInfo(hvparams=hvparams)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_xen.py", line 856, in GetNodeInfo
    instance_list = self._GetInstanceList(True, hvparams)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_xen.py", line 591, in _GetInstanceList
    include_node)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_xen.py", line 169, in _GetAllInstanceList
    return _ParseInstanceList(lines, include_node)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_xen.py", line 135, in _ParseInstanceList
    data[4] = _XenToHypervisorInstanceState(data[4])
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_xen.py", line 200, in _XenToHypervisorInstanceState
    instance_info)
HypervisorError: hv_xen._XenToHypervisorInstanceState: unhandled Xen instance state '------'
2014-07-17 17:55:26,384: ganeti-noded pid=666 INFO 77.75.57.112:58510 POST /node_info HTTP/1.1 200

And indeed, from time to time, xm list answer that :
srv001                            4  3176     1     ------ 1619505.5

but only for an instant..

Xen verison : xen-hypervisor-4.1-amd64         4.1.4-3+deb7u1
```
Originally added on 2014-07-18 09:22:11 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-07-18 09:26:00 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-07-30 09:49:29 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
The former has been fixed, I believe (please add the patches where it's been fixed), but a new state '--p-cd' appeared. So I'm just adding it to this issue.
```
Originally added on 2014-09-26 12:39:43 +0000 UTC.

Added Labels: Hypervisor-XenPVM Hypervisor-XenHVM

**Comment by Ganeti-Issues-Migrator** [comment]
```
Fixed in multiple patches. Last relevant one:

commit 6b16d04a318d33a59db24f2f7ee5e52721855428
Author: Hrvoje Ribicic <riba@google.com>
Date:   Tue Sep 15 10:37:11 2015 +0200

    Handle Xen 4.3 states better
    
    In Xen commit e1475a6693aac8cddc4bdd456548aa05a625556b, the output from
    xl list was extended to provide a reason for shutdowns. This breaks
    our somewhat strict parsing of the output in certain situations where
    the new states appear (e.g. the short suspension during a migration, or
    an instance reboot).
    
    This patch makes sure the new states (barring the mysterious watchdog
    state) are handled correctly.
    
    Signed-off-by: Hrvoje Ribicic <riba@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>
```
Originally added on 2016-01-11 15:47:10 +0000 UTC.

Changed State: Released
