### ISSUE TITLE
gnt-instance migrate fails "Error while executing backend function: 'vlan'"

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#949]
Originally reported of Google Code with ID 893.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

<b>What distribution are you using?</b>
# gnt-cluster --version
gnt-cluster (ganeti v2.11.3) 2.11.3
# gnt-cluster version
Software version: 2.11.3
Internode protocol: 2110000
Configuration format: 2110000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version v2.11.3
# hspace --version
hspace (ganeti) version v2.11.3
compiled with ghc 7.4
running on linux x86_64
# cat /etc/debian_version
7.6
# apt-cache policy ganeti
ganeti:
  Installed: 2.11.3-2~bpo70+1
  Candidate: 2.11.3-2~bpo70+1
  Package pin: 2.11.3-2~bpo70+1
  Version table:
 *** 2.11.3-2~bpo70+1 990
        100 http://debian.xxxxxxxx.de/debian/ wheezy-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2.10.5-1~bpo70+1 990
        100 http://debian.xxxxxxxx.de/debian/ wheezy-backports/main amd64 Packages
     2.9.5-1~bpo70+1 990
        100 http://debian.xxxxxxxx.de/debian/ wheezy-backports/main amd64 Packages


<b>What steps will reproduce the problem?</b>
gnt-instance migrate -f zzzzzzz censor


<b>What is the expected output? What do you see instead?</b>
  Tue Jul 22 19:36:17 2014 Migrating instance zzzzzzz.yyyyyy.xxxxxxxxx.de
  Tue Jul 22 19:36:17 2014 * checking disk consistency between source and target
  Tue Jul 22 19:36:20 2014 * switching node node2.yyyyyy.xxxxxxxxx.de to secondary mode
  Tue Jul 22 19:36:20 2014 * changing into standalone mode
  Tue Jul 22 19:36:22 2014 * changing disks into dual-master mode
  Tue Jul 22 19:36:26 2014 * wait until resync is done
  Tue Jul 22 19:36:27 2014 * preparing node2.yyyyyy.xxxxxxxxx.de to accept the instance
- Tue Jul 22 19:36:28 2014 Pre-migration failed, aborting
- Tue Jul 22 19:36:29 2014 * switching node node2.yyyyyy.xxxxxxxxx.de to secondary mode
- Tue Jul 22 19:36:29 2014 * changing into standalone mode
- Tue Jul 22 19:36:30 2014 * changing disks into single-master mode
- Tue Jul 22 19:36:32 2014 * wait until resync is done
- Failure: command execution error:
- Could not pre-migrate instance zzzzzzz.yyyyyy.xxxxxxxxx.de: Error while executing backend function: 'vlan' 


<b>Please provide any additional information below.</b>
# less /var/log/ganeti/node-daemon.log
[...]
2014-07-22 19:29:27,805: ganeti-noded pid=14816 INFO RunCmd /usr/bin/kvm --help
2014-07-22 19:29:27,821: ganeti-noded pid=14816 INFO RunCmd ganeti-kvmd
2014-07-22 19:29:27,829: ganeti-noded pid=14816 INFO RunCmd /usr/bin/kvm -device '?'
2014-07-22 19:29:28,145: ganeti-noded pid=14816 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/2.11/ganeti/server/noded.py", line 182, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/2.11/ganeti/server/noded.py", line 649, in perspective_accept_instance
    return backend.AcceptInstance(instance, info, target)
  File "/usr/share/ganeti/2.11/ganeti/backend.py", line 2061, in AcceptInstance
    hyper.AcceptInstance(instance, info, target)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_kvm.py", line 2460, in AcceptInstance
    incoming=incoming_address)
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_kvm.py", line 1969, in _ExecuteKVMRuntime
    self._ConfigureNIC(instance, nic_seq, nic, taps[nic_seq])
  File "/usr/share/ganeti/2.11/ganeti/hypervisor/hv_kvm.py", line 1101, in _ConfigureNIC
    if nic.nicparams[constants.NIC_VLAN]:
KeyError: 'vlan'
[...]

# cat /var/lib/ganeti/config.data | python -mjson.tool | less
[...]
            "name": "zzzzzzz.yyyyyy.xxxxxxxxx.de", 
            "network_port": 11029, 
            "nics": [
                {
                    "ip": "x.y.z.5", 
                    "mac": "00:e6:e7:bc:3b:2c", 
                    "network": "3f5121e3-3214-45f6-b239-e0babcf0c9b7", 
                    "nicparams": {
                        "link": "br0", 
                        "mode": "bridged", 
                        "vlan": ""
                    }, 
                    "uuid": "6f889076-4e89-4532-97ce-7447cc8ae9ad"
                }
            ], 
[...]

```
Originally added on 2014-07-22 17:43:50 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Can you please provide a few more information on your cluster
setup? I just couldn't reproduce the problem.
```
Originally added on 2014-07-22 18:20:55 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I don't know what you need

Cluster parameters: 
  candidate pool size: 10
  maximal number of jobs running simultaneously: 20
  master netdev: br0
  master netmask: 64
  primary ip version: 6

Default nic parameters: 
  default: 
    link: br0
    mode: bridged
    vlan: 



Network setup:
eth0
  br0 (primary & secondary // is to be changed soon)

no VLANs in use all VMs connected directly to br0

```
Originally added on 2014-07-22 18:44:09 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-07-23 09:00:52 +0000 UTC.

Added Labels: Priority-High
Added to Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
commit 3089f062aa638090e9586d7084a28e98d9d6f566
Author: Apollon Oikonomopoulos <apoikos@gmail.com>
Date:   Wed Jul 23 12:12:11 2014 +0300

    KVM: fix NIC configuration with absent NIC VLAN
    
    Commit 6b47261a exported the VLAN to the KVM NIC configuration scripts.
    However, in doing so it assumed that the VLAN is always present in the
    runtime, which is not true for instances being migrated but started on
    Ganeti versions prior to 2.10.6.
    
    We fix this by exporting the VLAN nicparam only if it actually exists.
    This closes issue #893.
    
    Signed-off-by: Apollon Oikonomopoulos <apoikos@gmail.com>
    Signed-off-by: Klaus Aehlig <aehlig@google.com>
    Reviewed-by: Klaus Aehlig <aehlig@google.com>

```
Originally added on 2014-07-23 10:33:17 +0000 UTC.

Changed State: Fixed
Added to Milestone: Release2.10
Removed from Milestone: Release2.11

**Comment by Ganeti-Issues-Migrator** [comment]
```
I don't use Xen, but I suspect a corresponding change is required for that too.

That is, commit 6b47261a also added:

--- a/lib/hypervisor/hv_xen.py
+++ b/lib/hypervisor/hv_xen.py
@@ -458,6 +458,7 @@ class XenHypervisor(hv_base.BaseHypervisor):
     data.write("INTERFACE_UUID=%s\n" % nic.uuid)
     data.write("MODE=%s\n" % nic.nicparams[constants.NIC_MODE])
     data.write("LINK=%s\n" % nic.nicparams[constants.NIC_LINK])
+    data.write("VLAN=%s\n" % nic.nicparams[constants.NIC_VLAN])

     try:
       utils.WriteFile(cfg_file, data=data.getvalue())


```
Originally added on 2014-07-29 14:03:58 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-07-29 14:10:25 +0000 UTC.

Changed State: Accepted

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2014-07-30 08:07:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
As this particular bit of code is common to both hypervisors, no Xen-specific tinkering was needed. I'll mark this as released.
```
Originally added on 2015-05-28 13:08:27 +0000 UTC.

Changed State: Released
