### ISSUE TITLE
gnt-node add

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#99]
Originally reported of Google Code with ID 43.

```
<b>What steps will reproduce the problem?</b>
1. node1:/srv/ganeti/os# gnt-node add node2.example.com
2. Are you sure you want to continue connecting (yes/no)? yes
 

<b>What is the expected output? What do you see instead?</b>

Traceback (most recent call last):
  File "/usr/local/sbin/gnt-node", line 166, in ?
    sys.exit(GenericMain(commands))
  File "/usr/local/lib/python2.4/site-packages/ganeti/cli.py", line 251, in
GenericMain
    result = func(options, args)
  File "/usr/local/sbin/gnt-node", line 34, in AddNode
    SubmitOpCode(op)
  File "/usr/local/lib/python2.4/site-packages/ganeti/cli.py", line 208, in
SubmitOpCode
    return proc.ExecOpCode(op, logger.ToStdout)
  File "/usr/local/lib/python2.4/site-packages/ganeti/mcpu.py", line 120,
in ExecOpCode
    result = lu.Exec(feedback_fn)
  File "/usr/local/lib/python2.4/site-packages/ganeti/cmdlib.py", line
1436, in Exec
    self.cfg.GetHostKey())
  File "/usr/local/lib/python2.4/site-packages/ganeti/cmdlib.py", line 376,
in _UpdateKnownHosts
    key = parts[2]
IndexError: list index out of range

<b>What version of the product are you using? On what operating system?</b>

I am ussing ganeti-1.2b1 on Debian Etch

<b>Please provide any additional information below.</b>

I try to follow this guide:
http://www.howtoforge.com/ganeti_xen_cluster_management_debian_etch
but in the step 5, i get this error.
Thks.-

```
Originally added on 2008-08-02 22:57:19 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
Hi, are you using 1.2b1? That's a year old already... Please try to reproduce the
problem with the latest version (1.2.5).

thanks,
iustin
```
Originally added on 2008-08-04 08:47:05 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
To clean up here a bit:

Juan, could you please check if your problem persists with 1.2.6?

If not, this bug might be closed in about a month or so.

By the way, you are calling the command with the example.com hostname - are you sure
this hostname can be resolved in your network?
```
Originally added on 2008-12-09 12:21:02 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
No activity on the bug for a long while, closing it. Please reopen if
you can reproduce the problem with a newer release.

regards,
iustin

```
Originally added on 2009-04-15 14:45:27 +0000 UTC.

Changed State: Invalid

**Comment by Ganeti-Issues-Migrator** [comment]
```
-- Empty comment --
```
Originally added on 2009-04-15 14:47:00 +0000 UTC.

Changed State: NotRepeatable
